/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

typedef struct __ATVMediaItem *ATVMediaItemRef;

typedef struct BRMultiPartImageMap {
	id _field1;
	id _field2;
} BRMultiPartImageMap;

typedef struct BRTimeRange {
	double _field1;
	double _field2;
} BRTimeRange;

typedef struct BRFocusEdge {
	CGPoint _field1;
	CGPoint _field2;
} BRFocusEdge;

typedef struct __ATVDataClient *ATVDataClientRef;

typedef struct __ATVMediaQuery *ATVMediaQueryRef;

typedef struct __ATVDataServer *ATVDataServerRef;

typedef struct __ATVMediaCollection *ATVMediaCollectionRef;

typedef struct __ATVMediaType *ATVMediaTypeRef;


