/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRMediaShelfControl.h"


__attribute__((visibility("hidden")))
@interface BRActionShelfControl : BRMediaShelfControl {
@private
	int _style;	// 252 = 0xfc
	long _previousIndex;	// 256 = 0x100
}
@property(assign) int actionControlStyle;	// G=0x315d9a89; S=0x315d9a79; converted property
// converted property getter: - (int)actionControlStyle;	// 0x315d9a89
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x315a48a1
// converted property setter: - (void)setActionControlStyle:(int)style;	// 0x315d9a79
@end

