/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"
#import "BRAXSelectionChangeProtocol.h"
#import "BRAXTitleChangeProtocol.h"

@class BRDividerControl, BRHeaderControl, BRImageControl, BRTextControl, BRReflectionControl;

@interface BRAlertControl : BRControl <BRAXTitleChangeProtocol, BRAXSelectionChangeProtocol> {
@private
	SEL _eventSelector;	// 40 = 0x28
	BRHeaderControl *_header;	// 44 = 0x2c
	BRDividerControl *_divider;	// 48 = 0x30
	int _type;	// 52 = 0x34
	BRTextControl *_primary;	// 56 = 0x38
	BRTextControl *_secondary;	// 60 = 0x3c
	BRImageControl *_image;	// 64 = 0x40
	BRReflectionControl *_reflection;	// 68 = 0x44
}
@property(retain) BRImageControl *image;	// G=0x315d9e9d; S=0x315d9ebd; converted property
@property(retain) id primaryText;	// G=0x315d9fa5; S=0x315da009; converted property
@property(retain) id secondaryText;	// G=0x315d9f2d; S=0x315d9f5d; converted property
@property(retain) id title;	// G=0x315da045; S=0x315da065; converted property
+ (id)alertForError:(id)error;	// 0x315da239
+ (id)alertOfType:(int)type;	// 0x315da1a9
+ (id)alertOfType:(int)type titled:(id)titled primaryText:(id)text secondaryText:(id)text4;	// 0x315da1e9
- (id)init;	// 0x315da191
- (id)initWithType:(int)type;	// 0x315da171
- (id)initWithType:(int)type titled:(id)titled primaryText:(id)text secondaryText:(id)text4;	// 0x315da485
- (id)_controlsForType:(int)type;	// 0x315d9ac1
- (void)_layoutSubcontrolsForAlert;	// 0x315da571
- (void)_layoutSubcontrolsForInfo;	// 0x315da83d
- (id)_primaryTextAttibutesForType:(int)type;	// 0x315dab21
- (id)axSelectedItemText;	// 0x315d9a99
- (id)axTitleText;	// 0x315d9aad
- (void)controlWasActivated;	// 0x315da539
- (void)dealloc;	// 0x315da3e1
// converted property getter: - (id)image;	// 0x315d9e9d
- (void)layoutSubcontrols;	// 0x315d9e69
// converted property getter: - (id)primaryText;	// 0x315d9fa5
// converted property getter: - (id)secondaryText;	// 0x315d9f2d
// converted property setter: - (void)setImage:(id)image;	// 0x315d9ebd
// converted property setter: - (void)setPrimaryText:(id)text;	// 0x315da009
- (void)setPrimaryText:(id)text withAttributes:(id)attributes;	// 0x315d9fd5
// converted property setter: - (void)setSecondaryText:(id)text;	// 0x315d9f5d
- (void)setSecondaryText:(id)text withAttributes:(id)attributes;	// 0x315d9ef9
// converted property setter: - (void)setTitle:(id)title;	// 0x315da065
- (void)setType:(int)type;	// 0x315da099
// converted property getter: - (id)title;	// 0x315da045
@end

