/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface BRApplianceCategoryListProvider : NSObject {
@private
	NSArray *_categories;	// 4 = 0x4
	NSDictionary *_attributes;	// 8 = 0x8
}
@property(retain) NSArray *categories;	// G=0x3164e745; S=0x3164e939; converted property
@property(retain) id textAttributes;	// G=0x3164e735; S=0x3164e989; converted property
// converted property getter: - (id)categories;	// 0x3164e745
- (long)categoryIndexForIdentifier:(id)identifier;	// 0x3164e839
- (void)dealloc;	// 0x3164ea09
- (long)defaultCategoryIndex;	// 0x3164e8c9
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x3164e785
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x3164e75d
- (id)list:(id)list sectionHeaderForSection:(long)section;	// 0x3164e759
- (long)numberOfSectionsInList:(id)list;	// 0x3164e755
// converted property setter: - (void)setCategories:(id)categories;	// 0x3164e939
// converted property setter: - (void)setTextAttributes:(id)attributes;	// 0x3164e989
// converted property getter: - (id)textAttributes;	// 0x3164e735
@end

