/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSMutableDictionary;

@interface BRApplianceCategory : NSObject {
@private
	NSMutableDictionary *_info;	// 4 = 0x4
}
@property(retain) id action;	// G=0x315bee25; S=0x315bee51; converted property
@property(retain) id identifier;	// G=0x31599949; S=0x31599005; converted property
@property(assign) BOOL isDefaultCategory;	// G=0x31599acd; S=0x3159918d; converted property
@property(assign) BOOL isStoreCategory;	// G=0x3159c8e1; S=0x31599079; converted property
@property(assign) BOOL isStoreDependent;	// G=0x315bed9d; S=0x315bedd9; converted property
@property(retain) id name;	// G=0x31599a31; S=0x31598fd9; converted property
@property(assign) float preferredOrder;	// G=0x315999f9; S=0x31599031; converted property
@property(assign) BOOL shouldDisplayOnStartup;	// G=0x315bed61; S=0x315990c5; converted property
+ (id)categoryWithName:(id)name identifier:(id)identifier preferredOrder:(float)order;	// 0x31598f01
- (id)init;	// 0x31598f7d
// converted property getter: - (id)action;	// 0x315bee25
- (void)dealloc;	// 0x3159aa99
- (id)description;	// 0x315bee7d
// converted property getter: - (id)identifier;	// 0x31599949
// converted property getter: - (BOOL)isDefaultCategory;	// 0x31599acd
// converted property getter: - (BOOL)isStoreCategory;	// 0x3159c8e1
// converted property getter: - (BOOL)isStoreDependent;	// 0x315bed9d
// converted property getter: - (id)name;	// 0x31599a31
// converted property getter: - (float)preferredOrder;	// 0x315999f9
// converted property setter: - (void)setAction:(id)action;	// 0x315bee51
// converted property setter: - (void)setIdentifier:(id)identifier;	// 0x31599005
// converted property setter: - (void)setIsDefaultCategory:(BOOL)category;	// 0x3159918d
// converted property setter: - (void)setIsStoreCategory:(BOOL)category;	// 0x31599079
// converted property setter: - (void)setIsStoreDependent:(BOOL)dependent;	// 0x315bedd9
// converted property setter: - (void)setName:(id)name;	// 0x31598fd9
// converted property setter: - (void)setPreferredOrder:(float)order;	// 0x31599031
// converted property setter: - (void)setShouldDisplayOnStartup:(BOOL)displayOnStartup;	// 0x315990c5
// converted property getter: - (BOOL)shouldDisplayOnStartup;	// 0x315bed61
@end

