/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@protocol BRAppliance;

__attribute__((visibility("hidden")))
@interface BRApplianceColumnControl : BRControl {
@private
	id<BRAppliance> _appliance;	// 40 = 0x28
	BRControl *_applianceLabel;	// 44 = 0x2c
	float _headerWidth;	// 48 = 0x30
	float _maxCategoryWidth;	// 52 = 0x34
}
@property(readonly, assign) float headerWidth;	// G=0x3165ff49; converted property
@property(assign) float maxCategoryWidth;	// G=0x3165cd65; S=0x3165cd55; converted property
- (id)initWithAppliance:(id)appliance;	// 0x3165cf89
- (void)dealloc;	// 0x3165cf2d
// converted property getter: - (float)headerWidth;	// 0x3165ff49
- (void)layoutSubcontrols;	// 0x316602bd
// converted property getter: - (float)maxCategoryWidth;	// 0x3165cd65
- (void)reload;	// 0x3165cda9
- (void)resetMaxCategoryWidth;	// 0x3165cd95
- (void)resetMetrics;	// 0x3165cd75
// converted property setter: - (void)setMaxCategoryWidth:(float)width;	// 0x3165cd55
@end

