/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMenuListItemProvider.h"

@class NSDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface BRApplianceListProvider : NSObject <BRMenuListItemProvider> {
@private
	NSArray *_applianceInfo;	// 4 = 0x4
	NSDictionary *_attributes;	// 8 = 0x8
}
@property(retain) id textAttributes;	// G=0x3159cc39; S=0x3159682d; converted property
- (id)init;	// 0x3159650d
- (void)_loadAppliances;	// 0x3159654d
- (id)applianceInfoAtIndex:(long)index;	// 0x315972d1
- (long)applianceInfoIndexForKey:(id)key;	// 0x3159cb19
- (void)dealloc;	// 0x315dbf61
- (float)heightForRow:(long)row;	// 0x31596af5
- (long)itemCount;	// 0x31596ad5
- (id)itemForRow:(long)row;	// 0x31596afd
- (void)reloadAppliances;	// 0x315dbf4d
- (BOOL)rowSelectable:(long)selectable;	// 0x315dbf49
// converted property setter: - (void)setTextAttributes:(id)attributes;	// 0x3159682d
// converted property getter: - (id)textAttributes;	// 0x3159cc39
- (id)titleForRow:(long)row;	// 0x31596ce9
@end

