/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@class NSMutableArray, NSTimer, NSAutoreleasePool, BREvent;
@protocol BRResponder;

@interface BRApplication : NSObject {
@private
	id _delegate;	// 4 = 0x4
	NSObject<BRResponder> *_firstResponder;	// 8 = 0x8
	BREvent *_currentEvent;	// 12 = 0xc
	NSTimer *_retriggerTimer;	// 16 = 0x10
	NSMutableArray *_eventQueue;	// 20 = 0x14
	NSAutoreleasePool *_runLoopPool;	// 24 = 0x18
	CFRunLoopSourceRef _source;	// 28 = 0x1c
	CFRunLoopRef _mainRunLoop;	// 32 = 0x20
	double _flushBeforeTimeStamp;	// 36 = 0x24
	long _retriggerCount;	// 44 = 0x2c
	double _nextRetriggerDelay;	// 48 = 0x30
	BOOL _handlingEvent;	// 56 = 0x38
	BOOL _isInModalLoop;	// 57 = 0x39
	BOOL _eventsBlocked;	// 58 = 0x3a
	BOOL _delegateRetained;	// 59 = 0x3b
	BOOL _isTerminating;	// 60 = 0x3c
}
@property(readonly, retain) BREvent *currentEvent;	// G=0x31626efd; converted property
@property(assign) id delegate;	// G=0x31626ebd; S=0x31627235; converted property
@property(retain) id firstResponder;	// G=0x31626eed; S=0x31626edd; converted property
@property(assign) BOOL isInModalLoop;	// G=0x31626f1d; S=0x31626f0d; converted property
@property(readonly, assign) BOOL isTerminating;	// G=0x31626ecd; converted property
@property(readonly, assign) double nextRetriggerDelay;	// G=0x31626f3d; converted property
@property(readonly, assign) long retriggerCount;	// G=0x31626f2d; converted property
+ (id)sharedApplication;	// 0x31590b3d
- (id)init;	// 0x31590b81
- (void)_blockEvents;	// 0x31626f4d
- (void)_drainRunLoopPool;	// 0x31626fed
- (void)_handler;	// 0x31627711
- (void)_registerForEvents;	// 0x316279a1
- (void)_retriggerEvent:(id)event;	// 0x31626f99
- (void)_run;	// 0x316275d5
- (void)_setRetainedDelegate:(id)delegate;	// 0x31626f5d
- (void)_unblockEvents;	// 0x31627091
- (void)cancelRetriggerCurrentEvent;	// 0x316270bd
// converted property getter: - (id)currentEvent;	// 0x31626efd
- (void)dealloc;	// 0x31627291
// converted property getter: - (id)delegate;	// 0x31626ebd
- (void)dispatchEventOnEventThread:(id)thread;	// 0x31627205
- (void)emptyQueue;	// 0x316274fd
// converted property getter: - (id)firstResponder;	// 0x31626eed
// converted property getter: - (BOOL)isInModalLoop;	// 0x31626f1d
// converted property getter: - (BOOL)isTerminating;	// 0x31626ecd
// converted property getter: - (double)nextRetriggerDelay;	// 0x31626f3d
- (void)postEvent:(id)event;	// 0x316273c1
// converted property getter: - (long)retriggerCount;	// 0x31626f2d
- (void)retriggerCurrentEvent;	// 0x316271e9
- (void)retriggerCurrentEventAfterDelay:(double)delay;	// 0x31627105
- (void)retriggerCurrentEventWithDecreasingDelay;	// 0x3162718d
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x31627235
// converted property setter: - (void)setFirstResponder:(id)responder;	// 0x31626edd
// converted property setter: - (void)setIsInModalLoop:(BOOL)modalLoop;	// 0x31626f0d
- (void)terminate;	// 0x31627305
@end

