/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRController.h"

@class BRWaitPromptControl, BRAuthenticationResources, NSTimer, BRAccountType;

@interface BRAuthenticationController : BRController {
@private
	BRAccountType *_accountType;	// 56 = 0x38
	BRAuthenticationResources *_authResources;	// 60 = 0x3c
	BRController *_controller;	// 64 = 0x40
	BRWaitPromptControl *_waitPrompt;	// 68 = 0x44
	int _mode;	// 72 = 0x48
	NSTimer *_authTimeoutTimer;	// 76 = 0x4c
	NSTimer *_promptTimer;	// 80 = 0x50
}
+ (id)authenticationControllerForController:(id)controller accountType:(id)type;	// 0x3168244d
+ (id)authenticationControllerForController:(id)controller accountType:(id)type mode:(int)mode;	// 0x31682471
+ (id)controller;	// 0x31681d15
- (long)_askIfAccountPasswordShouldBeRemembered:(id)_askIfAccountPassword;	// 0x31682941
- (id)_askUserForPasswordForAccount:(id)account;	// 0x31682aa5
- (id)_askUserForUsername:(id)username;	// 0x31683131
- (id)_askUserForUsernameForAccount:(id)account;	// 0x31682d41
- (void)_authenticate;	// 0x31681d19
- (void)_authenticateAccount:(id)account;	// 0x316833bd
- (void)_authenticationCancelled:(id)cancelled;	// 0x31681e39
- (void)_authenticationFailed:(id)failed;	// 0x31681ecd
- (void)_authenticationSucceeded:(id)succeeded;	// 0x31682015
- (void)_authenticationTimedOut:(id)anOut;	// 0x31682631
- (id)_initWithController:(id)controller accountType:(id)type mode:(int)mode;	// 0x31682f31
- (id)_makeNewAccountOfType:(id)type;	// 0x31682345
- (id)_qualifyAccount:(id)account;	// 0x31682149
- (void)_removeUnauthorizedAccount:(id)account;	// 0x31681dd9
- (id)_selectAccountForAccountType:(id)accountType;	// 0x316823b1
- (id)_setAccountOptionsForAccount:(id)account;	// 0x316820d5
- (BOOL)_shouldAttemptAuthorizationAgainForAccount:(id)account userInfo:(id)info;	// 0x316827dd
- (void)_showPrompt:(id)prompt;	// 0x31681d85
- (id)_updateAccount:(id)account;	// 0x31682211
- (void)dealloc;	// 0x3168259d
- (void)wasPopped;	// 0x316824b5
- (void)wasPushed;	// 0x31682545
@end

