/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMetadataPopulator.h"


__attribute__((visibility("hidden")))
@interface BRBaseMetadataPopulator : NSObject <BRMetadataPopulator> {
}
- (void)_populateMetadataLabels:(id *)labels andValues:(id *)values forAsset:(id)asset;	// 0x315b603d
- (id)axMetadataFromAsset:(id)asset;	// 0x3161ffd1
- (id)copyrightForAsset:(id)asset;	// 0x315b9291
- (void)populateLayer:(id)layer fromAsset:(id)asset;	// 0x315b5d39
- (void)populateLongDescriptionLayer:(id)layer fromAsset:(id)asset;	// 0x3161fe65
- (void)populateMetadataLabels:(id *)labels andValues:(id *)values forAsset:(id)asset;	// 0x3161ff8d
- (id)ratingForAsset:(id)asset;	// 0x315b5e9d
- (id)starRatingForAsset:(id)asset;	// 0x315b5f05
- (id)summaryForAsset:(id)asset;	// 0x315b5f41
- (id)titleForAsset:(id)asset;	// 0x315b5e61
@end

