/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSTimer;

@interface BRBackgroundTaskManager : BRSingleton {
@private
	int _numberOfCurrentBackgroundProcesses;	// 4 = 0x4
	double _lastUserActivity;	// 8 = 0x8
	NSTimer *_backgroundProcessSuppressionTimer;	// 16 = 0x10
	NSTimer *_heavyBackgroundProcessSuppresionTimer;	// 20 = 0x14
}
+ (BOOL)backgroundTasksRunning;	// 0x315bea51
+ (void)finishedBackgroundProcessing;	// 0x315a0a29
+ (void)finishedFileCopy:(id)copy;	// 0x315bed1d
+ (void)finishedMediaSyncing;	// 0x315a09e1
+ (void)holdOffBackgroundTasks;	// 0x315aaa31
+ (BOOL)mediaSyncInProgress;	// 0x315bea39
+ (BOOL)okToDoBackgroundProcessing;	// 0x315a7c89
+ (void)setSingleton:(id)singleton;	// 0x3159ffe5
+ (id)singleton;	// 0x3159ff39
+ (void)startedFileCopy:(id)copy;	// 0x315becd9
+ (void)startingBackgroundProcessing;	// 0x3159ff15
+ (void)startingMediaSyncing;	// 0x3159fecd
+ (double)timeSinceLastUserAction;	// 0x3162872d
- (id)init;	// 0x3159ff45
- (BOOL)_backgroundTasksRunning;	// 0x315bea75
- (void)_finishedBackgroundProcessing;	// 0x315a0a4d
- (void)_holdOffBackgroundTasks;	// 0x315aaa55
- (void)_holdOffHeavyBackgroundTasks;	// 0x31628631
- (BOOL)_okToDoBackgroundProcessing;	// 0x315a7cad
- (void)_sendResumeBackgroundProcessingNotification;	// 0x315ae6a5
- (void)_sendResumeHeavyBackgroundProcessingNotification;	// 0x31628751
- (void)_sendStopBackgroundProcessingNotification;	// 0x315aab0d
- (void)_sendStopHeavyBackgroundProcessingNotification;	// 0x31628795
- (void)_setOKToDoBackgroundProcessing:(id)doBackgroundProcessing;	// 0x315ae671
- (void)_setOKToDoHeavyBackgroundProcessing:(id)doHeavyBackgroundProcessing;	// 0x316287d9
- (void)_startingBackgroundProcessing;	// 0x3159fff1
- (double)_timeSinceLastUserAction;	// 0x316285f5
- (void)_updateActivity:(id)activity;	// 0x315a0a61
- (void)dealloc;	// 0x316286d9
@end

