/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRSelectionLozengeLayer.h"


__attribute__((visibility("hidden")))
@interface BRBlueGlowSelectionLozengeLayerBacking : BRSelectionLozengeLayer {
}
- (id)init;	// 0x3164f699
- (float)edgeInset;	// 0x3164f8d1
- (id)preferredActionForKey:(id)key;	// 0x3164f611
- (void)setFocused:(BOOL)focused;	// 0x3164f9e1
@end

