/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRListControl, BRDropShadowControl;

__attribute__((visibility("hidden")))
@interface BRBoxListControl : BRControl {
@private
	BRListControl *_list;	// 40 = 0x28
	BRDropShadowControl *_shadow;	// 44 = 0x2c
}
@property(retain) id providers;	// G=0x315dfe81; S=0x315dfea1; converted property
- (id)init;	// 0x315e09d5
- (void)dealloc;	// 0x315dff09
- (void)layoutSubcontrols;	// 0x315e0b61
- (float)listHeightToMaximum:(float)maximum;	// 0x315dfe61
// converted property getter: - (id)providers;	// 0x315dfe81
- (void)setProvider:(id)provider;	// 0x315dfed5
// converted property setter: - (void)setProviders:(id)providers;	// 0x315dfea1
@end

