/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRBackgroundTask.h"


@interface BRCacheCleaner : BRBackgroundTask {
}
+ (void)clearCaches;	// 0x31653f6d
+ (void)decrementWebControlCount;	// 0x31653fc9
+ (void)incrementWebControlCount;	// 0x3165404d
- (BOOL)perform:(id)perform;	// 0x31653f41
@end

