/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSString, BRControl;

@interface BRControlMediator : NSObject {
@private
	NSString *_identifier;	// 4 = 0x4
	BRControl *_control;	// 8 = 0x8
	BRControl *_preview;	// 12 = 0xc
	BOOL _active;	// 16 = 0x10
}
@property(assign) BOOL active;	// G=0x31620cad; S=0x31621089; converted property
@property(retain) BRControl *control;	// G=0x31620cbd; S=0x31621015; converted property
@property(retain) NSString *identifier;	// G=0x31620c9d; S=0x316210d9; converted property
@property(retain) id previewControl;	// G=0x31620ccd; S=0x31620fa1; converted property
+ (id)mediator;	// 0x316211c9
+ (id)mediatorWithControl:(id)control identifier:(id)identifier;	// 0x3162117d
- (id)init;	// 0x31620cdd
// converted property getter: - (BOOL)active;	// 0x31620cad
// converted property getter: - (id)control;	// 0x31620cbd
- (void)dealloc;	// 0x31621111
// converted property getter: - (id)identifier;	// 0x31620c9d
// converted property getter: - (id)previewControl;	// 0x31620ccd
// converted property setter: - (void)setActive:(BOOL)active;	// 0x31621089
// converted property setter: - (void)setControl:(id)control;	// 0x31621015
// converted property setter: - (void)setIdentifier:(id)identifier;	// 0x316210d9
// converted property setter: - (void)setPreviewControl:(id)control;	// 0x31620fa1
@end

