/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@protocol BRContextMenuUtility <NSObject>
+ (id)utility;
- (id)contextMenuProviderForObject:(id)object target:(id)target selector:(SEL)selector;
- (void)handleSelectionForObject:(id)object sender:(id)sender context:(id)context;
@end

