/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class NSArray, NSMutableArray, NSTimer, BRMediaType;

@interface BRCoverArtPreviewControl : BRControl {
@private
	NSArray *_imageProxies;	// 40 = 0x28
	NSMutableArray *_availableImages;	// 44 = 0x2c
	BRMediaType *_mediaType;	// 48 = 0x30
	NSTimer *_crossfadeTimer;	// 52 = 0x34
	long _imageIndex;	// 56 = 0x38
	float _rotation;	// 60 = 0x3c
	BOOL _artworkNeedsDeletterboxing;	// 64 = 0x40
	BOOL _actionAdded;	// 65 = 0x41
	BOOL _onlyDefaultsAvailable;	// 66 = 0x42
}
- (id)init;	// 0x315a2271
- (void)_cleanupTimer;	// 0x315a45a5
- (void)_crossFadeToNextImage:(id)nextImage;	// 0x315e16a1
- (void)_imageUnavailable:(id)unavailable;	// 0x315e17e1
- (void)_loadImage:(id)image;	// 0x315a4031
- (void)_scheduleTimerOnMainThread;	// 0x315b80a1
- (void)_updateCoverArt:(id)art;	// 0x315a3e19
- (void)controlWasActivated;	// 0x315a4441
- (void)controlWasDeactivated;	// 0x315a4f41
- (void)dealloc;	// 0x315a67dd
- (void)layoutSubcontrols;	// 0x315e14f5
- (void)setDeletterboxAssetArtwork:(BOOL)artwork;	// 0x315b7da5
- (void)setImageProxies:(id)proxies;	// 0x315e1241
- (void)setImageProxy:(id)proxy;	// 0x315e14c1
- (void)setMissingAssetType:(id)type;	// 0x315b7d6d
- (void)setRotation:(float)rotation;	// 0x315a2371
@end

