/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSMutableDictionary;

@interface BRDarwinNotificationTranslator : BRSingleton {
@private
	NSMutableDictionary *_registrations;	// 4 = 0x4
}
+ (BOOL)deregisterDarwinNotification:(const char *)notification;	// 0x31689395
+ (int)notificationTokenForDarwinNotification:(const char *)darwinNotification;	// 0x3168933d
+ (BOOL)registerDarwinNotification:(const char *)notification sendsNotificationNamed:(id)named;	// 0x316893c9
+ (void)setSingleton:(id)singleton;	// 0x316892f1
+ (id)singleton;	// 0x316892e5
- (id)init;	// 0x31689401
- (BOOL)_deregisterDarwinNotification:(const char *)notification;	// 0x316898c9
- (BOOL)_registerDarwinNotification:(const char *)notification sendsNotificationNamed:(id)named;	// 0x316896fd
- (id)_registrationForDarwinNotification:(const char *)darwinNotification;	// 0x316892fd
- (id)_registrationForToken:(int)token;	// 0x3168945d
- (void)dealloc;	// 0x3168953d
@end

