/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRActionShelfControl, BRCoverArtPreviewControl, BRTextControl;
@protocol BRProvider;

@interface BRDetailedMediaControl : BRControl {
@private
	BRControl *_metadata;	// 40 = 0x28
	BRCoverArtPreviewControl *_coverArtPreviewControl;	// 44 = 0x2c
	BRControl *_textLine;	// 48 = 0x30
	BRControl *_previewBrowser;	// 52 = 0x34
	BRActionShelfControl *_actionShelf;	// 56 = 0x38
	BRTextControl *_expiryText;	// 60 = 0x3c
	id<BRProvider> _metadataProvider;	// 64 = 0x40
	id<BRProvider> _textLineProvider;	// 68 = 0x44
	id<BRProvider> _previewBrowserProvider;	// 72 = 0x48
	int _style;	// 76 = 0x4c
	BOOL _detailsTogglingEnabled;	// 80 = 0x50
	BOOL _autoRefreshMetadata;	// 81 = 0x51
}
@property(retain) id actionProviders;	// G=0x315e401d; S=0x315e403d; converted property
@property(retain) BRCoverArtPreviewControl *coverArtPreviewControl;	// G=0x315e3e8d; S=0x315e43ed; converted property
@property(assign) int detailControlStyle;	// G=0x315e3e7d; S=0x315a2381; converted property
@property(retain) id detailedMetadataControl;	// G=0x315e3ebd; S=0x315e4259; converted property
@property(retain) id metadataProvider;	// G=0x315e3ead; S=0x315a28a9; converted property
@property(retain) id previewBrowserProvider;	// G=0x315e3ecd; S=0x315e4145; converted property
@property(retain) id textLineProvider;	// G=0x315e3e9d; S=0x315a3955; converted property
- (id)init;	// 0x315a20dd
- (void)_focusedActionChanged:(id)changed;	// 0x315e3eed
// converted property getter: - (id)actionProviders;	// 0x315e401d
- (BOOL)brEventAction:(id)action;	// 0x315a47e1
// converted property getter: - (id)coverArtPreviewControl;	// 0x315e3e8d
- (void)dealloc;	// 0x315a64cd
// converted property getter: - (int)detailControlStyle;	// 0x315e3e7d
// converted property getter: - (id)detailedMetadataControl;	// 0x315e3ebd
- (void)enableDetailsToggling;	// 0x315a3a69
- (CGRect)focusCursorFrame;	// 0x315e4915
- (void)invokeActionSelectionHandler;	// 0x315e3fc9
- (void)layoutSubcontrols;	// 0x315e4515
// converted property getter: - (id)metadataProvider;	// 0x315e3ead
// converted property getter: - (id)previewBrowserProvider;	// 0x315e3ecd
- (void)setActionFocusedIndex:(long)index;	// 0x315e3f89
// converted property setter: - (void)setActionProviders:(id)providers;	// 0x315e403d
- (void)setActionSelectionHandler:(id)handler;	// 0x315e3ffd
- (void)setActionStyle:(int)style;	// 0x315e3fa9
- (void)setAutoRefreshMetadata:(BOOL)metadata;	// 0x315e3edd
// converted property setter: - (void)setCoverArtPreviewControl:(id)control;	// 0x315e43ed
// converted property setter: - (void)setDetailControlStyle:(int)style;	// 0x315a2381
// converted property setter: - (void)setDetailedMetadataControl:(id)control;	// 0x315e4259
- (void)setExpiryText:(id)text;	// 0x315e40cd
- (void)setImageProxy:(id)proxy;	// 0x315e448d
- (void)setMediaType:(id)type;	// 0x315e44ad
// converted property setter: - (void)setMetadataProvider:(id)provider;	// 0x315a28a9
// converted property setter: - (void)setPreviewBrowserProvider:(id)provider;	// 0x315e4145
- (void)setTextLine:(id)line;	// 0x315e42e1
// converted property setter: - (void)setTextLineProvider:(id)provider;	// 0x315a3955
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315e44cd
// converted property getter: - (id)textLineProvider;	// 0x315e3e9d
@end

