/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRDividerControl, BRMetadataTitleControl, BRTextControl, BRMetadataDetailControl;

@interface BRDetailedMetadataControl : BRControl {
@private
	int _displayOption;	// 40 = 0x28
	BRMetadataDetailControl *_detailControl;	// 44 = 0x2c
	BRMetadataTitleControl *_titleControl;	// 48 = 0x30
	BRDividerControl *_topDivider;	// 52 = 0x34
	BRDividerControl *_middleDivider;	// 56 = 0x38
	BRTextControl *_summaryControl;	// 60 = 0x3c
}
@property(readonly, assign, nonatomic) BRMetadataTitleControl *titleControl;	// G=0x315e49b1; @synthesize=_titleControl
- (id)init;	// 0x315a29bd
- (void)addDetailControls:(id)controls withLabel:(id)label;	// 0x315a3649
- (void)addDetailStrings:(id)strings withLabel:(id)label;	// 0x315a3771
- (void)dealloc;	// 0x315a674d
- (void)layoutSubcontrols;	// 0x315e4b91
- (float)renderedHeightForWidth:(float)width;	// 0x315e49e1
- (void)setRating:(id)rating;	// 0x315a2eb5
- (void)setSummary:(id)summary;	// 0x315a3221
- (void)setTitle:(id)title;	// 0x315a2df9
- (void)setTitleSubtext:(id)subtext;	// 0x315a3411
- (void)setTopRightImage:(id)image;	// 0x315e49c1
// declared property getter: - (id)titleControl;	// 0x315e49b1
- (void)toggleSummaryMetadataView;	// 0x315b0b19
@end

