/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRProvider.h"

@class BRProviderGroup;

@interface BRDependentProvider : NSObject <BRProvider> {
@private
	id<BRProvider> _provider;	// 4 = 0x4
	BRProviderGroup *_providerGroup;	// 8 = 0x8
	long _threshold;	// 12 = 0xc
	BOOL _hidden;	// 16 = 0x10
}
@property(readonly, assign) long threshold;	// G=0x31666021; converted property
+ (id)providerWithDependentProvider:(id)dependentProvider providers:(id)providers threshold:(long)threshold;	// 0x316664a9
- (id)initWithDependentProvider:(id)dependentProvider providers:(id)providers threshold:(long)threshold;	// 0x31666301
- (void)_groupDataCountChanged:(id)changed;	// 0x316660e9
- (void)_providerDataSetChanged:(id)changed;	// 0x3166609d
- (void)_providerItemsModified:(id)modified;	// 0x31666031
- (id)controlFactory;	// 0x3166625d
- (id)dataAtIndex:(long)index;	// 0x316661f5
- (long)dataCount;	// 0x31666229
- (void)dealloc;	// 0x3166627d
- (id)hashForDataAtIndex:(long)index;	// 0x316661c1
- (id)providers;	// 0x316661a1
// converted property getter: - (long)threshold;	// 0x31666021
@end

