/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


@interface BRDropShadowControl : BRControl {
@private
	BRControl *_content;	// 40 = 0x28
	int _shadowStyle;	// 44 = 0x2c
	float _sizeFactor;	// 48 = 0x30
}
@property(retain) BRControl *content;	// G=0x315e6a35; S=0x31595929; converted property
@property(assign) float shadowSizeFactor;	// G=0x315e6a25; S=0x315e6a45; converted property
@property(assign) int shadowStyle;	// G=0x315e6a15; S=0x315954b9; converted property
- (id)init;	// 0x31595465
- (void)_updateImages;	// 0x315954e1
// converted property getter: - (id)content;	// 0x315e6a35
- (void)dealloc;	// 0x315a74d9
- (void)layoutSubcontrols;	// 0x315e6a79
// converted property setter: - (void)setContent:(id)content;	// 0x31595929
// converted property setter: - (void)setShadowSizeFactor:(float)factor;	// 0x315e6a45
// converted property setter: - (void)setShadowStyle:(int)style;	// 0x315954b9
// converted property getter: - (float)shadowSizeFactor;	// 0x315e6a25
// converted property getter: - (int)shadowStyle;	// 0x315e6a15
@end

