/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"


@interface BRFocusEngine : NSObject {
}
+ (BRFocusEdge)focusEdgeForEvent:(id)event elementPosition:(CGPoint)position elementBounds:(CGSize)bounds;	// 0x3163f1b1
+ (id)initalFocusForPoint:(CGPoint)point container:(id)container searchDownwardOnly:(BOOL)only;	// 0x3163eaf9
+ (id)newFocusForCandidate:(id)candidate container:(id)container event:(id)event;	// 0x3163e985
+ (id)newFocusForEdge:(BRFocusEdge)edge currentCandidate:(id)candidate container:(id)container event:(id)event;	// 0x3163ed2d
+ (BRFocusEdge)oppositeFocusEdgeForEvent:(id)event elementPosition:(CGPoint)position elementBounds:(CGSize)bounds;	// 0x3163e8ed
@end

