/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRMarqueeStack;

__attribute__((visibility("hidden")))
@interface BRFrontControl : BRControl {
@private
	BRMarqueeStack *_marqueeStack;	// 40 = 0x28
}
- (void)dealloc;	// 0x315f1745
- (void)setMarqueeStack:(id)stack;	// 0x315f16d1
@end

