/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@class NSMutableArray, NSString, NSLock, BRAsyncTaskContext, NSMutableDictionary;

@interface BRImageManager : NSObject {
@private
	unsigned long long _maxCacheSize;	// 4 = 0x4
	unsigned long long _cacheSize;	// 12 = 0xc
	BOOL _cachePurging;	// 20 = 0x14
	BOOL _purgeCacheOnLoadOrQuit;	// 21 = 0x15
	NSString *_imageCachePath;	// 24 = 0x18
	NSMutableDictionary *_images;	// 28 = 0x1c
	NSMutableDictionary *_remoteImageRequests;	// 32 = 0x20
	NSLock *_remoteImageLock;	// 36 = 0x24
	NSMutableArray *_jobQueue;	// 40 = 0x28
	NSMutableDictionary *_pendingCachedImagesToFlush;	// 44 = 0x2c
	BOOL _processJobs;	// 48 = 0x30
	BRAsyncTaskContext *_loadTaskContext;	// 52 = 0x34
	BRAsyncTaskContext *_writeTaskContext;	// 56 = 0x38
	NSMutableArray *_activeDelegates;	// 60 = 0x3c
}
+ (id)fullScreenImageResizingOptions;	// 0x3164219d
+ (id)generalPurposeManager;	// 0x31641fc5
+ (id)screenSaverManager;	// 0x31641f3d
+ (id)trickPlayManager;	// 0x31641eb5
- (id)initWithCachePath:(id)cachePath purgeOnLoadOrQuit:(BOOL)quit;	// 0x316424cd
- (void)_ATVDataImageAvailable:(id)available;	// 0x31642221
- (void)_addLoadJobToQueue:(id)queue;	// 0x316431f1
- (void)_addWriteJobToQueue:(id)queue withImageID:(id)imageID height:(int)height width:(int)width cropped:(BOOL)cropped;	// 0x31644af1
- (id)_cachedCroppedImageKeyForImageID:(id)imageID forSize:(CGSize)size;	// 0x31640fa9
- (id)_cachedCroppedImagePathForImageID:(id)imageID forSize:(CGSize)size;	// 0x31641069
- (id)_cachedOriginalImagePathForImageID:(id)imageID;	// 0x31641261
- (id)_cachedResizedImageKeyForImageID:(id)imageID forSize:(CGSize)size;	// 0x31641009
- (id)_cachedResizedImagePathForImageID:(id)imageID forSize:(CGSize)size;	// 0x31641165
- (void)_decrementCacheSize:(unsigned long long)size;	// 0x31640c85
- (id)_defaultResizingImageOptions;	// 0x316416d9
- (id)_extensionForImageID:(id)imageID;	// 0x31643705
- (id)_imageFromWriteQueue:(id)writeQueue;	// 0x31642a49
- (void)_imageLoadFailed:(id)failed;	// 0x31642c49
- (void)_imageLoadSucceeded:(id)succeeded;	// 0x3159f96d
- (void)_incrementCacheSize:(unsigned long long)size;	// 0x3159fccd
- (BOOL)_isLoadJobQueued:(id)queued;	// 0x31641365
- (void)_maintainImageCache:(id)cache;	// 0x31642d49
- (void)_performLoadJob:(id)job;	// 0x31643aed
- (void)_performWriteJob:(id)job;	// 0x3164446d
- (void)_postUnavailableImageNotification:(id)notification;	// 0x31641509
- (void)_postUpdateNotification:(id)notification;	// 0x3159fd69
- (void)_postWriteCompletedNotification:(id)notification size:(CGSize)size cropped:(BOOL)cropped;	// 0x316413f5
- (id)_queuedLoadJobWithName:(id)name;	// 0x31642b15
- (void)_removeCacheFile:(id)file;	// 0x3164156d
- (void)_removeLoadJobFromQueue:(id)queue;	// 0x316430f9
- (void)_removeRemoteImageRequestNamed:(id)named;	// 0x316415e5
- (void)_removeWriteJobFromQueue:(id)queue;	// 0x316432f1
- (void)_startLoadJob:(id)job;	// 0x3164175d
- (void)_startWriteJob:(id)job;	// 0x316417dd
- (void)_terminateNotification:(id)notification;	// 0x3164130d
- (BOOL)_updateExistingImageRecord:(id)record;	// 0x31643001
- (id)_writeIDForImageID:(id)imageID cropped:(BOOL)cropped size:(CGSize)size;	// 0x31643f0d
- (void)_writeImage:(id)image named:(id)named forSize:(CGSize)size cropped:(BOOL)cropped;	// 0x31643f7d
- (id)absolutePathForImageID:(id)imageID;	// 0x31641865
- (id)cachePath;	// 0x31640c5d
- (float)cacheSize;	// 0x31640c6d
- (void)cancelWriteForImageWithURL:(id)url imageID:(id)anId;	// 0x31641d05
- (void)dealloc;	// 0x3164209d
- (id)downSampleImage:(id)image name:(id)name scaledToSize:(CGSize)size writeToDisk:(BOOL)disk;	// 0x31643965
- (BOOL)hasRemoteImageBeenRequestedForMediaID:(id)mediaID;	// 0x31641879
- (id)imageNameFromURL:(id)url;	// 0x3159f06d
- (id)imageNamed:(id)named;	// 0x315a0119
- (id)imageNamed:(id)named croppedToSize:(CGSize)size create:(BOOL)create;	// 0x31644601
- (id)imageNamed:(id)named scaledToSize:(CGSize)size;	// 0x31641c69
- (BOOL)isImageAvailable:(id)available;	// 0x3159f095
- (BOOL)isImageAvailable:(id)available croppedToSize:(CGSize)size;	// 0x31641e1d
- (BOOL)isImageAvailable:(id)available scaledToSize:(CGSize)size;	// 0x31641e5d
- (BOOL)isImageWritten:(id)written;	// 0x31641e9d
- (id)loadImageFromURL:(id)url headerFields:(id)fields decryptionAgent:(id)agent;	// 0x316434e9
- (void)purge;	// 0x316433cd
- (void)purgeRemoteRequest;	// 0x315bcad5
- (BOOL)receiveRemoteImageURL:(id)url forID:(id)anId;	// 0x31641ad5
- (BOOL)receiveRemoteImageURL:(id)url forID:(id)anId withResizingOptions:(id)resizingOptions;	// 0x316437d9
- (void)receivedRemoteITunesImage:(id)image forID:(id)anId;	// 0x316423a1
- (void)receivedRemoteImage:(id)image forID:(id)anId;	// 0x31641981
- (void)remoteImageRequestForMediaID:(id)mediaID;	// 0x31641b19
- (void)writeCroppedImage:(id)image named:(id)named;	// 0x31643779
- (id)writeEncryptedImageFromURL:(id)url;	// 0x3159f179
- (void)writeImage:(id)image named:(id)named;	// 0x3159fd99
- (void)writeImage:(id)image named:(id)named asynchronous:(BOOL)asynchronous;	// 0x31641cad
- (id)writeImageFromImageProxy:(id)imageProxy;	// 0x31641db5
- (id)writeImageFromURL:(id)url;	// 0x315b3605
- (id)writeImageFromURL:(id)url decryptionAgent:(id)agent;	// 0x31641d91
- (id)writeImageFromURL:(id)url headerFields:(id)fields decryptionAgent:(id)agent;	// 0x31641d6d
- (id)writeImageFromURL:(id)url imageID:(id)anId headerFields:(id)fields decryptionAgent:(id)agent;	// 0x316435f9
- (void)writeScaledImage:(id)image named:(id)named withSize:(CGSize)size;	// 0x31643e81
@end

