/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRSyncProgressControl, BRImageControl, BRTextControl, BRReflectionControl;

@interface BRImageAndSyncingPreviewController : BRControl {
@private
	BRImageControl *_imageControl;	// 40 = 0x28
	BRReflectionControl *_reflectionControl;	// 44 = 0x2c
	BRSyncProgressControl *_syncProgressControl;	// 48 = 0x30
	BRTextControl *_statusTextControl;	// 52 = 0x34
	BOOL _hasProgress;	// 56 = 0x38
}
@property(readonly, retain) BRImageControl *imageControl;	// G=0x3160a335; converted property
- (id)init;	// 0x315be805
- (void)_startSyncingProgress:(id)progress;	// 0x315beaad
- (void)_stopSyncingProgress:(id)progress;	// 0x3160a345
- (void)_updateProgress:(id)progress;	// 0x3160a381
- (void)controlWasActivated;	// 0x3160a4bd
- (void)dealloc;	// 0x315beb45
// converted property getter: - (id)imageControl;	// 0x3160a335
- (void)layoutSubcontrols;	// 0x3160a529
- (void)setHasSyncProgress:(BOOL)progress;	// 0x315be961
- (void)setImage:(id)image;	// 0x315be925
- (void)setReflectionAmount:(float)amount;	// 0x315be8bd
- (void)setReflectionOffset:(float)offset;	// 0x315be8dd
- (void)setStatusMessage:(id)message;	// 0x3160a451
@end

