/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@protocol BRImageProxy <NSObject>
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;
- (id)defaultImageForImageSize:(int)imageSize;
- (id)imageForImageSize:(int)imageSize;
- (id)imageIDForImageSize:(int)imageSize;
- (id)object;
- (BOOL)supportsImageForImageSize:(int)imageSize;
@end

