/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSMutableString, NSMutableArray, BRKeyboardCandidates, NSString, BRKeyboard;

__attribute__((visibility("hidden")))
@interface BRInputMethod : NSObject {
@private
	int _textEntryStyle;	// 4 = 0x4
	NSString *_mostRecentCandidateCharacter;	// 8 = 0x8
	NSMutableString *_candidatesBuffer;	// 12 = 0xc
	NSMutableArray *_keyboards;	// 16 = 0x10
	BRKeyboard *_activeKeyboard;	// 20 = 0x14
	BRKeyboardCandidates *_candidatesKeyboard;	// 24 = 0x18
}
@property(readonly, retain) BRKeyboardCandidates *candidatesKeyboard;	// G=0x315f7e3d; converted property
@property(readonly, retain) NSMutableArray *keyboards;	// G=0x315f7e89; converted property
@property(readonly, assign) int textEntryStyle;	// G=0x315f7d61; converted property
- (id)init;	// 0x315f7fb5
- (void)_createKeyboardsForTextEntryStyle:(int)textEntryStyle;	// 0x315f7d99
- (id)candidates;	// 0x315f7d95
// converted property getter: - (id)candidatesKeyboard;	// 0x315f7e3d
- (void)dealloc;	// 0x315f7f35
- (BOOL)deleteText;	// 0x315f80fd
- (void)flushText;	// 0x315f7d9d
- (BOOL)inputText:(id)text;	// 0x315f8011
- (id)isoLanguageCode;	// 0x315f7d5d
// converted property getter: - (id)keyboards;	// 0x315f7e89
- (id)mostRecentCharacter;	// 0x315f7d85
- (id)name;	// 0x315f7d51
- (void)removeCandidatesKeyboard;	// 0x315f7e05
- (void)setActiveKeyboard:(id)keyboard;	// 0x315f7d71
- (BOOL)setTextEntryStyle:(int)style;	// 0x315f7eb5
// converted property getter: - (int)textEntryStyle;	// 0x315f7d61
- (BOOL)usesCandidateDisplayForKeyboard:(id)keyboard;	// 0x315f7d81
@end

