/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"
#import "BRITunesUtilities.h"


@interface BRITunesLibraryUtilitiesAccess : BRSingleton <BRITunesUtilities> {
@private
	id<BRITunesUtilities> _utilitiesDelegate;	// 4 = 0x4
}
+ (void)setSingleton:(id)singleton;	// 0x31645b39
+ (id)singleton;	// 0x31645b2d
- (BOOL)attemptAuthorizationForAsset:(id)asset error:(id *)error;	// 0x31645d05
- (void)dealloc;	// 0x31645da9
- (void)deauthorizeAssetIfNecessary:(id)necessary;	// 0x31645ca5
- (id)iTunesCompareAscending:(BOOL)ascending withKey:(id)key;	// 0x31645c05
- (id)iTunesCompareAscending:(BOOL)ascending withKey:(id)key fallbackSortSelector:(SEL)selector;	// 0x31645c29
- (int)iTunesCompareString:(id)string toString:(id)string2;	// 0x31645bc5
- (id)keyBagPathForPairingGUID:(unsigned long long)pairingGUID;	// 0x31645b65
- (unsigned long)randomPlaylistIndex:(unsigned long)index;	// 0x31645b85
- (id)rentalGUID;	// 0x31645b45
- (void)setITunesUtilitiesDelegate:(id)delegate;	// 0x31645d71
- (id)sortStringForString:(id)string;	// 0x31645be5
- (id)urlSuitableForPlayback:(id)playback;	// 0x31645ba5
@end

