/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRKeyboardRomanSquare.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanURL : BRKeyboardRomanSquare {
}
- (CGSize)_actionKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x3164f221
- (id)_keyboardDataFileName;	// 0x3164f209
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x3164f019
- (id)actionKeysContainer;	// 0x3164f0e1
- (id)customizedTextEntryFieldControls;	// 0x3164f1a9
- (id)name;	// 0x3164ef5d
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x3164ef69
@end

