/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRKeyboardRomanURL.h"
#import "BackRow-Structs.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanURLUppercase : BRKeyboardRomanURL {
}
- (id)_keyboardDataFileName;	// 0x3165c031
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x3165c049
- (id)name;	// 0x3165c021
@end

