/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSString;

__attribute__((visibility("hidden")))
@interface BRKeyValueObservationEntry : NSObject {
@private
	NSObject *_observer;	// 4 = 0x4
	NSObject *_observedObject;	// 8 = 0x8
	void *_context;	// 12 = 0xc
	NSString *_keyPath;	// 16 = 0x10
	id _handler;	// 20 = 0x14
}
- (id)initWithObserver:(id)observer observedObject:(id)object keyPath:(id)path handler:(id)handler;	// 0x3168a471
- (void)dealloc;	// 0x3168a549
- (BOOL)isEqualToObservedObject:(id)observedObject;	// 0x31689d09
@end

