/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRKeyboard.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanFull : BRKeyboard {
}
- (id)init;	// 0x315fe1f5
- (id)_keyboardDataFileName;	// 0x315fe249
- (id)_mainKeyRowWithKeys:(id)keys index:(int)index;	// 0x315fe065
- (float)_mainKeysContainerBaseGap:(id)gap resolutionScale:(float)scale;	// 0x315fe261
- (CGSize)_mainKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x315fe3f1
- (float)_mainKeysVerticalSpacing;	// 0x315fe049
- (CGSize)_minTextEntryControlSize:(id)size resolutionScale:(float)scale;	// 0x315fe351
- (int)_numberOfColumnsForMainKeyRowIndex:(int)mainKeyRowIndex;	// 0x315fe11d
- (int)_numberOfMainKeyRows;	// 0x315fe045
- (float)_preferredGlyphHeight:(id)height;	// 0x315fe03d
- (float)_preferredGlyphWidth:(id)width;	// 0x315fe035
- (float)_textFieldBackgroundBaseGap:(id)gap resolutionScale:(float)scale;	// 0x315fe27d
- (CGSize)_textFieldBackgroundSize:(id)size resolutionScale:(float)scale;	// 0x315fe299
- (float)_topMostUIElementGap:(id)gap resolutionScale:(float)scale;	// 0x315fe051
- (BOOL)canShowLanguageSwitchButton;	// 0x315fe02d
- (int)mapVisualIndex:(int)index toRow:(id)row;	// 0x315fe1b5
- (id)name;	// 0x315fe01d
- (BOOL)popupKeyboardShouldBeRightAlignedForKey:(id)popupKeyboard;	// 0x315fe155
- (BOOL)requiresTextFieldLabel;	// 0x315fe031
@end

