/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRKeyboardRomanSquare.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanSymbols : BRKeyboardRomanSquare {
}
- (id)_keyboardDataFileName;	// 0x315ff4d1
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x315ff4e9
- (id)name;	// 0x315ff4c1
@end

