/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRKeyboardJapaneseRomanSquare.h"
#import "BackRow-Structs.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseRomanSymbols : BRKeyboardJapaneseRomanSquare {
}
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x315fd5f1
- (id)name;	// 0x315fd485
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x315fd495
@end

