/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlHeightFactory.h"
#import "BRControlFactory.h"
#import "BRProvider.h"

@class NSMutableArray;
@protocol BRMenuListItemProvider;

__attribute__((visibility("hidden")))
@interface BRLegacyProvider : NSObject <BRControlFactory, BRControlHeightFactory, BRProvider> {
@private
	id<BRMenuListItemProvider> _source;	// 4 = 0x4
	NSMutableArray *_dividers;	// 8 = 0x8
	long _firstDividerIndex;	// 12 = 0xc
	long _lastDividerIndex;	// 16 = 0x10
}
@property(retain) id datasource;	// G=0x315bec91; S=0x315968d9; converted property
- (long)_listRowForProviderRow:(long)providerRow;	// 0x315ec245
- (long)_providerRowForListRow:(long)listRow divider:(id *)divider;	// 0x315ec309
- (void)_updateDividers;	// 0x315ec415
- (void)addDividerAtIndex:(long)index withLabel:(id)label;	// 0x315ec829
- (id)controlFactory;	// 0x315ec241
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x315ec5f9
- (id)dataAtIndex:(long)index;	// 0x315ec6c1
- (long)dataCount;	// 0x315eca29
// converted property getter: - (id)datasource;	// 0x315bec91
- (long)datasourceIndexForProviderIndex:(long)providerIndex;	// 0x315ec655
- (void)dealloc;	// 0x315ec9e1
- (id)hashForDataAtIndex:(long)index;	// 0x315ec681
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x315ec559
- (long)providerIndexForDatasourceIndex:(long)datasourceIndex;	// 0x315ec66d
- (void)removeDividerAtIndex:(long)index;	// 0x315ec73d
- (void)removeDividers;	// 0x315ec701
// converted property setter: - (void)setDatasource:(id)datasource;	// 0x315968d9
@end

