/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@class BRListControl;

@interface BRListControlMonitor : NSObject {
@private
	BRListControl *_listControl;	// 4 = 0x4
	NSRange _loadingRange;	// 8 = 0x8
	long _dataCount;	// 16 = 0x10
}
- (void)_cancelLoads;	// 0x316460bd
- (void)_listSelectionFinalized:(id)finalized;	// 0x31645df1
- (void)_loadImagesForOnScreenRows;	// 0x31645e6d
- (void)cancelCurrentLoads;	// 0x31645e05
- (void)dealloc;	// 0x31645e19
- (void)setListControl:(id)control;	// 0x31646005
@end

