/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlFactory.h"
#import "BackRow-Structs.h"

@protocol BRSelectionHandler;

@interface BRMainMenuControlFactory : NSObject <BRControlFactory> {
@private
	id<BRSelectionHandler> _selectionHandler;	// 4 = 0x4
}
@property(retain) id selectionHandler;	// G=0x31654f95; S=0x316551f9; converted property
+ (id)factory;	// 0x31655231
- (id)_posterControlForAsset:(id)asset currentControl:(id)control requestedBy:(id)by;	// 0x31654fa5
- (id)_posterControlForCollection:(id)collection currentControl:(id)control requestedBy:(id)by;	// 0x31655395
- (id)_posterControlForMediaItem:(ATVMediaItemRef)mediaItem currentControl:(id)control requestedBy:(id)by;	// 0x316555e5
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x316552b9
- (void)dealloc;	// 0x31655271
// converted property getter: - (id)selectionHandler;	// 0x31654f95
// converted property setter: - (void)setSelectionHandler:(id)handler;	// 0x316551f9
@end

