/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRTextControl;

@interface BRMainMenuShelfErrorControl : BRControl {
@private
	BRTextControl *_text;	// 40 = 0x28
	BRTextControl *_subtext;	// 44 = 0x2c
}
@property(retain) BRTextControl *subtext;	// G=0x31662c55; S=0x31662c85; converted property
@property(retain) BRTextControl *text;	// G=0x31662cd9; S=0x31662d09; converted property
- (id)init;	// 0x31662db9
- (id)_subtextAttributes;	// 0x31663095
- (id)_textAttributes;	// 0x31662e6d
- (void)dealloc;	// 0x31662d5d
- (void)layoutSubcontrols;	// 0x31662fb9
// converted property setter: - (void)setSubtext:(id)subtext;	// 0x31662c85
// converted property setter: - (void)setText:(id)text;	// 0x31662d09
// converted property getter: - (id)subtext;	// 0x31662c55
// converted property getter: - (id)text;	// 0x31662cd9
@end

