/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMarqueeScrollingDelegate.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface BRMarqueeStack : NSObject <BRMarqueeScrollingDelegate> {
@private
	NSMutableArray *_controlStack;	// 4 = 0x4
	unsigned _currentScrollingControlIndex;	// 8 = 0x8
	BOOL _isFirstRun;	// 12 = 0xc
	BOOL _shouldStopAllScrolling;	// 13 = 0xd
	BOOL _shouldAnimateOnce;	// 14 = 0xe
	BOOL _allowsSimultaneousScrollingControls;	// 15 = 0xf
	unsigned _maxSimultaneousScrollingControls;	// 16 = 0x10
	int _transitionDirection;	// 20 = 0x14
}
@property(assign) BOOL allowsSimultaneousScrollingControls;	// G=0x3166a445; S=0x3166a435; converted property
@property(assign) unsigned maxSimultaneousScrollingControls;	// G=0x3166a465; S=0x3166a455; converted property
@property(assign) int transitionDirection;	// G=0x3166a405; S=0x3166a3f5; converted property
- (id)init;	// 0x3166a655
- (int)_indexOfFirstControlInNeedOfAnimation;	// 0x3166a475
- (int)_indexOfNextControlInNeedOfScrollingFromIndex:(unsigned)index;	// 0x3166a839
- (void)addControlToStack:(id)stack;	// 0x3166a611
- (void)addControlToStack:(id)stack atIndex:(unsigned)index;	// 0x3166a7bd
// converted property getter: - (BOOL)allowsSimultaneousScrollingControls;	// 0x3166a445
- (void)controlDidFinishingScrolling:(id)control;	// 0x3166a48d
- (void)dealloc;	// 0x3166a71d
// converted property getter: - (unsigned)maxSimultaneousScrollingControls;	// 0x3166a465
- (void)removeControlFromStack:(id)stack;	// 0x3166a5dd
// converted property setter: - (void)setAllowsSimultaneousScrollingControls:(BOOL)controls;	// 0x3166a435
// converted property setter: - (void)setMaxSimultaneousScrollingControls:(unsigned)controls;	// 0x3166a455
- (void)setShouldAnimateOnce:(BOOL)animateOnce;	// 0x3166a425
- (void)setShouldStopAllScrolling:(BOOL)stopAllScrolling;	// 0x3166a415
// converted property setter: - (void)setTransitionDirection:(int)direction;	// 0x3166a3f5
- (BOOL)shouldControlWaitToScroll:(id)scroll;	// 0x3166a8e9
- (id)stack;	// 0x3166a629
// converted property getter: - (int)transitionDirection;	// 0x3166a405
@end

