/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRMediaAccessUtilities : NSObject {
}
+ (id)allowedMusicMediaTypesPredicate;	// 0x3162fd1d
+ (id)highestResolutionAssetInCollection:(id)collection;	// 0x3162faed
+ (id)oldestUnwatchedAssetInArray:(id)array;	// 0x3162fbb1
+ (id)oldestUnwatchedAssetInCollection:(id)collection;	// 0x3162fcf1
+ (id)uniqueAlbumsForTracks:(id)tracks;	// 0x3162fdbd
@end

