/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControl.h"
#import "BackRow-Structs.h"

@class NSMutableArray, NSString, NSTimer, BRProviderGroup, NSDictionary;

@interface BRMediaShelfControl : BRControl {
@private
	BRProviderGroup *_group;	// 40 = 0x28
	long _minNumberShelfItems;	// 44 = 0x2c
	NSDictionary *_controlActions;	// 48 = 0x30
	NSDictionary *_titleActions;	// 52 = 0x34
	NSDictionary *_titleAttributes;	// 56 = 0x38
	float _coverflowMargin;	// 60 = 0x3c
	long _columnCount;	// 64 = 0x40
	BOOL _centered;	// 68 = 0x44
	BOOL _scrollable;	// 69 = 0x45
	NSString *_lastFocusedHash;	// 72 = 0x48
	BOOL _restoresFocus;	// 76 = 0x4c
	BOOL _showsDividers;	// 77 = 0x4d
	BOOL _showsProviderNames;	// 78 = 0x4e
	float _horizontalGap;	// 80 = 0x50
	NSRange _flatRange;	// 84 = 0x54
	CATransform3D _leftTransform;	// 92 = 0x5c
	CATransform3D _rightTransform;	// 156 = 0x9c
	NSMutableArray *_cells;	// 220 = 0xdc
	NSMutableArray *_titles;	// 224 = 0xe0
	BOOL _handlingProviderChange;	// 228 = 0xe4
	NSTimer *_scrollTimer;	// 232 = 0xe8
	BOOL _scrolling;	// 236 = 0xec
	int _collapsedState;	// 240 = 0xf0
	BOOL _featured;	// 244 = 0xf4
	BOOL _ordered;	// 245 = 0xf5
	BOOL _showAllTitles;	// 246 = 0xf6
	BOOL _showTitleAndSubtitle;	// 247 = 0xf7
	BOOL _needToReloadDataOnActivate;	// 248 = 0xf8
}
@property(assign) BOOL centered;	// G=0x315c64f1; S=0x3159e625; converted property
@property(assign) int collapsedState;	// G=0x315c6531; S=0x315c75e1; converted property
@property(assign) long columnCount;	// G=0x315c64d1; S=0x3159e135; converted property
@property(assign) float coverflowMargin;	// G=0x315c6511; S=0x3159df9d; converted property
@property(assign) BOOL featured;	// G=0x3159e38d; S=0x3159e00d; converted property
@property(assign) long focusedIndex;	// G=0x315c76a1; S=0x315c76d5; converted property
@property(assign) float horizontalGap;	// G=0x315c6501; S=0x3159df69; converted property
@property(assign) long minNumberOfShelfItems;	// G=0x315c64c1; S=0x315c64b1; converted property
@property(assign) BOOL ordered;	// G=0x3159e35d; S=0x3159e089; converted property
@property(retain) id providers;	// G=0x315c77fd; S=0x315c781d; converted property
@property(assign) BOOL restoresFocus;	// G=0x315c6521; S=0x315c7615; converted property
@property(assign) BOOL scrollable;	// G=0x315c64e1; S=0x3159de2d; converted property
@property(assign) BOOL showAllTitles;	// G=0x3159e36d; S=0x3159e0b1; converted property
@property(assign) BOOL showTitleAndSubtitle;	// G=0x3159e37d; S=0x3159e0d9; converted property
@property(assign) BOOL showsDividers;	// G=0x315c6541; S=0x315c6bd1; converted property
@property(assign) BOOL showsProviderNames;	// G=0x315c6551; S=0x315c6a11; converted property
- (id)init;	// 0x3159dca1
- (void)_adjustShelfSubsetProviderLimits;	// 0x315c6d19
- (id)_controlActions;	// 0x315c6fd9
- (id)_currentCellAtIndex:(int)index;	// 0x315c73a9
- (long)_dividedProviderIndexForProvider:(id)provider;	// 0x315c67d9
- (NSRange)_dividedRangeForRange:(NSRange)range andDirection:(int)direction;	// 0x315c83ed
- (unsigned)_dividerCountInRange:(NSRange)range;	// 0x315c8521
- (unsigned)_firstScrollableIndex;	// 0x315a2089
- (void)_focusChanged:(id)changed;	// 0x315c7395
- (long)_groupCountIgnoringDividers;	// 0x315c6999
- (void)_hideFirstDividerInDividedProviders:(id)dividedProviders;	// 0x315c6891
- (BOOL)_isDividerAtIndex:(long)index;	// 0x315c6949
- (unsigned)_lastScrollableIndex;	// 0x315a200d
- (void)_layoutShelfContents;	// 0x315c8561
- (BOOL)_leftButtonEvent;	// 0x315a2045
- (void)_loadControlAtIndex:(int)index;	// 0x3159e1ed
- (id)_newControlAtIndex:(int)index;	// 0x315c73ed
- (unsigned)_nextFocusableIndexInDirection:(int)direction;	// 0x315c72dd
- (void)_providerControlCountChanged:(id)changed;	// 0x315c6f2d
- (void)_providerNameChanged:(id)changed;	// 0x315c6561
- (void)_purgeControlAtIndex:(int)index;	// 0x315a917d
- (void)_purgeControls;	// 0x315c7501
- (void)_refillShelf;	// 0x315c80c9
- (void)_reloadTitles;	// 0x315c66b1
- (void)_restoreLastSelection;	// 0x315c7bb1
- (BOOL)_rightButtonEvent;	// 0x315a1fc9
- (void)_saveCurrentSelection;	// 0x315c71ad
- (BOOL)_scrollInDirection:(int)direction;	// 0x315a8e51
- (BOOL)_scrollIndexToVisible:(long)visible;	// 0x315c83b9
- (BOOL)_scrollLeft;	// 0x315c72c1
- (BOOL)_scrollRight;	// 0x315a8e39
- (void)_setDimness:(float)dimness forLayer:(id)layer;	// 0x315c7e59
- (id)_titleActions;	// 0x315c65a1
- (id)_titleAttributes;	// 0x315c7f7d
- (void)_updateFocusAcceptanceAtIndex:(int)index;	// 0x3159e2c1
- (void)_updateSublayerTransform;	// 0x3159de69
- (int)_visibleFlowCellCount;	// 0x3159e1e9
- (NSRange)_visibleRange;	// 0x3159e175
- (BOOL)brEventAction:(id)action;	// 0x315a17c5
// converted property getter: - (BOOL)centered;	// 0x315c64f1
// converted property getter: - (int)collapsedState;	// 0x315c6531
// converted property getter: - (long)columnCount;	// 0x315c64d1
- (void)controlWasActivated;	// 0x315c7b15
- (void)controlWasFocused;	// 0x315c7b5d
// converted property getter: - (float)coverflowMargin;	// 0x315c6511
- (void)dealloc;	// 0x3159f84d
// converted property getter: - (BOOL)featured;	// 0x3159e38d
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x315c7549
// converted property getter: - (long)focusedIndex;	// 0x315c76a1
// converted property getter: - (float)horizontalGap;	// 0x315c6501
- (id)initialFocus;	// 0x315c7c81
- (void)layoutSubcontrols;	// 0x315c7d81
// converted property getter: - (long)minNumberOfShelfItems;	// 0x315c64c1
// converted property getter: - (BOOL)ordered;	// 0x3159e35d
- (long)providerDataCount;	// 0x315c77d9
// converted property getter: - (id)providers;	// 0x315c77fd
- (void)reloadData;	// 0x3159e035
// converted property getter: - (BOOL)restoresFocus;	// 0x315c6521
// converted property getter: - (BOOL)scrollable;	// 0x315c64e1
- (id)selectedControl;	// 0x315c7601
// converted property setter: - (void)setCentered:(BOOL)centered;	// 0x3159e625
// converted property setter: - (void)setCollapsedState:(int)state;	// 0x315c75e1
// converted property setter: - (void)setColumnCount:(long)count;	// 0x3159e135
// converted property setter: - (void)setCoverflowMargin:(float)margin;	// 0x3159df9d
// converted property setter: - (void)setFeatured:(BOOL)featured;	// 0x3159e00d
// converted property setter: - (void)setFocusedIndex:(long)index;	// 0x315c76d5
// converted property setter: - (void)setHorizontalGap:(float)gap;	// 0x3159df69
// converted property setter: - (void)setMinNumberOfShelfItems:(long)shelfItems;	// 0x315c64b1
- (void)setName:(id)name forProvider:(id)provider;	// 0x315c6a39
// converted property setter: - (void)setOrdered:(BOOL)ordered;	// 0x3159e089
- (void)setProvider:(id)provider;	// 0x3159e101
// converted property setter: - (void)setProviders:(id)providers;	// 0x315c781d
// converted property setter: - (void)setRestoresFocus:(BOOL)focus;	// 0x315c7615
// converted property setter: - (void)setScrollable:(BOOL)scrollable;	// 0x3159de2d
// converted property setter: - (void)setShowAllTitles:(BOOL)titles;	// 0x3159e0b1
// converted property setter: - (void)setShowTitleAndSubtitle:(BOOL)subtitle;	// 0x3159e0d9
// converted property setter: - (void)setShowsDividers:(BOOL)dividers;	// 0x315c6bd1
// converted property setter: - (void)setShowsProviderNames:(BOOL)names;	// 0x315c6a11
// converted property getter: - (BOOL)showAllTitles;	// 0x3159e36d
// converted property getter: - (BOOL)showTitleAndSubtitle;	// 0x3159e37d
// converted property getter: - (BOOL)showsDividers;	// 0x315c6541
// converted property getter: - (BOOL)showsProviderNames;	// 0x315c6551
- (void)visibleScrollRectChanged;	// 0x315c7149
@end

