/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"
#import "BRAXMetadataChangeProtocol.h"

@class NSTimer, BRCoverArtImageLayer, BRMetadataLongDescriptionControl, BRReflectionControl;
@protocol BRMetadataProvider;

@interface BRMetadataLongDescriptionPreviewControl : BRControl <BRAXMetadataChangeProtocol> {
@private
	id _asset;	// 40 = 0x28
	id<BRMetadataProvider> _metadataProvider;	// 44 = 0x2c
	BRControl *_coverArtWrapper;	// 48 = 0x30
	BRCoverArtImageLayer *_coverArtLayer;	// 52 = 0x34
	BRReflectionControl *_reflectionLayer;	// 56 = 0x38
	BRMetadataLongDescriptionControl *_metadataLayer;	// 60 = 0x3c
	NSTimer *_timer;	// 64 = 0x40
	BOOL _showsMetadataImmediately;	// 68 = 0x44
	BOOL _showingMetadata;	// 69 = 0x45
}
@property(retain) id asset;	// G=0x3168045d; S=0x31680e49; converted property
@property(assign) BOOL deletterboxAssetArtwork;	// G=0x3168074d; S=0x31680771; converted property
@property(assign) BOOL showsDefaultCoverArt;	// G=0x31680705; S=0x31680729; converted property
@property(assign) BOOL showsMetadataImmediately;	// G=0x3168046d; S=0x31680795; converted property
- (id)init;	// 0x3168093d
- (void)_coverArtChanged:(id)changed;	// 0x31680555
- (void)_downloadStateChanged:(id)changed;	// 0x316804f9
- (CGRect)_frameForArt:(id)art inBounds:(CGSize)bounds;	// 0x3168115d
- (CGRect)_metadataFrameForBounds:(CGSize)bounds;	// 0x3168048d
- (void)_metadataTimerFired:(id)fired;	// 0x31680531
- (float)_reflectionAmountForArtFrame:(CGRect)artFrame bottomCutoff:(float)cutoff;	// 0x316804a5
- (void)_showMetadataAfterDelay;	// 0x316805a9
- (void)_updateMetadataLayer;	// 0x31681015
// converted property getter: - (id)asset;	// 0x3168045d
- (id)axMetadataText;	// 0x31680631
- (void)controlWasActivated;	// 0x316806c9
- (void)controlWasDeactivated;	// 0x3168067d
- (void)dealloc;	// 0x31680871
// converted property getter: - (BOOL)deletterboxAssetArtwork;	// 0x3168074d
- (void)layoutSubcontrols;	// 0x31680bd1
- (id)metadataControl;	// 0x3168047d
// converted property setter: - (void)setAsset:(id)asset;	// 0x31680e49
// converted property setter: - (void)setDeletterboxAssetArtwork:(BOOL)artwork;	// 0x31680771
- (void)setImageProxy:(id)proxy;	// 0x3168081d
- (void)setMetadataProvider:(id)provider;	// 0x316807bd
// converted property setter: - (void)setShowsDefaultCoverArt:(BOOL)art;	// 0x31680729
// converted property setter: - (void)setShowsMetadataImmediately:(BOOL)immediately;	// 0x31680795
// converted property getter: - (BOOL)showsDefaultCoverArt;	// 0x31680705
// converted property getter: - (BOOL)showsMetadataImmediately;	// 0x3168046d
@end

