/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class BRMediaPlayerController;

__attribute__((visibility("hidden")))
@interface BRMediaPlayerControllerTransitionDelegate : NSObject {
@private
	BRMediaPlayerController *_controller;	// 4 = 0x4
}
- (id)initWithController:(id)controller;	// 0x315c19cd
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x315c5e41
- (void)setController:(id)controller;	// 0x315c186d
@end

