/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRAsyncImageControl, NSMutableSet, BRMarqueeTextControl, BRWaitSpinnerControl, NSNumber, NSAttributedString;
@protocol BRDisplayInfoLoader;

@interface BRMenuItem : BRControl {
@private
	CGColorRef _bgColor;	// 40 = 0x28
	NSAttributedString *_text;	// 44 = 0x2c
	NSAttributedString *_detailedText;	// 48 = 0x30
	NSAttributedString *_rightJustifiedText;	// 52 = 0x34
	BRMarqueeTextControl *_scrollingTextControl;	// 56 = 0x38
	BRAsyncImageControl *_imageControl;	// 60 = 0x3c
	BRWaitSpinnerControl *_spinner;	// 64 = 0x40
	id<BRDisplayInfoLoader> _displayInfoLoader;	// 68 = 0x44
	NSMutableSet *_accessories;	// 72 = 0x48
	BOOL _dimmed;	// 76 = 0x4c
	BOOL _disableAccessoryHighlighting;	// 77 = 0x4d
	BOOL _forceOrdinalLayout;	// 78 = 0x4e
	BOOL _dotsTrailImage;	// 79 = 0x4f
	BOOL _forceBlueDotLayout;	// 80 = 0x50
	BOOL _forceMenuArrowLayout;	// 81 = 0x51
	BOOL _usingDefaultTextAttributes;	// 82 = 0x52
	BOOL _iconsTrailText;	// 83 = 0x53
	float _forcedHeight;	// 84 = 0x54
	float _forcedContentHeight;	// 88 = 0x58
	NSNumber *_ordinal;	// 92 = 0x5c
	int _largestOrdinal;	// 96 = 0x60
	float _imageInset;	// 100 = 0x64
	float _imageHeight;	// 104 = 0x68
	float _textPadding;	// 108 = 0x6c
	float _leftMargin;	// 112 = 0x70
	float _rightMargin;	// 116 = 0x74
	float _imageAspectRatio;	// 120 = 0x78
	BOOL _colorSet;	// 124 = 0x7c
}
@property(retain) NSAttributedString *detailedText;	// G=0x316685bd; S=0x316686e1; converted property
@property(assign) BOOL dimmed;	// G=0x316671f5; S=0x31668f11; converted property
@property(assign) BOOL disableAccessoryHighlighting;	// G=0x31667205; S=0x3166804d; converted property
@property(retain) id displayInfoLoader;	// G=0x316671e5; S=0x316681a9; converted property
@property(assign) BOOL dotsTrailImage;	// G=0x31667265; S=0x31667e65; converted property
@property(assign) BOOL forceBlueDotLayout;	// G=0x31667255; S=0x31667e8d; converted property
@property(assign) BOOL forceMenuArrowLayout;	// G=0x31667235; S=0x31667f55; converted property
@property(readonly, assign) BOOL forceOrdinalLayout;	// G=0x31667245; converted property
@property(assign) float forcedContentHeight;	// G=0x31667225; S=0x31667f75; converted property
@property(assign) float forcedHeight;	// G=0x31667215; S=0x31667f99; converted property
@property(assign) BOOL iconsTrailText;	// G=0x31667275; S=0x31667e3d; converted property
@property(retain) id image;	// G=0x31668371; S=0x31668441; converted property
@property(assign) float imageAspectRatio;	// G=0x316671d5; S=0x31668251; converted property
@property(assign) float imageHeight;	// G=0x316672b5; S=0x31667d6d; converted property
@property(assign) float imageInset;	// G=0x31667295; S=0x31667dd5; converted property
@property(retain) id imageProxy;	// G=0x31668285; S=0x316682a5; converted property
@property(assign) float leftMargin;	// G=0x31667285; S=0x31667e09; converted property
@property(assign) CGColorRef menuItemBackgroundColor;	// G=0x31668819; S=0x31668eed; converted property
@property(retain) NSAttributedString *rightJustifiedText;	// G=0x31668509; S=0x316685a5; converted property
@property(assign) float rightMargin;	// G=0x316672c5; S=0x31667d39; converted property
@property(retain) NSAttributedString *text;	// G=0x316686f9; S=0x31668801; converted property
@property(assign) float textPadding;	// G=0x316672a5; S=0x31667da1; converted property
- (id)init;	// 0x31668b95
- (id)_accessoryOfType:(int)type;	// 0x31667d21
- (id)_accessoryOfType:(int)type offset:(float *)offset;	// 0x31667a29
- (id)_detailedTextAttributes;	// 0x31668e7d
- (void)_drawDimmedText:(id)text inRect:(CGRect)rect withDim:(float)dim context:(CGContextRef)context;	// 0x3166923d
- (id)_firstAccessoryFromAccessories:(id)accessories offset:(float *)offset;	// 0x316679b5
- (id)_imageWithName:(id)name;	// 0x316691e5
- (id)_largeLeftImage;	// 0x31667785
- (float)_largestOrdinalWidth;	// 0x31668d29
- (id)_ordinalImage;	// 0x316676d1
- (id)_ordinalString;	// 0x316672d5
- (id)_ordinalTypes;	// 0x316676fd
- (id)_rightJustifiedIconWithRightOffset:(float *)rightOffset;	// 0x31667881
- (id)_rightTextAttributes;	// 0x31669199
- (void)_setSpinnerEnabled:(BOOL)enabled;	// 0x316673f5
- (CGSize)_sizeThatFits:(CGSize)fits;	// 0x3166930d
- (void)_switchToScrollingTextForTextFrame:(CGRect)textFrame;	// 0x31667491
- (id)_textAttributes;	// 0x31668e39
- (void)_updateColorAndContentHeight;	// 0x316690b5
- (id)_upperRightImageTypes;	// 0x31667615
- (id)_upperRightImages;	// 0x3166756d
- (void)addAccessoryOfType:(int)type;	// 0x316680fd
- (void)cancelLoadDisplayInfo;	// 0x316688c5
- (id)centeredDetailedTextAttributes;	// 0x31668ec9
- (id)centeredTextAttributes;	// 0x3166883d
- (void)controlWasActivated;	// 0x316689ed
- (void)controlWasDeactivated;	// 0x3166898d
- (void)controlWasFocused;	// 0x31668add
- (void)controlWasUnfocused;	// 0x31668a85
- (void)dealloc;	// 0x31668c41
- (id)description;	// 0x31668b35
// converted property getter: - (id)detailedText;	// 0x316685bd
// converted property getter: - (BOOL)dimmed;	// 0x316671f5
// converted property getter: - (BOOL)disableAccessoryHighlighting;	// 0x31667205
// converted property getter: - (id)displayInfoLoader;	// 0x316671e5
// converted property getter: - (BOOL)dotsTrailImage;	// 0x31667265
- (void)drawInContext:(CGContextRef)context;	// 0x31669399
- (CGRect)focusCursorFrame;	// 0x3166901d
// converted property getter: - (BOOL)forceBlueDotLayout;	// 0x31667255
// converted property getter: - (BOOL)forceMenuArrowLayout;	// 0x31667235
// converted property getter: - (BOOL)forceOrdinalLayout;	// 0x31667245
// converted property getter: - (float)forcedContentHeight;	// 0x31667225
// converted property getter: - (float)forcedHeight;	// 0x31667215
- (BOOL)hasAccessoryOfType:(int)type;	// 0x3166806d
// converted property getter: - (BOOL)iconsTrailText;	// 0x31667275
// converted property getter: - (id)image;	// 0x31668371
// converted property getter: - (float)imageAspectRatio;	// 0x316671d5
// converted property getter: - (float)imageHeight;	// 0x316672b5
// converted property getter: - (float)imageInset;	// 0x31667295
// converted property getter: - (id)imageProxy;	// 0x31668285
// converted property getter: - (float)leftMargin;	// 0x31667285
- (void)loadDisplayInfo;	// 0x31668901
// converted property getter: - (CGColorRef)menuItemBackgroundColor;	// 0x31668819
- (void)removeAccessoryOfType:(int)type;	// 0x31668089
// converted property getter: - (id)rightJustifiedText;	// 0x31668509
// converted property getter: - (float)rightMargin;	// 0x316672c5
- (void)scrollingCompleted;	// 0x3166893d
- (void)setDefaultImage:(id)image;	// 0x31668391
// converted property setter: - (void)setDetailedText:(id)text;	// 0x316686e1
- (void)setDetailedText:(id)text withAttributes:(id)attributes;	// 0x316685dd
// converted property setter: - (void)setDimmed:(BOOL)dimmed;	// 0x31668f11
// converted property setter: - (void)setDisableAccessoryHighlighting:(BOOL)highlighting;	// 0x3166804d
// converted property setter: - (void)setDisplayInfoLoader:(id)loader;	// 0x316681a9
// converted property setter: - (void)setDotsTrailImage:(BOOL)image;	// 0x31667e65
// converted property setter: - (void)setForceBlueDotLayout:(BOOL)layout;	// 0x31667e8d
// converted property setter: - (void)setForceMenuArrowLayout:(BOOL)layout;	// 0x31667f55
- (void)setForceOrdinalLayout:(BOOL)layout ordinal:(id)ordinal largestOrdinal:(id)ordinal3;	// 0x31667eb5
// converted property setter: - (void)setForcedContentHeight:(float)height;	// 0x31667f75
// converted property setter: - (void)setForcedHeight:(float)height;	// 0x31667f99
// converted property setter: - (void)setIconsTrailText:(BOOL)text;	// 0x31667e3d
// converted property setter: - (void)setImage:(id)image;	// 0x31668441
// converted property setter: - (void)setImageAspectRatio:(float)ratio;	// 0x31668251
// converted property setter: - (void)setImageHeight:(float)height;	// 0x31667d6d
// converted property setter: - (void)setImageInset:(float)inset;	// 0x31667dd5
// converted property setter: - (void)setImageProxy:(id)proxy;	// 0x316682a5
// converted property setter: - (void)setLeftMargin:(float)margin;	// 0x31667e09
// converted property setter: - (void)setMenuItemBackgroundColor:(CGColorRef)color;	// 0x31668eed
// converted property setter: - (void)setRightJustifiedText:(id)text;	// 0x316685a5
- (void)setRightJustifiedText:(id)text withAttributes:(id)attributes;	// 0x31668529
// converted property setter: - (void)setRightMargin:(float)margin;	// 0x31667d39
// converted property setter: - (void)setText:(id)text;	// 0x31668801
- (void)setText:(id)text withAttributes:(id)attributes;	// 0x31668719
// converted property setter: - (void)setTextPadding:(float)padding;	// 0x31667da1
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x31668de9
// converted property getter: - (id)text;	// 0x316686f9
// converted property getter: - (float)textPadding;	// 0x316672a5
@end

