/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImageControl, BRTextControl;

@interface BRMetadataTitleControl : BRControl {
@private
	BRTextControl *_title;	// 40 = 0x28
	BRTextControl *_titleSubtext;	// 44 = 0x2c
	BRImageControl *_rating;	// 48 = 0x30
	BRImageControl *_rightImage;	// 52 = 0x34
	BOOL _ratingSnapsToTitle;	// 56 = 0x38
	float _rightImageHeight;	// 60 = 0x3c
}
- (id)init;	// 0x315a2b45
- (void)dealloc;	// 0x315a68f1
- (void)layoutSubcontrols;	// 0x315efb81
- (CGSize)renderedSize;	// 0x315a3a99
- (void)setRating:(id)rating;	// 0x315a2ed5
- (void)setRatingSnapsToTitle:(BOOL)title;	// 0x315efb59
- (void)setRightImage:(id)image;	// 0x315efb25
- (void)setRightImageFixedHeight:(float)height;	// 0x315efaf1
- (void)setTitle:(id)title;	// 0x315a2e19
- (void)setTitleSubtext:(id)subtext;	// 0x315a3431
@end

