/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRResponder.h"

@class NSTimer, BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface BRMediaPlayerEventHandler : NSObject <BRResponder> {
@private
	BRMediaPlayer *_player;	// 4 = 0x4
	BOOL _waitingForUp;	// 8 = 0x8
	BOOL _inChapterSkipMode;	// 9 = 0x9
	double _virtualChapterMark;	// 12 = 0xc
	NSTimer *_chapterSelectionModeTimer;	// 20 = 0x14
	NSTimer *_musicSkipModeTimer;	// 24 = 0x18
	int _preShuttleState;	// 28 = 0x1c
	int _shuttleSpeed;	// 32 = 0x20
	int _shuttleDirection;	// 36 = 0x24
	BOOL _inShuttleMode;	// 40 = 0x28
	BOOL _readyToInitiateShuttle;	// 41 = 0x29
	NSTimer *_shuttleChapterSkipTimer;	// 44 = 0x2c
	CGPoint _initialTouchPosition;	// 48 = 0x30
	CGPoint _lastTouchPosition;	// 56 = 0x38
	CGPoint _lastTouchDelta;	// 64 = 0x40
	double _shuttleFinishedTime;	// 72 = 0x48
}
+ (id)handlerWithPlayer:(id)player;	// 0x31638b35
- (id)initWithPlayer:(id)player;	// 0x31638b79
- (BOOL)_changePlayerStateTo:(int)to;	// 0x31636fdd
- (BOOL)_changePlayerStateTo:(int)to onButtonDown:(id)down retrigger:(BOOL)retrigger;	// 0x31636f61
- (BOOL)_chapterSkipSupported;	// 0x31636aa5
- (BOOL)_chapteringSupported;	// 0x31636b2d
- (BOOL)_defaultEventHandler:(id)handler;	// 0x316387c5
- (void)_endChapterSelectionMode:(id)mode;	// 0x31637671
- (BOOL)_handleEventWhileChapterSelecting:(id)selecting;	// 0x31637ecd
- (BOOL)_handleEventWhileFF1:(id)a1;	// 0x31637d0d
- (BOOL)_handleEventWhileFF2:(id)a2;	// 0x31637c71
- (BOOL)_handleEventWhileFF3:(id)a3;	// 0x31637bd5
- (BOOL)_handleEventWhileLoading:(id)loading;	// 0x316381d1
- (BOOL)_handleEventWhilePaused:(id)paused;	// 0x316382ed
- (BOOL)_handleEventWhilePlaying:(id)playing;	// 0x31637d95
- (BOOL)_handleEventWhileREW1:(id)a1;	// 0x31637b4d
- (BOOL)_handleEventWhileREW2:(id)a2;	// 0x31637ab1
- (BOOL)_handleEventWhileREW3:(id)a3;	// 0x31637a15
- (BOOL)_handleEventWhileSlowForward1:(id)a1;	// 0x3163798d
- (BOOL)_handleEventWhileSlowForward2:(id)a2;	// 0x316378f1
- (BOOL)_handleEventWhileSlowForward3:(id)a3;	// 0x31637855
- (BOOL)_handleEventWhileSlowRewind1:(id)a1;	// 0x316377cd
- (BOOL)_handleEventWhileSlowRewind2:(id)a2;	// 0x31637731
- (BOOL)_handleEventWhileSlowRewind3:(id)a3;	// 0x31637695
- (BOOL)_handleForwardEvent:(id)event;	// 0x31638ddd
- (BOOL)_handleLeftEvent:(id)event;	// 0x3163857d
- (BOOL)_handleLeftEventWhileChapterSkipping:(id)skipping;	// 0x316383cd
- (BOOL)_handleRewindEvent:(id)event;	// 0x31638c45
- (BOOL)_handleRightEvent:(id)event;	// 0x316386a1
- (BOOL)_handleRightEventWhileChapterSkipping:(id)skipping;	// 0x316384a5
- (BOOL)_handleTouchEvent:(id)event;	// 0x31639145
- (BOOL)_handleTouchMultiSwipeLeftEvent:(id)event;	// 0x3163681d
- (BOOL)_handleTouchMultiSwipeRightEvent:(id)event;	// 0x31636879
- (BOOL)_handleTouchSwipeEvent:(id)event;	// 0x31636995
- (BOOL)_handleTouchSwipeLeftEvent:(id)event;	// 0x316368d5
- (BOOL)_handleTouchSwipeRightEvent:(id)event;	// 0x31636935
- (BOOL)_handleTrickPlayWhileLoading:(id)loading;	// 0x31638181
- (void)_initiateShuttleAction;	// 0x31636659
- (BOOL)_isFavoriteRadioStation;	// 0x31636a0d
- (void)_performCancelMusicSkip;	// 0x31636bb1
- (void)_performMusicFastForward;	// 0x31636dd5
- (void)_performMusicRewind;	// 0x31636db9
- (void)_performMusicSkipToTime:(id)time;	// 0x31636bd9
- (void)_performMusicSkipWithSkipAdjust:(int)skipAdjust;	// 0x31636d1d
- (BOOL)_performNextThingButtonAction:(id)action;	// 0x316374d9
- (BOOL)_performPreviousThingButtonAction:(id)action;	// 0x3163755d
- (void)_performShuttle:(long)shuttle;	// 0x31636ded
- (void)_performShuttleExit;	// 0x31636eb5
- (BOOL)_performSkipBackwardAction:(id)action;	// 0x3163733d
- (BOOL)_performSkipForwardAction:(id)action;	// 0x31637421
- (BOOL)_performVolumeDownAction:(id)action;	// 0x31637055
- (BOOL)_performVolumeUpAction:(id)action;	// 0x316371c9
- (void)_playSoundForState:(int)state;	// 0x31636f11
- (void)_playerAssetChanged:(id)changed;	// 0x3163895d
- (void)_playerStateChanged:(id)changed;	// 0x31638929
- (void)_setInChapterSkipMode:(BOOL)chapterSkipMode;	// 0x31638f71
- (void)_setShuttleSpeed:(int)speed;	// 0x31636791
- (void)_touchRepeatCancel;	// 0x31636631
- (void)_touchRepeatEvent;	// 0x316365fd
- (BOOL)brEventAction:(id)action;	// 0x316389c1
- (BOOL)brKeyEvent:(id)event;	// 0x316365e9
- (void)dealloc;	// 0x31638ac5
- (BOOL)showingChapterMarks;	// 0x316365ed
@end

