/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"


@interface BRMediaUtilities : NSObject {
}
+ (id)defaultImageForMediaCollection:(ATVMediaCollectionRef)mediaCollection imageSize:(int)size;	// 0x31681ca5
+ (id)defaultImageForMediaItem:(ATVMediaItemRef)mediaItem imageSize:(int)size;	// 0x31681889
+ (BOOL)iTunesServerID:(id)anId isEqualToITunesServerID:(id)itunesServerID;	// 0x31681281
+ (BOOL)isAirPlayAsset:(id)asset;	// 0x31681481
+ (BOOL)isHomeShareRental:(id)rental;	// 0x31681385
+ (BOOL)isiTunesAsset:(id)asset;	// 0x316814cd
+ (BOOL)isiTunesMediaItem:(ATVMediaItemRef)item;	// 0x31681cfd
+ (id)mediaAssetsFromMediaItems:(id)mediaItems;	// 0x3168151d
+ (id)mediaTypeForATVMediaType:(ATVMediaTypeRef)atvmediaType;	// 0x316815c1
+ (id)mediaTypeForMediaCollection:(ATVMediaCollectionRef)mediaCollection;	// 0x31681c69
+ (id)mediaTypeForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x316819a9
+ (double)playedThresholdForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x316819e5
+ (double)playedThresholdForMediaType:(ATVMediaTypeRef)mediaType duration:(double)duration;	// 0x316811e9
+ (float)soundCheckValueForMediaAsset:(id)mediaAsset;	// 0x316818bd
+ (float)soundCheckValueForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x31681ba9
+ (int)watchedStateForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x31681a81
+ (int)watchedStateForMediaType:(ATVMediaTypeRef)mediaType duration:(double)duration bookmarkInMS:(long)ms hasBeenPlayed:(BOOL)played playCount:(long)count;	// 0x31681925
@end

