/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BROptionDialog.h"

@class BRMediaHost;

__attribute__((visibility("hidden")))
@interface BRMediaHostDisconnectedDialog : BROptionDialog {
@private
	BRMediaHost *_mediaHost;	// 124 = 0x7c
	unsigned _timerSatisfied : 1;	// 128 = 0x80
}
@property(retain) BRMediaHost *mediaHost;	// G=0x3161b499; S=0x3161b50d; converted property
- (id)initWithHost:(id)host;	// 0x3161b625
- (void)_checkHostStatus:(id)status;	// 0x3161b795
- (void)dealloc;	// 0x3161b5dd
- (void)goToSources;	// 0x3161b545
// converted property getter: - (id)mediaHost;	// 0x3161b499
// converted property setter: - (void)setMediaHost:(id)host;	// 0x3161b50d
- (void)wasPushed;	// 0x3161b4a9
@end

