/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRImageLoader.h"


__attribute__((visibility("hidden")))
@interface BRMediaParadeProvider : BRImageLoader {
@private
	unsigned _artworkNeedsDeletterboxing : 1;	// 56 = 0x38
}
- (id)finalFormForImage:(id)image;	// 0x315ad551
- (BOOL)isImageFinalForm:(id)form;	// 0x315eebd5
- (void)setDeletterboxAssetArtwork:(BOOL)artwork;	// 0x315acba5
@end

