/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BRMetadataLinesLayer : BRControl {
@private
	NSArray *_lineLayers;	// 40 = 0x28
	float _lineHeight;	// 44 = 0x2c
}
- (id)init;	// 0x315b5cfd
- (void)_buildLineLayersForValues:(id)values andLabels:(id)labels usingIndexes:(id)indexes;	// 0x315b70d1
- (void)_layoutLines;	// 0x315b73bd
- (void)_setLineHeightUsingValues:(id)values andLabels:(id)labels;	// 0x315b6de9
- (id)_visibleMetadataIndexesForHeight:(float)height andValues:(id)values;	// 0x315b6f51
- (float)_widthOfWidestLabel;	// 0x315b74b9
- (void)dealloc;	// 0x315b7729
- (void)setMetadataValues:(id)values withLabels:(id)labels frameWidth:(float)width maxHeight:(float)height;	// 0x315b6d01
@end

