/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRTextWithSpinnerController.h"

@class BRMediaHost;
@protocol BRMediaLoading, BRMediaProvider;

__attribute__((visibility("hidden")))
@interface BRMediaHostConnectionDialog : BRTextWithSpinnerController {
@private
	BRMediaHost *_mediaHost;	// 76 = 0x4c
	id<BRMediaLoading, BRMediaProvider> _providerNeedingAuth;	// 80 = 0x50
	BRController *_controllerUnderneath;	// 84 = 0x54
	BOOL _timerSatisfied;	// 88 = 0x58
	BOOL _wasBuried;	// 89 = 0x59
	BOOL _passwordWasEntered;	// 90 = 0x5a
	BOOL _authAlreadyAttempted;	// 91 = 0x5b
}
@property(retain) BRMediaHost *mediaHost;	// G=0x3161a23d; S=0x3161a319; converted property
- (id)initWithHost:(id)host;	// 0x3161a4ad
- (void)_authRequired:(id)required;	// 0x3161a5c9
- (void)_checkMountStatus:(id)status;	// 0x3161abd5
- (void)_hostsChanged:(id)changed;	// 0x3161a251
- (void)_waitForHostReset:(id)hostReset;	// 0x3161a8dd
- (BOOL)brEventAction:(id)action;	// 0x3161b375
- (void)dealloc;	// 0x3161a38d
// converted property getter: - (id)mediaHost;	// 0x3161a23d
// converted property setter: - (void)setMediaHost:(id)host;	// 0x3161a319
- (void)textDidChange:(id)text;	// 0x3161a24d
- (void)textDidEndEditing:(id)text;	// 0x3161afbd
- (void)wasBuried;	// 0x3161a351
- (void)wasPushed;	// 0x3161b14d
@end

