/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSelectionHandler.h"


@interface BRMediaObjectButtonSelectionHandler : NSObject <BRSelectionHandler> {
@private
	int _selectionType;	// 4 = 0x4
}
- (id)init;	// 0x31623859
- (BOOL)_handleDeleteSelectionForControl:(id)control;	// 0x31623895
- (BOOL)_handlePlaySelectionForControl:(id)control;	// 0x31623a85
- (BOOL)_handleStartDownloadSelectionForControl:(id)control;	// 0x316239d9
- (BOOL)handleSelectionForControl:(id)control;	// 0x31623a3d
- (void)setSelectionHandlerType:(int)type;	// 0x31623849
@end

