/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRMenuController.h"

@class NSString, BRWaitSpinnerControl, NSTimer, BRControl, BRTextControl, BRFocusableImageControl;

@interface BRMediaMenuController : BRMenuController {
@private
	BRControl *_previewControl;	// 100 = 0x64
	BRControl *_previewContainer;	// 104 = 0x68
	NSString *_previewControlItemHash;	// 108 = 0x6c
	BRFocusableImageControl *_actionControl;	// 112 = 0x70
	BRWaitSpinnerControl *_spinner;	// 116 = 0x74
	BRControl *_observedControl;	// 120 = 0x78
	float _controlDelay;	// 124 = 0x7c
	NSTimer *_controlDelayTimer;	// 128 = 0x80
	BRTextControl *_noContentMessageControl;	// 132 = 0x84
}
@property(retain) id noContentMessage;	// G=0x315c120d; S=0x315c1791; converted property
@property(assign) BOOL showSpinner;	// G=0x315c0fd5; S=0x315c13b5; converted property
- (id)init;	// 0x315b3cf1
- (void)_cleanupControlDelayTimer;	// 0x315b4f65
- (void)_controlDelayTimerHandler:(id)handler;	// 0x315b8c9d
- (void)_playstateChanged;	// 0x315b97d1
- (void)_scrollSelectionFinalized:(id)finalized;	// 0x315c0fed
- (void)_scrollWillStart:(id)_scroll;	// 0x315b8bed
- (void)_setDislaysActionControl:(BOOL)control;	// 0x315b4a0d
- (void)_updateActionControl;	// 0x315b3ea9
- (void)_updateControls;	// 0x315b3e81
- (void)_updateControlsWithDelay;	// 0x315b8c15
- (void)_updatePreview;	// 0x315b3fd1
- (id)actionItemAtIndex:(long)index;	// 0x315c0fe9
- (id)actionSelectionHandlerForItemAtIndex:(long)index;	// 0x315b4a09
- (BOOL)allowUnplayedMark;	// 0x315b8381
- (BOOL)brEventAction:(id)action;	// 0x315c12d5
- (void)clearPreviewController;	// 0x315c123d
- (void)controlWasActivated;	// 0x315c10e5
- (void)controlWasDeactivated;	// 0x315b4e79
- (void)dealloc;	// 0x315b4f91
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x315b4d85
- (void)layoutSubcontrols;	// 0x315c1455
// converted property getter: - (id)noContentMessage;	// 0x315c120d
- (id)previewControlForItem:(long)item;	// 0x315c1001
- (void)refreshControllerForModelUpdate;	// 0x315beca1
- (void)refreshControllerForModelUpdateToObject:(id)object;	// 0x315b9d19
- (void)resetPreviewController;	// 0x315c129d
// converted property setter: - (void)setNoContentMessage:(id)message;	// 0x315c1791
// converted property setter: - (void)setShowSpinner:(BOOL)spinner;	// 0x315c13b5
// converted property getter: - (BOOL)showSpinner;	// 0x315c0fd5
- (void)updatePreviewController;	// 0x315b3e6d
@end

