/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMenuView.h"
#import "BackRow-Structs.h"

@class NSString, BRTabControl;

@interface BRMediaMenuView : BRMenuView {
@private
	BRControl *_preview;	// 72 = 0x48
	NSString *_previewLabel;	// 76 = 0x4c
	BRTabControl *_tabControl;	// 80 = 0x50
}
@property(retain) BRControl *preview;	// G=0x31679a11; S=0x31679ae5; converted property
@property(retain) NSString *previewLabel;	// G=0x31679a21; S=0x31679aad; converted property
@property(retain) BRTabControl *tabControl;	// G=0x31679a31; S=0x31679a41; converted property
- (BOOL)brEventAction:(id)action;	// 0x31679b51
- (void)dealloc;	// 0x31679c1d
- (void)layoutSubcontrols;	// 0x31679c89
// converted property getter: - (id)preview;	// 0x31679a11
// converted property getter: - (id)previewLabel;	// 0x31679a21
// converted property setter: - (void)setPreview:(id)preview;	// 0x31679ae5
// converted property setter: - (void)setPreviewLabel:(id)label;	// 0x31679aad
// converted property setter: - (void)setTabControl:(id)control;	// 0x31679a41
// converted property getter: - (id)tabControl;	// 0x31679a31
@end

