/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRMediaParadeLayer : BRControl {
@private
	CGSize _animationBounds;	// 40 = 0x28
	CGSize _maxImageBounds;	// 48 = 0x30
	BOOL _paused;	// 56 = 0x38
}
@property(assign) BOOL paused;	// G=0x315eeb2d; S=0x315acd4d; converted property
@property(retain) id provider;	// G=0x315eeb3d; S=0x315ade75; converted property
- (id)init;	// 0x315ac3b5
- (id)_addLayerForImage:(id)image;	// 0x315ad939
- (void)_updateAnimationForImageLayer:(id)imageLayer withTimeOffset:(double)timeOffset;	// 0x315ad9d1
- (void)_updateAnimations;	// 0x315ad289
- (void)_updateKeyframes;	// 0x315ad005
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x315ade95
- (void)layoutSubcontrols;	// 0x315eeb5d
- (long)maxImages;	// 0x315ac6f9
// converted property getter: - (BOOL)paused;	// 0x315eeb2d
// converted property getter: - (id)provider;	// 0x315eeb3d
- (void)setImages:(id)images;	// 0x315ad849
// converted property setter: - (void)setPaused:(BOOL)paused;	// 0x315acd4d
// converted property setter: - (void)setProvider:(id)provider;	// 0x315ade75
@end

