/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"
#import "BackRow-Structs.h"

@class NSMutableArray, NSTimer, NSDictionary, BRWindow;

@interface BRMediaPlayerManager : BRSingleton {
@private
	NSMutableArray *_registrations;	// 4 = 0x4
	NSDictionary *_singletons;	// 8 = 0x8
	BRWindow *_shroudyMcShroud;	// 12 = 0xc
	BRWindow *_playerWindow;	// 16 = 0x10
	NSTimer *_popupDelay;	// 20 = 0x14
	NSTimer *_autoPresentTimer;	// 24 = 0x18
	NSTimer *_safetyTimer;	// 28 = 0x1c
	double _autoPresentTimeout;	// 32 = 0x20
	int _playerWindowState;	// 40 = 0x28
	BOOL _playerWindowBeingRemoved;	// 44 = 0x2c
	BOOL _playerWindowBeingAdded;	// 45 = 0x2d
	BOOL _playerWindowRemovedWhileBeingAdded;	// 46 = 0x2e
	BOOL _screensaverUp;	// 47 = 0x2f
	float _savedVolume;	// 48 = 0x30
}
@property(assign) double autoPresentTimeout;	// G=0x31629ad1; S=0x3162af95; converted property
+ (void)setSingleton:(id)singleton;	// 0x31629ab5
+ (id)singleton;	// 0x31629aa9
- (id)init;	// 0x3158d221
- (void)_addPlayerWindowForController:(id)controller;	// 0x3162a645
- (void)_addPlayerWindowUnderShroud;	// 0x3162a599
- (void)_addShroudWindowWithSelector:(SEL)selector;	// 0x3162be51
- (id)_autoPresentPlayer;	// 0x31629fd9
- (void)_autoPresentTimerFired:(id)fired;	// 0x3162bb89
- (int)_calculateAccessModeForExtrasAsset:(id)extrasAsset;	// 0x3162ab95
- (void)_dataServerDAAPClientDidDisconnect:(id)_dataServerDAAPClient;	// 0x3162c065
- (void)_deferredPresentPlayerAndOptions:(id)options;	// 0x3162aabd
- (Class)_findRegisteredPlayerClassForType:(id)type visualContent:(BOOL)content;	// 0x3162aeed
- (void)_networkStatusChanged:(id)changed;	// 0x31629b69
- (void)_playerAssetChanged:(id)changed;	// 0x31629de5
- (void)_playerControllerUserEvent:(id)event;	// 0x3162a3b9
- (void)_playerControllerWasPopped:(id)popped;	// 0x31629ae1
- (id)_playerInstanceForAssetAtIndex:(long)index inTrackList:(id)trackList;	// 0x3162ad6d
- (id)_playerInstanceForClass:(Class)aClass;	// 0x3162ac21
- (void)_playerStackBankrupt:(id)bankrupt;	// 0x3162a3a1
- (void)_playerStateChanged:(id)changed;	// 0x31629e39
- (void)_playerVolumeChanged:(id)changed;	// 0x31629cf5
- (void)_popupDelayTimerFired:(id)fired;	// 0x3162a0c5
- (id)_presentedPlayer;	// 0x3162aa41
- (id)_presentedPlayerController;	// 0x3162a9e5
- (void)_removePlayerWindow:(BOOL)window;	// 0x3162a4a9
- (void)_removePlayerWindowUnderShroud;	// 0x3162a3dd
- (void)_removeShroudWindow;	// 0x3162aa65
- (void)_removeShroudWindowWithAnimation;	// 0x3162bcb9
- (void)_removeTrackPopup;	// 0x3162a2f5
- (void)_safetyTimerFired:(id)fired;	// 0x3162bbc9
- (void)_screenSaverActivated:(id)activated;	// 0x31629c99
- (void)_screenSaverDismissed:(id)dismissed;	// 0x31629c41
- (void)_serverStatusChanged:(id)changed;	// 0x3162c189
- (void)_showTrackPopupForPlayer:(id)player;	// 0x3162a17d
- (void)_showTrackPopupWithDelayForPlayer:(id)player;	// 0x3162a0fd
- (BOOL)_stopCurrentPlayerUsingNewPlayer:(id)player;	// 0x3162aaf9
- (void)_updateAutoPresentPlayer;	// 0x3162ba75
- (void)_updateTrackPopupForPlayer:(id)player;	// 0x3162a34d
- (void)_userActivity:(id)activity;	// 0x31629af5
- (id)activeAudioPlayer;	// 0x3162b159
- (id)activePlayer;	// 0x3162b219
- (id)airtunesAudioPlayer;	// 0x3162b0c1
- (id)audioPlayer;	// 0x3162b10d
- (id)audioVisualizer;	// 0x3162afcd
// converted property getter: - (double)autoPresentTimeout;	// 0x31629ad1
- (void)dealloc;	// 0x3162b9a5
- (void)endPresentation;	// 0x3162b279
- (id)playerForATVMediaAssetAtIndex:(long)index inTrackList:(id)trackList error:(id *)error;	// 0x3162b7fd
- (id)playerForMediaAsset:(id)mediaAsset error:(id *)error;	// 0x3162b931
- (id)playerForMediaAssetAtIndex:(long)index inCollection:(id)collection error:(id *)error;	// 0x3162b841
- (id)playerForMediaAssetAtIndex:(long)index inTrackList:(id)trackList error:(id *)error;	// 0x3162b8c9
- (void)presentATVMediaAsset:(ATVMediaItemRef)asset options:(id)options;	// 0x3162b389
- (void)presentATVMediaAssetAtIndex:(long)index inItemList:(id)itemList options:(id)options;	// 0x3162b319
- (void)presentMediaAsset:(id)asset options:(id)options;	// 0x3162b3d9
- (void)presentMediaAssetAtIndex:(long)index inCollection:(id)collection options:(id)options;	// 0x3162b2a9
- (void)presentMediaAssetAtIndex:(long)index inTrackList:(id)trackList options:(id)options;	// 0x3162b2e1
- (void)presentPlayer:(id)player options:(id)options;	// 0x3162b4e1
- (BOOL)presentationCanBeScreenSaver;	// 0x3162b255
- (id)presentationWindow;	// 0x31629ac1
- (void)registerPlayerClass:(Class)aClass;	// 0x3162bc41
- (void)removePresentation;	// 0x3162b291
// converted property setter: - (void)setAutoPresentTimeout:(double)timeout;	// 0x3162af95
- (void)showVolumeControl;	// 0x3162c2c9
- (void)stopMediaPlayersWithMediaFromProvider:(id)provider;	// 0x3162afed
@end

