/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"


@interface BRMerchant : NSObject <NSCopying, NSCoding> {
}
+ (id)allocWithZone:(NSZone *)zone;	// 0x31686fe1
+ (id)identifier;	// 0x31687099
+ (id)merchant;	// 0x31686f89
+ (id)merchantForControl:(id)control;	// 0x31686f25
+ (id)merchantForControl:(id)control defaultMerchant:(id)merchant;	// 0x31686ee9
+ (id)merchantForObject:(id)object;	// 0x31686f3d
+ (id)merchantForObject:(id)object defaultMerchant:(id)merchant;	// 0x316870b1
+ (id)merchantWithIdentifier:(id)identifier;	// 0x31686f55
+ (void)registerMerchant:(Class)merchant withIdentifier:(id)identifier;	// 0x31687031
- (id)initWithCoder:(id)coder;	// 0x31686d2d
- (void)assignToControl:(id)control;	// 0x31686df9
- (BOOL)assignToObject:(id)object;	// 0x31686e2d
- (id)brandImageForControl:(id)control;	// 0x31686de1
- (id)brandImageForControl:(id)control fromDictionary:(id)dictionary;	// 0x31686d45
- (BOOL)brandsControls;	// 0x31686d41
- (id)copyWithZone:(NSZone *)zone;	// 0x31686d29
- (id)description;	// 0x31686d35
- (void)encodeWithCoder:(id)coder;	// 0x31686d31
- (id)generateRequestForURL:(id)url headers:(id)headers method:(id)method;	// 0x31686d4d
- (id)identifier;	// 0x31686ec5
- (id)localizedStringForKey:(id)key;	// 0x31686fd5
- (id)merchantErrorForError:(id)error;	// 0x31686d49
- (void)release;	// 0x31686d1d
- (id)retain;	// 0x31686d19
- (unsigned)retainCount;	// 0x31686d21
@end

