/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@protocol BRMediaObject <NSObject>
- (BOOL)isValid;
- (id)mediaObjectID;
- (void)performSelector:(SEL)selector target:(id)target;
- (void)performSelector:(SEL)selector target:(id)target withObject:(id)object;
@end

