/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



__attribute__((visibility("hidden")))
@interface BRMusicScrubber : NSObject {
@private
	unsigned _skipCount;	// 4 = 0x4
	int _skipAdjustTimeInMS;	// 8 = 0x8
	double _nextSkipAdjustTime;	// 12 = 0xc
	double _skipAdjustTimeInterval;	// 20 = 0x14
}
- (id)initWithSkipAdjustInMS:(int)ms;	// 0x31689cad
- (id)initWithSkipAdjustInMS:(int)ms withAdjustTimeInterval:(double)adjustTimeInterval;	// 0x31689c19
- (void)dealloc;	// 0x31689ac9
- (double)nextTimeToAdvanceToFromTime:(double)time;	// 0x31689af5
@end

