/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRAXTitleChangeProtocol.h"
#import "BRAXMetadataChangeProtocol.h"
#import "BRAudioVisualizerControl.h"

@class NSString, NSTimer, NSDictionary, BRMusicNowPlayingLayer, BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface BRMusicNowPlayingControl : BRAudioVisualizerControl <BRAXTitleChangeProtocol, BRAXMetadataChangeProtocol> {
@private
	BRMusicNowPlayingLayer *_layer;	// 40 = 0x28
	BRMediaPlayer *_player;	// 44 = 0x2c
	NSString *_lastAssetID;	// 48 = 0x30
	NSTimer *_flipTimer;	// 52 = 0x34
	NSTimer *_delayedContentUpdateTimer;	// 56 = 0x38
	NSTimer *_flipRearrangeTimer;	// 60 = 0x3c
	NSTimer *_assetChangeAnimationUnblockTimer;	// 64 = 0x40
	double _flipDuration;	// 68 = 0x44
	double _flipInterval;	// 76 = 0x4c
	double _assetChangeAnimationBlockTime;	// 84 = 0x54
	double _assetChangeAnimationDuration;	// 92 = 0x5c
	double _newTrackKicksInTime;	// 100 = 0x64
	double _oldTrackFadeOutTime;	// 108 = 0x6c
	double _postFlipAssetChangeAnimationBlockTime;	// 116 = 0x74
	int _transitionDirection;	// 124 = 0x7c
	BOOL _assetChangeAnimationBlockFlag;	// 128 = 0x80
	BOOL _buffering;	// 129 = 0x81
	NSDictionary *_periodicMetadata;	// 132 = 0x84
}
@property(retain) id player;	// G=0x315f0051; S=0x315f066d; converted property
- (id)init;	// 0x315ba605
- (void)_chapterPictureChanged:(id)changed;	// 0x315f0335
- (id)_fetchCoverArt;	// 0x315bb419
- (void)_flipNow:(id)now;	// 0x315f0271
- (void)_periodicMetadataChanged:(id)changed;	// 0x315f0081
- (void)_playbackAssetChanged:(id)changed;	// 0x315f0439
- (void)_playbackProgressChanged:(id)changed;	// 0x315bb9cd
- (void)_playlistChanged:(id)changed;	// 0x315f0421
- (void)_radioBufferingEnd:(id)end;	// 0x315f0229
- (void)_radioBufferingStart:(id)start;	// 0x315f024d
- (void)_repeatModeChanged:(id)changed;	// 0x315f0171
- (void)_setTransitionDirection:(id)direction;	// 0x315f00d9
- (void)_shuffleModeChanged:(id)changed;	// 0x315f01cd
- (void)_unblockAssetChangeAnimation:(id)animation;	// 0x315f0065
- (void)_updateCoverArt:(id)art;	// 0x315f0369
- (void)_updateElapsedTime;	// 0x315bb4f5
- (void)_updatePlayerRepeatState;	// 0x315bb8c9
- (void)_updatePlayerShuffleState;	// 0x315bb869
- (void)_updateTrackWithTransition:(BOOL)transition;	// 0x315bae31
- (id)axMetadataText;	// 0x315f0615
- (id)axTitleText;	// 0x315f0645
- (void)controlWasActivated;	// 0x315bb9e1
- (void)controlWasDeactivated;	// 0x315bbca1
- (void)dealloc;	// 0x315bbf1d
- (BOOL)displayTrackPopup;	// 0x315f0061
- (void)layoutSubcontrols;	// 0x315f06a5
// converted property getter: - (id)player;	// 0x315f0051
// converted property setter: - (void)setPlayer:(id)player;	// 0x315f066d
@end

