/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@protocol BRRatingInfoDatabase;

@interface BRParentalControlManager : BRSingleton {
@private
	id<BRRatingInfoDatabase> _ratingInfoDatabase;	// 4 = 0x4
}
@property(assign) BOOL accessControlEnabled;	// G=0x31596771; S=0x3162d405; converted property
@property(assign) int accessModeForPurchase;	// G=0x3162c725; S=0x3162c76d; converted property
@property(retain) id defaultRatingSystemID;	// G=0x3162d2b5; S=0x3162d2ed; converted property
@property(retain) id pin;	// G=0x3162d329; S=0x3162d361; converted property
@property(retain) id ratingDatabase;	// G=0x315a5105; S=0x31595251; converted property
+ (void)setSingleton:(id)singleton;	// 0x31595245
+ (id)singleton;	// 0x3159520d
+ (BOOL)storeAccessRestricted;	// 0x3162c555
- (id)init;	// 0x31595219
// converted property getter: - (BOOL)accessControlEnabled;	// 0x31596771
- (int)accessModeForAppliance:(id)appliance categoryIdentifier:(id)identifier;	// 0x3162cc5d
- (int)accessModeForMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID withRank:(id)rank;	// 0x3162c82d
// converted property getter: - (int)accessModeForPurchase;	// 0x3162c725
- (void)clearAccessModeforAppliance:(id)appliance categoryIdentifier:(id)identifier;	// 0x3162d0fd
- (int)computeAccessModeForAppliance:(id)appliance withCategoryIdentifier:(id)categoryIdentifier;	// 0x3159673d
- (int)computeAccessModeForAsset:(id)asset;	// 0x315aa8f1
- (int)computeAccessModeForPurchase;	// 0x315a50d9
- (int)computeAccessModeForPurchaseWithMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID withRank:(id)rank isExplicit:(BOOL)anExplicit;	// 0x315a5115
// converted property getter: - (id)defaultRatingSystemID;	// 0x3162d2b5
- (int)explicitAccessModeForMediaType:(id)mediaType;	// 0x315ba491
// converted property getter: - (id)pin;	// 0x3162d329
// converted property getter: - (id)ratingDatabase;	// 0x315a5105
// converted property setter: - (void)setAccessControlEnabled:(BOOL)enabled;	// 0x3162d405
- (void)setAccessMode:(int)mode forAppliance:(id)appliance categoryIdentifier:(id)identifier;	// 0x3162ce21
- (void)setAccessMode:(int)mode forMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID withThresholdRank:(id)thresholdRank;	// 0x3162ca01
// converted property setter: - (void)setAccessModeForPurchase:(int)purchase;	// 0x3162c76d
// converted property setter: - (void)setDefaultRatingSystemID:(id)anId;	// 0x3162d2ed
- (void)setExplicitAccessMode:(int)mode forMediaType:(id)mediaType;	// 0x3162c5a1
// converted property setter: - (void)setPin:(id)pin;	// 0x3162d361
// converted property setter: - (void)setRatingDatabase:(id)database;	// 0x31595251
- (id)thresholdForMediaType:(id)mediaType withRatingSystemID:(id)ratingSystemID;	// 0x3162c3f1
@end

