/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRFullScreenPhotoControllerDelegate.h"
#import "BRController.h"

@class BRPhotoBrowserBannerButton, BRGridControl, BRScrollControl, BRWaitSpinnerControl, BRTextControl, NSDateFormatter, BRCursorControl, NSInvocation, BRPanelControl, BRPhotoBrowserHeaderControl, NSString, NSTimer;
@protocol BRProvider;

@interface BRPhotoBrowserController : BRController <BRFullScreenPhotoControllerDelegate> {
@private
	id<BRProvider> _provider;	// 56 = 0x38
	int _style;	// 60 = 0x3c
	float _iconVerticalOffset;	// 64 = 0x40
	NSString *_subtitleKey;	// 68 = 0x44
	int _cursorStyle;	// 72 = 0x48
	BOOL _displaysCount;	// 76 = 0x4c
	NSDateFormatter *_formatter;	// 80 = 0x50
	long _providerDataCount;	// 84 = 0x54
	BRPhotoBrowserHeaderControl *_header;	// 88 = 0x58
	BRGridControl *_grid;	// 92 = 0x5c
	BRWaitSpinnerControl *_spinner;	// 96 = 0x60
	BRCursorControl *_cursorControl;	// 100 = 0x64
	BRScrollControl *_scroller;	// 104 = 0x68
	BRPanelControl *_bannerControl;	// 108 = 0x6c
	BRTextControl *_noContentMessageControl;	// 112 = 0x70
	NSTimer *_noContentMessageTimer;	// 116 = 0x74
	BOOL _isNetworkDependent;	// 120 = 0x78
	BOOL _isValidWithZeroData;	// 121 = 0x79
	BOOL _useCorkBoardBackground;	// 122 = 0x7a
	NSInvocation *_invocation;	// 124 = 0x7c
	BRPhotoBrowserBannerButton *_slideshowButton;	// 128 = 0x80
	BRPhotoBrowserBannerButton *_settingsButton;	// 132 = 0x84
}
@property(assign) int columnCount;	// G=0x31615ae5; S=0x31615b25; converted property
@property(assign) int cursorStyle;	// G=0x31615b65; S=0x31615b85; converted property
@property(assign) BOOL displaysCount;	// G=0x31615ce9; S=0x31615d0d; converted property
@property(assign) float dividerBrightness;	// G=0x31615a65; S=0x31615a85; converted property
@property(assign) float horizontalGap;	// G=0x31615b05; S=0x31615b45; converted property
@property(retain) id icon;	// G=0x31615c95; S=0x31615cb5; converted property
@property(assign) float iconVerticalOffset;	// G=0x31615c41; S=0x31615c61; converted property
@property(assign) BOOL isNetworkDependent;	// G=0x31614a1d; S=0x31614a0d; converted property
@property(assign) BOOL isValidWithZeroData;	// G=0x31614a3d; S=0x31614a2d; converted property
@property(assign) int style;	// G=0x316149ed; S=0x31616665; converted property
@property(retain) id subtitle;	// G=0x31615bed; S=0x31615c0d; converted property
@property(retain) NSString *subtitleKey;	// G=0x316149fd; S=0x31615ba5; converted property
@property(retain) id title;	// G=0x31615d41; S=0x31615d61; converted property
@property(assign) float verticalGap;	// G=0x31615aa5; S=0x31615ac5; converted property
+ (id)controllerForProvider:(id)provider;	// 0x31615e75
+ (id)controllerForProvider:(id)provider style:(int)style;	// 0x31615e15
- (id)initWithProvider:(id)provider;	// 0x31615e5d
- (id)initWithProvider:(id)provider style:(int)style;	// 0x316163c5
- (id)_containerCollection;	// 0x316151b1
- (void)_focusChanged:(id)changed;	// 0x31614cb5
- (void)_handleSelection:(id)selection;	// 0x31614d99
- (void)_handleSettingsSelection:(id)selection;	// 0x31614ced
- (void)_handleSlideshowSelection:(id)selection;	// 0x31616cad
- (void)_hideNoContentMessage;	// 0x31615175
- (void)_initiateSlideshowPlaybackAtIndex:(long)index inCollection:(id)collection withOptions:(id)options;	// 0x31615051
- (void)_noContentTimerFired:(id)fired;	// 0x3161511d
- (void)_playerStateChanged:(id)changed;	// 0x31614ac9
- (void)_providerUpdated:(id)updated;	// 0x31614b55
- (void)_setupControls;	// 0x316153c1
- (void)_showNoContentMessage;	// 0x31616c0d
- (void)_slideshowPlayerAssetChanged:(id)changed;	// 0x31614a5d
- (id)_subtitleStringForKey:(id)key;	// 0x316151fd
- (void)addBannerControl:(id)control;	// 0x316159cd
- (BOOL)brEventAction:(id)action;	// 0x31615eb9
// converted property getter: - (int)columnCount;	// 0x31615ae5
- (void)controlWasActivated;	// 0x31616125
- (void)controlWasDeactivated;	// 0x316160d9
// converted property getter: - (int)cursorStyle;	// 0x31615b65
- (void)dealloc;	// 0x3161627d
// converted property getter: - (BOOL)displaysCount;	// 0x31615ce9
// converted property getter: - (float)dividerBrightness;	// 0x31615a65
// converted property getter: - (float)horizontalGap;	// 0x31615b05
// converted property getter: - (id)icon;	// 0x31615c95
// converted property getter: - (float)iconVerticalOffset;	// 0x31615c41
- (id)invocaiton;	// 0x31614a4d
// converted property getter: - (BOOL)isNetworkDependent;	// 0x31614a1d
- (BOOL)isValidAfterDataUpdate;	// 0x31615ddd
// converted property getter: - (BOOL)isValidWithZeroData;	// 0x31614a3d
- (void)layoutSubcontrols;	// 0x31616931
- (void)photoPlaybackWillStartForPlayer:(id)photoPlayback;	// 0x31615845
// converted property setter: - (void)setColumnCount:(int)count;	// 0x31615b25
// converted property setter: - (void)setCursorStyle:(int)style;	// 0x31615b85
// converted property setter: - (void)setDisplaysCount:(BOOL)count;	// 0x31615d0d
// converted property setter: - (void)setDividerBrightness:(float)brightness;	// 0x31615a85
// converted property setter: - (void)setHorizontalGap:(float)gap;	// 0x31615b45
// converted property setter: - (void)setIcon:(id)icon;	// 0x31615cb5
// converted property setter: - (void)setIconVerticalOffset:(float)offset;	// 0x31615c61
- (void)setInvocation:(id)invocation;	// 0x31615995
// converted property setter: - (void)setIsNetworkDependent:(BOOL)dependent;	// 0x31614a0d
// converted property setter: - (void)setIsValidWithZeroData:(BOOL)zeroData;	// 0x31614a2d
- (void)setLastViewedSlideIndex:(int)index;	// 0x316158c9
// converted property setter: - (void)setStyle:(int)style;	// 0x31616665
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x31615c0d
// converted property setter: - (void)setSubtitleKey:(id)key;	// 0x31615ba5
// converted property setter: - (void)setTitle:(id)title;	// 0x31615d61
// converted property setter: - (void)setVerticalGap:(float)gap;	// 0x31615ac5
// converted property getter: - (int)style;	// 0x316149ed
// converted property getter: - (id)subtitle;	// 0x31615bed
// converted property getter: - (id)subtitleKey;	// 0x316149fd
// converted property getter: - (id)title;	// 0x31615d41
// converted property getter: - (float)verticalGap;	// 0x31615aa5
- (void)wasBuried;	// 0x31616235
- (void)wasExhumed;	// 0x316161ed
@end

