/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRPhotoProvider.h"
#import "BRProvider.h"
#import "BRPhotoProviderForCollection.h"

@class NSArray;
@protocol BRMediaCollection;

@protocol BRPhotoProviderForCollection <BRProvider>
- (BOOL)canHaveZeroData;
- (id)collection;
@end

@interface BRPhotoProviderForCollection : BRPhotoProvider <BRPhotoProviderForCollection> {
@private
	NSArray *_assets;	// 12 = 0xc
	id<BRMediaCollection> _parentCollection;	// 16 = 0x10
}
+ (id)providerWithAssets:(id)assets parentCollection:(id)collection controlFactory:(id)factory;	// 0x3167b6b9
- (id)initWithAssets:(id)assets parentCollection:(id)collection controlFactory:(id)factory;	// 0x3167b639
- (BOOL)canHaveZeroData;	// 0x3167b555
- (id)collection;	// 0x3167b545
- (id)dataAtIndex:(long)index;	// 0x3167b57d
- (long)dataCount;	// 0x3167b5bd
- (void)dealloc;	// 0x3167b5dd
- (id)hashForDataAtIndex:(long)index;	// 0x3167b559
@end

