/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRDataStore.h"

@protocol BRMediaCollection;

@interface BRPlaylistDataStore : BRDataStore {
@private
	id<BRMediaCollection> _playlist;	// 40 = 0x28
}
- (id)initWithPlaylist:(id)playlist mediaTypes:(id)types;	// 0x31634ce9
- (void)addObject:(id)object;	// 0x316349b5
- (void)dealloc;	// 0x31634ca1
- (id)loadData;	// 0x31634a45
- (void)objectModified:(id)modified;	// 0x316349f9
- (id)playlist;	// 0x316349a5
- (void)removeObject:(id)object;	// 0x316349b9
- (BOOL)storeAppliesToObject:(id)object;	// 0x31634c61
@end

