/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRPosterImageControl : BRControl {
@private
	BRImage *_image;	// 40 = 0x28
	float _cornerRadius;	// 44 = 0x2c
	float _posterBorderWidth;	// 48 = 0x30
	CGColorRef _posterBorderColor;	// 52 = 0x34
}
- (id)initWithImage:(id)image cornerRadius:(float)radius borderWidth:(float)width borderColor:(CGColorRef)color;	// 0x3160fccd
- (void)dealloc;	// 0x3160fae5
- (void)drawInContext:(CGContextRef)context;	// 0x31610aa1
@end

