/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

__attribute__((visibility("hidden")))
@interface BRPosterLayer : CALayer {
@private
	BOOL _requiresDrawing;	// 48 = 0x30
}
@property(assign) BOOL requiresDrawing;	// G=0x3160d7c9; S=0x3160d7b9; converted property
+ (id)defaultActionForKey:(id)key;	// 0x3160d7d9
- (void)display;	// 0x3160d7e9
// converted property getter: - (BOOL)requiresDrawing;	// 0x3160d7c9
// converted property setter: - (void)setRequiresDrawing:(BOOL)drawing;	// 0x3160d7b9
@end

