/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlHeightFactory.h"
#import "BRControlFactory.h"

@class BRImage;

@interface BRPosterControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	BRImage *_defaultImage;	// 4 = 0x4
}
+ (id)factory;	// 0x315d86ad
- (id)init;	// 0x315d8499
- (id)_posterForGridFromAsset:(id)asset currentControl:(id)control requestedBy:(id)by;	// 0x315d85f5
- (id)_posterForShelfFromAsset:(id)asset currentControl:(id)control requestedBy:(id)by;	// 0x315d85a5
- (id)_posterFromAsset:(id)asset currentControl:(id)control requestedBy:(id)by;	// 0x315d84d1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x315d86dd
- (void)dealloc;	// 0x315d8665
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x315d88d9
- (void)setDefaultImage:(id)image;	// 0x315d862d
@end

