/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRPercentageIndicatorLayer.h"


@interface BRProgressBarWidget : BRPercentageIndicatorLayer {
}
- (id)init;	// 0x31612c71
@end

