/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSelectionHandler.h"


__attribute__((visibility("hidden")))
@interface BRPreviewBrowserSelectionHandler : NSObject <BRSelectionHandler> {
}
- (BOOL)handleSelectionForControl:(id)control;	// 0x315f30d5
@end

