/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


@interface BRRoundRectOutlineLayer : BRControl {
@private
	CGColorRef _color;	// 40 = 0x28
	float _lineWidth;	// 44 = 0x2c
	float _cornerRadius;	// 48 = 0x30
}
@property(assign) float cornerRadius;	// G=0x315b067d; S=0x315af6a5; converted property
@property(assign) float lineWidth;	// G=0x3161e919; S=0x315af681; converted property
@property(assign) CGColorRef outlineColor;	// G=0x3161e909; S=0x315af645; converted property
- (id)init;	// 0x315af5e1
// converted property getter: - (float)cornerRadius;	// 0x315b067d
- (void)dealloc;	// 0x315b3cb5
- (void)drawInContext:(CGContextRef)context;	// 0x315b03fd
// converted property getter: - (float)lineWidth;	// 0x3161e919
// converted property getter: - (CGColorRef)outlineColor;	// 0x3161e909
// converted property setter: - (void)setCornerRadius:(float)radius;	// 0x315af6a5
// converted property setter: - (void)setLineWidth:(float)width;	// 0x315af681
// converted property setter: - (void)setOutlineColor:(CGColorRef)color;	// 0x315af645
@end

