/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class NSAttributedString;

__attribute__((visibility("hidden")))
@interface BRScrollingTextPlane : BRControl {
@private
	NSAttributedString *_string;	// 40 = 0x28
	float _pursuitGap;	// 44 = 0x2c
	CGSize _cachedNaturalTextSize;	// 48 = 0x30
}
@property(retain) id attributedString;	// G=0x315ecc05; S=0x315ed2b5; converted property
+ (Class)layerClass;	// 0x315ed339
// converted property getter: - (id)attributedString;	// 0x315ecc05
- (void)dealloc;	// 0x315ed629
- (void)drawInContext:(CGContextRef)context;	// 0x315edb55
- (CGSize)naturalTextSize;	// 0x315edc51
// converted property setter: - (void)setAttributedString:(id)string;	// 0x315ed2b5
- (void)setPursuitGap:(float)gap;	// 0x315ed281
- (void)setTileSize:(CGSize)size;	// 0x315ed255
@end

