/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlHeightFactory.h"
#import "BRControlFactory.h"

@protocol BRSelectionHandler;

@interface BRSeriesControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	int _controlType;	// 4 = 0x4
	float _textImageMenuItemLayerHeight;	// 8 = 0x8
	float _dividerHeight;	// 12 = 0xc
	BOOL _hidePartialPlayedImages;	// 16 = 0x10
	id<BRSelectionHandler> _selectionHandler;	// 20 = 0x14
}
@property(retain) id selectionHandler;	// G=0x315d8981; S=0x315d9409; converted property
+ (id)factoryForControlType:(int)controlType hidePartialPlayedImages:(BOOL)images;	// 0x315d950d
- (id)initFactoryForControlType:(int)controlType hidePartialPlayedImages:(BOOL)images;	// 0x315d9489
- (id)_acquiredDateBasedAssetListItem:(id)item currentControl:(id)control;	// 0x315d92d9
- (id)_acquiredDateFromAsset:(id)asset;	// 0x315d8c89
- (id)_airedDateFromAsset:(id)asset;	// 0x315d8c5d
- (void)_assets:(id)assets areHD:(BOOL *)hd haveUnplayed:(BOOL *)unplayed havePartiallyPlayed:(BOOL *)played latestDate:(id *)date;	// 0x315d89e5
- (void)_badgeListItem:(id)item withInfoFromAsset:(id)asset setRightJustifiedText:(BOOL *)text;	// 0x315d8af1
- (id)_episodeBasedAssetListItem:(id)item currentControl:(id)control;	// 0x315d9095
- (id)_listItemForAsset:(id)asset currentControl:(id)control;	// 0x315d93c5
- (void)_markPlayedUnplayedState:(id)state markNew:(BOOL)aNew markPartialPlayed:(BOOL)played;	// 0x315d8991
- (id)_posterControlForSeriesArray:(id)seriesArray currentControl:(id)control;	// 0x315d8df1
- (id)_previewControlForData:(id)data currentControl:(id)control;	// 0x315d8cb5
- (id)_showBasedAssetListItem:(id)item currentControl:(id)control;	// 0x315d91dd
- (id)_showBasedSeriesItem:(id)item currentControl:(id)control;	// 0x315d8f21
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x315d9551
- (void)dealloc;	// 0x315d9441
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x315d9821
// converted property getter: - (id)selectionHandler;	// 0x315d8981
// converted property setter: - (void)setSelectionHandler:(id)handler;	// 0x315d9409
@end

