/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMultiPartWidgetLayer.h"


__attribute__((visibility("hidden")))
@interface BRSelectionLozengeLayer : BRMultiPartWidgetLayer {
}
- (float)bottomGlowHeight;	// 0x31597201
- (float)edgeGlowWidth;	// 0x3159ceed
- (float)edgeInset;	// 0x31597209
- (float)overHeightFactor;	// 0x315ecb09
- (id)preferredActionForKey:(id)key;	// 0x315ecb0d
- (void)setFocused:(BOOL)focused;	// 0x315ecb05
- (float)topGlowHeight;	// 0x31597205
@end

