/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@protocol BRMusicStoreImageDecryptionAgent, BRSyncProgressAgent, BRYTSigningAgent, BRDAAPListenerEnabler;

@interface BRSentinel : BRSingleton {
@private
	id<BRMusicStoreImageDecryptionAgent> _musicStoreImageDecryptionAgent;	// 4 = 0x4
	id<BRMusicStoreImageDecryptionAgent> _musicStoreTrickPlayImageDecryptionAgent;	// 8 = 0x8
	id<BRSyncProgressAgent> _syncProgressAgent;	// 12 = 0xc
	id<BRYTSigningAgent> _signingAgent;	// 16 = 0x10
	id<BRDAAPListenerEnabler> _daapListenerEnabler;	// 20 = 0x14
	unsigned _networkDependentControllerCount;	// 24 = 0x18
}
@property(retain) id YTSigningAgent;	// G=0x315bd961; S=0x315951d5; converted property
@property(retain) id musicStoreImageDecryptionAgent;	// G=0x3159fc81; S=0x31595289; converted property
@property(retain) id musicStoreTrickPlayImageDecryptionAgent;	// G=0x3163ac65; S=0x3163b1b1; converted property
@property(retain) id syncProgressAgent;	// G=0x315beb35; S=0x315952c1; converted property
+ (void)setSingleton:(id)singleton;	// 0x315951c9
+ (id)singleton;	// 0x31594fb9
- (id)init;	// 0x31594fc5
// converted property getter: - (id)YTSigningAgent;	// 0x315bd961
- (void)_currentMediaServerDisconnected:(id)disconnected;	// 0x3163b27d
- (void)_databaseObjectWasAdded:(id)added;	// 0x3163aed1
- (void)_databaseObjectWasDeleted:(id)deleted;	// 0x3163ad69
- (void)_databaseObjectWasModified:(id)modified;	// 0x3163aff5
- (void)_databaseObjectWillBeDeleted:(id)_databaseObject;	// 0x3163ae6d
- (void)_databaseUpdateComplete:(id)complete;	// 0x315a0489
- (void)_databaseUpdateStarted:(id)started;	// 0x315a0385
- (void)_databaseUpdatedWhileSyncStateIdle:(id)idle;	// 0x3163ad0d
- (void)_networkStatusChanged:(id)changed;	// 0x3163b3b9
- (void)_newPhotoDatabaseAvailable:(id)available;	// 0x3163ac95
- (void)_syncHostAvailabilityChanged:(id)changed;	// 0x3159aae1
- (id)daapListenerEnabler;	// 0x3163ac85
- (void)dealloc;	// 0x3163b1e9
// converted property getter: - (id)musicStoreImageDecryptionAgent;	// 0x3159fc81
// converted property getter: - (id)musicStoreTrickPlayImageDecryptionAgent;	// 0x3163ac65
- (void)networkDependentControllerWasPopped;	// 0x315a73cd
- (void)networkDependentControllerWasPushed;	// 0x3163b119
- (void)setDAAPListenerEnabler:(id)enabler;	// 0x3163ac75
// converted property setter: - (void)setMusicStoreImageDecryptionAgent:(id)agent;	// 0x31595289
// converted property setter: - (void)setMusicStoreTrickPlayImageDecryptionAgent:(id)agent;	// 0x3163b1b1
// converted property setter: - (void)setSyncProgressAgent:(id)agent;	// 0x315952c1
// converted property setter: - (void)setYTSigningAgent:(id)agent;	// 0x315951d5
// converted property getter: - (id)syncProgressAgent;	// 0x315beb35
@end

