/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMediaMenuController.h"
#import "BackRow-Structs.h"
#import "BRMenuListItemProvider.h"

@class NSArray, BRIconPreviewController;

@interface BRSlideshowSettingsMusicController : BRMediaMenuController <BRMenuListItemProvider> {
@private
	NSArray *_playlistNames;	// 136 = 0x88
	long _currentSavedSelection;	// 140 = 0x8c
	BRIconPreviewController *_slideshowSettingsIconController;	// 144 = 0x90
	BOOL _isMusicAvailable;	// 148 = 0x94
}
- (id)init;	// 0x316189bd
- (BOOL)_isMusicAvailable;	// 0x31618521
- (void)_pickSelectedSetting;	// 0x31618611
- (long)_rowForTitle:(id)title;	// 0x316186dd
- (void)dealloc;	// 0x31618961
- (long)defaultIndex;	// 0x31618881
- (float)heightForRow:(long)row;	// 0x31618519
- (long)itemCount;	// 0x316187e5
- (id)itemForRow:(long)row;	// 0x31618805
- (void)itemSelected:(long)selected;	// 0x316188a5
- (id)previewControlForItem:(long)item;	// 0x3161873d
- (BOOL)rowSelectable:(long)selectable;	// 0x3161851d
- (id)titleForRow:(long)row;	// 0x316187c5
@end

