/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSConditionLock, NSMutableArray;

__attribute__((visibility("hidden")))
@interface BRTaskManager : BRSingleton {
@private
	NSMutableArray *_taskQueue;	// 4 = 0x4
	NSConditionLock *_queueLock;	// 8 = 0x8
	int _numberOfTaskThreadsRunning;	// 12 = 0xc
	int _numberOfFinishingThreads;	// 16 = 0x10
}
+ (void)setSingleton:(id)singleton;	// 0x315b1465
+ (id)singleton;	// 0x315b13b5
- (id)init;	// 0x315b13c1
- (void)_processTasks;	// 0x315b15e5
- (void)cancelTask:(id)task;	// 0x3163c551
- (void)dealloc;	// 0x3163bf31
- (void)scheduleTask:(id)task;	// 0x315b1471
@end

