/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRMultiPartWidgetLayer;

@interface BRTabControlItem : BRControl {
@private
	id _opaqueIdentifier;	// 40 = 0x28
	BRMultiPartWidgetLayer *_baseControl;	// 44 = 0x2c
	BRTextControl *_label;	// 48 = 0x30
}
@property(retain) id identifier;	// G=0x315f7705; S=0x315f7909; converted property
@property(retain) BRTextControl *label;	// G=0x315f78d9; S=0x315f7835; converted property
- (id)init;	// 0x315f79b5
- (void)dealloc;	// 0x315f7949
// converted property getter: - (id)identifier;	// 0x315f7705
// converted property getter: - (id)label;	// 0x315f78d9
- (void)layoutSubcontrols;	// 0x315f7ab9
// converted property setter: - (void)setIdentifier:(id)identifier;	// 0x315f7909
// converted property setter: - (void)setLabel:(id)label;	// 0x315f7835
- (void)setLabelAttributes:(id)attributes;	// 0x315f77e1
- (void)setLabelOpacity:(float)opacity;	// 0x315f77c1
- (void)setTabImages:(id)images;	// 0x315f7715
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315f7bad
@end

