/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRCursorLayer.h"


__attribute__((visibility("hidden")))
@interface BRTextEntryCursorLayer : BRCursorLayer {
}
- (id)init;	// 0x315b068d
- (float)animationDuration;	// 0x315e2721
- (id)animationTimingFunction;	// 0x315e2679
- (id)imageMapForCornerRadius:(float)cornerRadius;	// 0x315e278d
@end

