/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRThreadNotificationManager : NSObject {
}
+ (void)initializeNotificationCallbackForCurrentThread;	// 0x31598a11
+ (void)postNotification:(id)notification onThread:(id)thread;	// 0x3159b371
@end

