/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlMediator.h"

@class BRProviderGroup;

@interface BRThresholdControlMediator : BRControlMediator {
@private
	BRProviderGroup *_dataProviderGroup;	// 20 = 0x14
	int _activeThreshold;	// 24 = 0x18
}
- (void)_refreshActiveState;	// 0x31620d19
- (void)dealloc;	// 0x31620f31
- (void)setActiveThreshold:(int)threshold;	// 0x31620d61
- (void)setDataProvider:(id)provider;	// 0x31620d81
- (void)setDataProviders:(id)providers;	// 0x31620db5
@end

