/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@class NSMutableArray, NSLock;

__attribute__((visibility("hidden")))
@interface BRThreadCallback : NSObject {
@private
	CFRunLoopRef _loop;	// 4 = 0x4
	CFRunLoopSourceRef _source;	// 8 = 0x8
	NSMutableArray *_notifications;	// 12 = 0xc
	NSLock *_lock;	// 16 = 0x10
}
- (id)init;	// 0x31598b35
- (void)dealloc;	// 0x3164babd
@end

