/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRBackgroundTask.h"


__attribute__((visibility("hidden")))
@interface BRTopShelfRefreshTask : BRBackgroundTask {
}
- (id)init;	// 0x3166123d
- (BOOL)perform:(id)perform;	// 0x3166127d
@end

