/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@class NSMutableArray, NSAttributedString;

@interface BRTypesetter : NSObject {
@private
	NSAttributedString *_resolvedString;	// 4 = 0x4
	CTTypesetterRef _setter;	// 8 = 0x8
	NSMutableArray *_lines;	// 12 = 0xc
	CGSize _boxSize;	// 16 = 0x10
	CGSize _shadowOffset;	// 24 = 0x18
	CGColorRef _shadowColor;	// 32 = 0x20
	float _flushFactor;	// 36 = 0x24
	BOOL _renderingAttributesFetched;	// 40 = 0x28
}
+ (float)pointSizeForBoxHeight:(float)boxHeight fontName:(id)name;	// 0x3164c09d
- (id)initWithAttributedString:(id)attributedString textBoxSize:(CGSize)size;	// 0x3164c2b9
- (id)_boxLines:(BOOL *)lines;	// 0x315a3bb9
- (void)_justifyLines:(id)lines;	// 0x315a3d89
- (CTLineRef)_truncateLine:(CTLineRef)line withSetting:(unsigned char)setting;	// 0x3159f5e5
- (CTLineRef)_truncationToken;	// 0x3159f675
- (void)_updateRenderingAttributes;	// 0x3164c0ed
- (void)dealloc;	// 0x3159a5d9
- (void)drawTextAtPoint:(CGPoint)point inContext:(CGContextRef)context;	// 0x3159d1fd
- (id)lineAtIndex:(long)index;	// 0x3164bcc1
- (long)numLines;	// 0x3164bd85
- (CGSize)typographicBounds;	// 0x3159cc49
@end

