/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSelectionLozengeLayer.h"
#import "BackRow-Structs.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRUnboundedSelectionLozengeLayer : BRSelectionLozengeLayer {
@private
	BRImage *_topImage;	// 88 = 0x58
	BRImage *_bottomImage;	// 92 = 0x5c
	BOOL _brighterImage;	// 96 = 0x60
	BOOL _focusedImage;	// 97 = 0x61
}
@property(assign) BOOL useBrighterUnselectedImage;	// G=0x315ecb95; S=0x3159645d; converted property
- (id)init;	// 0x315962dd
- (void)_updateImages;	// 0x3159632d
- (void)dealloc;	// 0x315ecba9
- (void)drawInContext:(CGContextRef)context;	// 0x3159d075
- (void)layoutSubcontrols;	// 0x315ecba5
- (void)setFocused:(BOOL)focused;	// 0x3159d481
// converted property setter: - (void)setUseBrighterUnselectedImage:(BOOL)image;	// 0x3159645d
// converted property getter: - (BOOL)useBrighterUnselectedImage;	// 0x315ecb95
@end

