/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRURLDocument.h"


@interface BRURLPlist : BRURLDocument {
@private
	id _propertyList;	// 52 = 0x34
}
@property(readonly, retain) id propertyList;	// G=0x31686c29; converted property
- (void)dealloc;	// 0x31686cd1
- (void)documentLoaded;	// 0x31686c39
// converted property getter: - (id)propertyList;	// 0x31686c29
@end

