/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRUsageReporter : NSObject {
}
+ (void)clearDistributionKey:(id)key;	// 0x31685511
+ (void)clearScalarKey:(id)key;	// 0x316855f1
+ (void)decrementScalarKey:(id)key;	// 0x31685589
+ (void)incrementScalarKey:(id)key;	// 0x316855bd
+ (void)pushValue:(double)value forDistributionKey:(id)distributionKey;	// 0x316854cd
+ (void)setValue:(long long)value forScalarKey:(id)scalarKey;	// 0x31685545
@end

