/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRSingleton.h"


@interface BRVideoCacheManager : BRSingleton {
}
+ (void)setImplementationClass:(Class)aClass;	// 0x3168b13d
+ (void)setSingleton:(id)singleton;	// 0x3168b0fd
+ (id)singleton;	// 0x3168b0f1
- (id)cacheInfoForAsset:(id)asset;	// 0x3168b10d
- (void)evictAsset:(id)asset;	// 0x3168b115
- (BOOL)isItemLoading:(ATVMediaItemRef)loading;	// 0x3168b129
- (BOOL)isItemReadyToPlay:(ATVMediaItemRef)play;	// 0x3168b12d
- (id)playerItemForLoadingMediaItem:(ATVMediaItemRef)loadingMediaItem;	// 0x3168b139
- (void)saveCacheKey:(id)key forAsset:(id)asset;	// 0x3168b111
- (double)secondsUntilItemWillBeReadyToPlay:(ATVMediaItemRef)secondsUntilItem;	// 0x3168b131
- (void)setDelegate:(id)delegate;	// 0x3168b109
- (void)startCachingItem:(ATVMediaItemRef)item;	// 0x3168b119
- (void)startCachingItem:(ATVMediaItemRef)item withElapsedTime:(double)elapsedTime;	// 0x3168b11d
- (void)stopCaching;	// 0x3168b125
@end

