/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRProvider.h"
#import "BackRow-Structs.h"

@class NSTimer, BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface BRVideoChapterProvider : NSObject <BRProvider> {
@private
	BRMediaPlayer *_player;	// 4 = 0x4
	NSRange _invalidTitlesRange;	// 8 = 0x8
	NSTimer *_checkForChapterTitleUpdateTimer;	// 16 = 0x10
}
- (id)initWithPlayer:(id)player;	// 0x315dfa19
- (void)_checkChapterTitle:(id)title;	// 0x315dfd2d
- (void)_movieLoadedHandler:(id)handler;	// 0x315df855
- (BOOL)_videoIsLoaded;	// 0x315df8c1
- (id)controlFactory;	// 0x315df989
- (id)dataAtIndex:(long)index;	// 0x315dfaf1
- (long)dataCount;	// 0x315df955
- (void)dealloc;	// 0x315df9a9
- (id)hashForDataAtIndex:(long)index;	// 0x315df92d
- (void)stopMonitoring;	// 0x315df905
@end

