/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class WebView, WAKWindow, DOMElement, CALayer;
@protocol WebWindowDelegate;

__attribute__((visibility("hidden")))
@interface BRWebWindowControl : BRControl {
@private
	WebView *_webView;	// 40 = 0x28
	WAKWindow *_window;	// 44 = 0x2c
	DOMElement *_focusedElement;	// 48 = 0x30
	CALayer *_rootEffectsLayer;	// 52 = 0x34
	id<WebWindowDelegate> _delegate;	// 56 = 0x38
}
@property(assign) id delegate;	// G=0x316538f9; S=0x316538e9; converted property
@property(retain) DOMElement *focusedElement;	// G=0x31653909; S=0x3165393d; converted property
@property(readonly, retain) WebView *webView;	// G=0x316538d9; converted property
- (id)initWithFrame:(CGRect)frame;	// 0x31653bdd
- (void)close;	// 0x3165391d
- (void)dealloc;	// 0x31653b25
// converted property getter: - (id)delegate;	// 0x316538f9
- (CGRect)focusCursorFrame;	// 0x31653ee5
// converted property getter: - (id)focusedElement;	// 0x31653909
- (void)layoutSubcontrols;	// 0x31653db9
- (BOOL)postEvent:(id)event;	// 0x31653d15
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x316538e9
// converted property setter: - (void)setFocusedElement:(id)element;	// 0x3165393d
- (void)setRootEffectsLayer:(id)layer;	// 0x31653a31
- (int)touchSensitivity;	// 0x31653919
// converted property getter: - (id)webView;	// 0x316538d9
@end

