/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRBaseMediaAsset.h"

@class NSMutableDictionary;

@interface BRXMLMediaAsset : BRBaseMediaAsset {
@private
	NSMutableDictionary *_info;	// 8 = 0x8
}
@property(retain) id dictionary;	// G=0x315d0e2d; S=0x315d0fd5; converted property
- (id)init;	// 0x315d1469
- (id)initWithMediaProvider:(id)mediaProvider;	// 0x315ae72d
- (id)artist;	// 0x315d141d
- (id)assetID;	// 0x315ae82d
- (unsigned)bookmarkTimeInMS;	// 0x315d10a5
- (unsigned)bookmarkTimeInSeconds;	// 0x315d10e1
- (id)cast;	// 0x315b6441
- (id)composer;	// 0x315d0e29
- (id)copyright;	// 0x315b6011
- (id)coverArt;	// 0x315b34f1
- (id)coverArtID;	// 0x315b3369
- (id)dateAcquired;	// 0x315d1351
- (id)dateCreated;	// 0x315d133d
- (id)datePublished;	// 0x315b659d
- (void)dealloc;	// 0x315aee9d
- (id)description;	// 0x315d110d
// converted property getter: - (id)dictionary;	// 0x315d0e2d
- (id)directors;	// 0x315b646d
- (long)duration;	// 0x315d12a1
- (id)genres;	// 0x315b6699
- (BOOL)hasCoverArt;	// 0x315b31e5
- (BOOL)hasVideoContent;	// 0x315ae7c9
- (id)imageProxy;	// 0x315d1449
- (BOOL)isExplicit;	// 0x315d1159
- (BOOL)isHD;	// 0x315d100d
- (id)mediaSummary;	// 0x315b5fcd
- (id)mediaType;	// 0x315d112d
- (id)mediaURL;	// 0x315ae85d
- (long)parentalControlRatingRank;	// 0x315d11c9
- (long)parentalControlRatingSystemID;	// 0x315d1235
- (id)playbackMetadata;	// 0x315d105d
- (id)previewURL;	// 0x315b2c45
- (id)primaryCollectionTitle;	// 0x315d13f1
- (id)primaryGenre;	// 0x315b6661
- (id)publisher;	// 0x315d1399
- (id)rating;	// 0x315b5ed9
- (id)resolution;	// 0x315b31b9
// converted property setter: - (void)setDictionary:(id)dictionary;	// 0x315d0fd5
- (void)setObject:(id)object forKey:(id)key;	// 0x315ae791
- (id)thumbnailArt;	// 0x315be085
- (id)thumbnailArtID;	// 0x315bdee5
- (id)thumbnailURL;	// 0x315be021
- (id)title;	// 0x315b2641
- (id)trickPlayURL;	// 0x315d13c5
@end

