/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"


@interface DOMDocument (Clickability)
- (id)clickableNodes;	// 0x3165b9f5
- (id)clickableNodesInRect:(CGRect)rect;	// 0x3165b929
@end

