/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class BRWebControl;

__attribute__((visibility("hidden")))
@interface DOMEventBridge : NSObject <DOMEventListener> {
@private
	BRWebControl *_webControl;	// 4 = 0x4
	SEL _selector;	// 8 = 0x8
}
- (id)initWithWebControl:(id)webControl selector:(SEL)selector;	// 0x3164fdf1
- (void)handleEvent:(id)event;	// 0x3164fe39
- (void)setTarget:(id)target;	// 0x3164fde1
@end

