/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class BRListControl;

__attribute__((visibility("hidden")))
@interface ListAnimationDelegate : NSObject {
@private
	BRListControl *_list;	// 4 = 0x4
	long _animationBalance;	// 8 = 0x8
}
- (id)initWithList:(id)list;	// 0x31595ebd
- (void)animationDidStart:(id)animation;	// 0x315a8b55
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x315a8ded
- (void)clearScroll;	// 0x31677129
- (void)decrementBalance;	// 0x315a8e01
- (void)incrementBalance;	// 0x315a8b69
- (BOOL)scrolling;	// 0x3159cef1
@end

