/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRDataStore.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BRAggregateDataStore : BRDataStore {
@private
	NSArray *_dataStores;	// 40 = 0x28
}
- (id)initWithDataStores:(id)dataStores;	// 0x3162f279
- (void)dealloc;	// 0x3162f231
- (id)loadData;	// 0x3162f161
- (void)purge;	// 0x3162f1e5
- (void)setUseLocalProvidersOnly:(BOOL)only;	// 0x3162f0e9
- (BOOL)storeAppliesToObject:(id)object;	// 0x3162f089
@end

