/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"


@interface BRAirportNetwork : NSObject {
@private
	void/*WiFiNetwork*/ *_wiFiNetworkRef;	// 4 = 0x4
	BOOL _isDirected;	// 8 = 0x8
}
@property(assign, getter=isDirected) BOOL directed;	// G=0x3163b5b9; S=0x3163b5c9; converted property
@property(readonly, assign) void/*WiFiNetwork*/ *wiFiNetworkRef;	// G=0x3163b5a9; converted property
+ (void)asyncNetworkWithName:(id)name error:(id *)error;	// 0x3163b66d
+ (id)networkWithWiFiNetwork:(void/*WiFiNetwork*/ *)wiFiNetwork;	// 0x3163b8c9
- (id)init;	// 0x3163b5d9
- (BOOL)asyncAssociateUsingPassword:(id)password error:(id *)error;	// 0x3163b835
- (void)dealloc;	// 0x3163b615
// converted property getter: - (BOOL)isDirected;	// 0x3163b5b9
- (id)name;	// 0x3163b655
- (int)securityType;	// 0x3163b68d
// converted property setter: - (void)setDirected:(BOOL)directed;	// 0x3163b5c9
// converted property getter: - (void/*WiFiNetwork*/ *)wiFiNetworkRef;	// 0x3163b5a9
@end

