/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@protocol BRApplianceBrowserProtocol <NSObject>
- (id)actionForCurrentSelection;
- (void)clearRemembery;
- (id)controllerForCurrentSelection;
- (BOOL)controllerMatchesCurrentSelection:(id)selection;
- (void)highlightApplianceWithKey:(id)key andCategoryWithIdentifier:(id)identifier;
- (void)highlightItemsForController:(id)controller;
@end

