/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRImageProxy.h"
#import "BackRow-Structs.h"

@class NSMutableArray;

@interface BRATVDataImageProxy : NSObject <BRImageProxy> {
@private
	void *_mediaObject;	// 4 = 0x4
	ATVDataClientRef _dataClient;	// 8 = 0x8
	NSMutableArray *_savedTokens;	// 12 = 0xc
	BOOL _usesScreenSaverImageManager;	// 16 = 0x10
}
+ (id)imageProxyWithMediaObject:(void *)mediaObject;	// 0x3167a175
- (id)initWithMediaObject:(void *)mediaObject;	// 0x3167a221
- (void)_cancelImageForImageID:(id)imageID;	// 0x3167a379
- (id)_imageIDForImageSize:(int)imageSize;	// 0x31679ee9
- (id)_imageIDStringForSize:(int)size;	// 0x31679e69
- (id)_imageManager;	// 0x31679ea9
- (void *)_mediaID;	// 0x3167a425
- (void)_removeTokenForImageID:(id)imageID;	// 0x31679f9d
- (void)_saveToken:(void *)token forImageID:(id)imageID;	// 0x31679fed
- (id)_tokenInfoForImageID:(id)imageID;	// 0x3167a03d
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x3167a0b1
- (void)dealloc;	// 0x3167a30d
- (id)defaultImageForImageSize:(int)imageSize;	// 0x3167a1a9
- (id)imageForImageSize:(int)imageSize;	// 0x3167a4d5
- (id)imageIDForImageSize:(int)imageSize;	// 0x3167a161
- (id)object;	// 0x31679e49
- (void)setUsesScreenSaverImageManager:(BOOL)manager;	// 0x31679e59
- (BOOL)supportsImageForImageSize:(int)imageSize;	// 0x31679e45
@end

