/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRAudioVisualizerControl : BRControl {
}
@property(retain) id player;	// G=0x31635ffd; S=0x31635ff9; converted property
- (BOOL)displayTrackPopup;	// 0x31636001
// converted property getter: - (id)player;	// 0x31635ffd
// converted property setter: - (void)setPlayer:(id)player;	// 0x31635ff9
@end

