/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRAppliance.h"

@class NSArray;

@interface BRBaseAppliance : NSObject <BRAppliance> {
@private
	NSArray *_categories;	// 4 = 0x4
}
- (id)init;	// 0x3159278d
- (BOOL)_anySharesAvailable;	// 0x31598d4d
- (BOOL)_anyStoreCategoryExistsInMusicStoreCollection:(id)musicStoreCollection;	// 0x315bf475
- (id)_applianceCategories;	// 0x315974d1
- (BOOL)_isCategoryWithIdentifier:(id)identifier memberOfMusicStoreCollection:(id)musicStoreCollection;	// 0x31599111
- (id)alertControllerForNoContent;	// 0x315b7a59
- (id)alertControllerForNoRemoteContent;	// 0x315bf5b9
- (id)applianceCategories;	// 0x315973f5
- (id)applianceCategoryDescriptions;	// 0x315bf595
- (id)applianceInfo;	// 0x315928a9
- (id)baseMediaType;	// 0x31597905
- (id)categoryWithIdentifier:(id)identifier;	// 0x3159c85d
- (id)controllerForIdentifier:(id)identifier args:(id)args;	// 0x315bf445
- (void)dealloc;	// 0x31592fad
- (id)description;	// 0x315bf615
- (BOOL)handleObjectSelection:(id)selection userInfo:(id)info;	// 0x315bf449
- (BOOL)handlePlay:(id)play userInfo:(id)info;	// 0x315bf44d
- (id)identifierForContentAlias:(id)contentAlias;	// 0x315bf441
- (id)musicStoreItemWithIdentifier:(id)identifier;	// 0x3159c91d
- (int)noContentBRError;	// 0x315bf451
- (int)noRemoteContentBRError;	// 0x315bf459
- (BOOL)previewError;	// 0x315bf461
- (id)previewErrorIconImage;	// 0x315bf46d
- (id)previewErrorSubtext;	// 0x315bf469
- (id)previewErrorText;	// 0x315bf465
- (void)reloadCategories;	// 0x315bf539
- (id)topShelfController;	// 0x315bf471
@end

