/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMediaProvider.h"
#import "BRMediaLoading.h"


@interface BRBaseMediaProvider : NSObject <BRMediaProvider, BRMediaLoading> {
@private
	int _providerStatus;	// 4 = 0x4
	BOOL _passwordProtected;	// 8 = 0x8
}
@property(assign) BOOL isPasswordProtected;	// G=0x3162eb85; S=0x3162ec75; converted property
@property(assign) int status;	// G=0x315909b9; S=0x3158f5ad; converted property
+ (id)errorStateOfProvider:(id)provider;	// 0x3162ec41
+ (id)mediaProvider;	// 0x3162ec0d
- (BOOL)autoload;	// 0x315918d5
- (long)countOfObjectsWithMediaType:(id)mediaType;	// 0x3162eb99
- (void)dealloc;	// 0x315a478d
- (int)errorCodeForProvider;	// 0x3162eb51
- (void)flush;	// 0x3162eb95
// converted property getter: - (BOOL)isPasswordProtected;	// 0x3162eb85
- (int)load;	// 0x3162eb55
- (int)loadWithUsername:(id)username password:(id)password;	// 0x3162eb65
- (id)machineID;	// 0x3158f955
- (id)mediaForEntityName:(id)entityName;	// 0x3162ebb9
- (id)mediaTypes;	// 0x3162ebd9
- (id)objectsWithEntityName:(id)entityName qualifiedByPredicate:(id)predicate sortDescriptors:(id)descriptors error:(id *)error;	// 0x31599761
- (id)objectsWithEntityName:(id)entityName qualifiedByPredicate:(id)predicate sortDescriptors:(id)descriptors excludeHiddenObjects:(BOOL)objects error:(id *)error;	// 0x3162ec95
- (id)providerID;	// 0x31590a29
- (id)providerName;	// 0x3162ebf9
- (void)reset;	// 0x3162eba1
// converted property setter: - (void)setIsPasswordProtected:(BOOL)aProtected;	// 0x3162ec75
// converted property setter: - (void)setStatus:(int)status;	// 0x3158f5ad
// converted property getter: - (int)status;	// 0x315909b9
- (int)unload;	// 0x3162eb75
@end

