/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRSelectionLozengeLayer.h"


@interface BRBlueGlowSelectionLozengeLayer : BRSelectionLozengeLayer {
@private
	BOOL _focusedImage;	// 88 = 0x58
	BOOL _clearCenter;	// 89 = 0x59
}
@property(assign) BOOL clearCenter;	// G=0x3164f601; S=0x3164f6d9; converted property
- (id)init;	// 0x3164f729
- (float)bottomGlowHeight;	// 0x3164f959
// converted property getter: - (BOOL)clearCenter;	// 0x3164f601
- (void)drawInContext:(CGContextRef)context;	// 0x3164fa19
- (float)edgeGlowWidth;	// 0x3164f915
// converted property setter: - (void)setClearCenter:(BOOL)center;	// 0x3164f6d9
- (void)setFocused:(BOOL)focused;	// 0x3164f701
- (float)topGlowHeight;	// 0x3164f99d
@end

