/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRDividerControl;

@interface BRBoxControl : BRControl {
@private
	BRControl *_content;	// 40 = 0x28
	BRDividerControl *_divider;	// 44 = 0x2c
	float _dividerMargin;	// 48 = 0x30
	float _dividerSuggestedHeight;	// 52 = 0x34
	float _space;	// 56 = 0x38
}
@property(retain) BRControl *content;	// G=0x315dd5e1; S=0x3159e64d; converted property
@property(retain) BRDividerControl *divider;	// G=0x315dd5a1; S=0x315dd65d; converted property
@property(assign) float dividerMargin;	// G=0x315dd5d1; S=0x315dd601; converted property
@property(assign) float dividerSuggestedHeight;	// G=0x315dd5c1; S=0x315dd5b1; converted property
// converted property getter: - (id)content;	// 0x315dd5e1
- (void)dealloc;	// 0x3159f765
// converted property getter: - (id)divider;	// 0x315dd5a1
// converted property getter: - (float)dividerMargin;	// 0x315dd5d1
// converted property getter: - (float)dividerSuggestedHeight;	// 0x315dd5c1
- (void)layoutSubcontrols;	// 0x315dd6d5
// converted property setter: - (void)setContent:(id)content;	// 0x3159e64d
// converted property setter: - (void)setDivider:(id)divider;	// 0x315dd65d
// converted property setter: - (void)setDividerMargin:(float)margin;	// 0x315dd601
// converted property setter: - (void)setDividerSuggestedHeight:(float)height;	// 0x315dd5b1
- (void)setSpace:(float)space;	// 0x315dd5f1
@end

