/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"
#import "BRTabControlDelegate.h"

@class BRImageControl, BRTabControl, BRImage, BRTextControl, BRMediaPlayer, BRVideoChapterProvider, BRCoverArtPreviewControl, BRReflectionControl, NSValue;

__attribute__((visibility("hidden")))
@interface BRChapterSubtitleAudioPickerControl : BRControl <BRTabControlDelegate> {
@private
	BRImage *_currentVideoFrame;	// 40 = 0x28
	BRControl *_screenShotPreviewAndReflectionComboControl;	// 44 = 0x2c
	BRImageControl *_screenShotPreviewControl;	// 48 = 0x30
	CGPoint _screenShotPreviewControlFullScreenPosition;	// 52 = 0x34
	BRReflectionControl *_reflectionToPreviewControl;	// 60 = 0x3c
	NSValue *_previewTransform;	// 64 = 0x40
	NSValue *_reflectionTransform;	// 68 = 0x44
	BRVideoChapterProvider *_chapterProvider;	// 72 = 0x48
	BRCoverArtPreviewControl *_preview;	// 76 = 0x4c
	BRControl *_csaPicker;	// 80 = 0x50
	BRTabControl *_tabControl;	// 84 = 0x54
	BRTextControl *_titleControl;	// 88 = 0x58
	BRMediaPlayer *_player;	// 92 = 0x5c
	BRControl *_currentContentControl;	// 96 = 0x60
	BRControl *_chapterPicker;	// 100 = 0x64
	BOOL _inScreenShotMode;	// 104 = 0x68
	BOOL _controlWasActivated;	// 105 = 0x69
	BOOL _controlWasDeactivated;	// 106 = 0x6a
}
+ (id)controlWithPlayer:(id)player;	// 0x315de405
- (id)init;	// 0x315de369
- (void)_addCSAPicker;	// 0x315dddc1
- (void)_addFullScreenVideoSnapshot;	// 0x315dddb9
- (void)_animatePreviewBackToScreenshot;	// 0x315dddf9
- (void)_animateScreenshotToPreview;	// 0x315dddbd
- (BOOL)_chapterPreviewsAvailable;	// 0x315dde69
- (void)_createCSAPicker;	// 0x315ded75
- (void)_endPositionForPreview:(CGPoint *)preview forReflection:(CGPoint *)reflection;	// 0x315de7b9
- (void)_loadAudioList;	// 0x315de9ad
- (void)_loadChapters;	// 0x315dde31
- (void)_loadGraphicalChapterList;	// 0x315df1f5
- (void)_loadListWithTitles:(id)titles forTrackIDs:(id)trackIDs withCurrentSelection:(long)currentSelection withSelectionHandler:(id)selectionHandler;	// 0x315defb5
- (void)_loadSubtitleList;	// 0x315deb41
- (void)_loadTextualChapterList;	// 0x315df4b5
- (void)_setAudioTrack:(id)track;	// 0x315dde8d
- (void)_setChapter:(id)chapter;	// 0x315ddf9d
- (void)_setSubtitleTrack:(id)track;	// 0x315ddf15
- (id)_titleControlItemLabelAttributes;	// 0x315ded55
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x315de0e1
- (void)controlWasActivated;	// 0x315de1b5
- (void)dealloc;	// 0x315de249
- (void)layoutSubcontrols;	// 0x315de855
- (void)orderOut;	// 0x315de205
- (void)setPlayer:(id)player;	// 0x315de455
- (void)tabControl:(id)control didSelectTabItem:(id)item;	// 0x315de161
- (void)tabControl:(id)control willSelectTabItem:(id)item;	// 0x315dddb1
- (void)tabControlDidChangeNumberOfTabItems:(id)tabControl;	// 0x315dddb5
@end

