/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRAsyncImageControl, NSDictionary, BRMarqueeTextControl;

__attribute__((visibility("hidden")))
@interface BRChapterGridItem : BRControl {
@private
	BRAsyncImageControl *_imageControl;	// 40 = 0x28
	BRMarqueeTextControl *_chapterTitleControl;	// 44 = 0x2c
	NSDictionary *_chapterInfo;	// 48 = 0x30
}
@property(retain) NSDictionary *chapterInfo;	// G=0x315dd85d; S=0x315dd9d9; converted property
- (id)init;	// 0x315dd985
// converted property getter: - (id)chapterInfo;	// 0x315dd85d
- (void)controlWasFocused;	// 0x315dd8b5
- (void)controlWasUnfocused;	// 0x315dd86d
- (void)dealloc;	// 0x315dd919
- (void)layoutSubcontrols;	// 0x315ddcc1
// converted property setter: - (void)setChapterInfo:(id)info;	// 0x315dd9d9
@end

