/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControl.h"

@class NSMutableDictionary, BRContextMenuControl, BRControllerStack;

@interface BRController : BRControl {
@private
	NSMutableDictionary *_labels;	// 40 = 0x28
	BRControllerStack *_stack;	// 44 = 0x2c
	BOOL _depthLimited;	// 48 = 0x30
	BRContextMenuControl *_contextMenu;	// 52 = 0x34
}
@property(assign) BOOL depthLimited;	// G=0x315bf6ad; S=0x315bf69d; converted property
@property(retain) BRControllerStack *stack;	// G=0x315a4601; S=0x3158e50d; converted property
+ (id)controllerWithContentControl:(id)contentControl;	// 0x315bf7d1
- (id)init;	// 0x3158e2e5
- (void)_contextMenuCancelItemSelected:(id)selected;	// 0x315bf6f5
- (void)addLabel:(id)label;	// 0x3159ca79
- (BOOL)brEventAction:(id)action;	// 0x315bf895
- (BOOL)canBeRemovedFromStack;	// 0x315bf699
- (int)contextMenuDimOption;	// 0x315bf6ed
- (BOOL)contextMenuIsVisible;	// 0x315bf77d
- (id)controlForContextMenuPositioning;	// 0x315bf6e1
- (id)controlForContextMenuStart;	// 0x315bf6e5
- (id)controlToDim;	// 0x315bf6e9
- (void)controlWasDeactivated;	// 0x315bfb4d
- (void)dealloc;	// 0x3159ac4d
// converted property getter: - (BOOL)depthLimited;	// 0x315bf6ad
- (id)description;	// 0x315aef2d
- (void)dismissContextMenu;	// 0x315bf73d
- (long)errorNumberForNoContent;	// 0x315bf6c1
- (BOOL)isLabelled:(id)labelled;	// 0x315a4611
- (BOOL)isNetworkDependent;	// 0x3158e591
- (BOOL)isValidAfterDataUpdate;	// 0x315bf6bd
- (id)providersForContextMenu;	// 0x315bf6dd
- (BOOL)recreateOnReselect;	// 0x315a8e35
- (void)removeLabel:(id)label;	// 0x315a7471
- (BOOL)requiresAuthentication:(id *)authentication mode:(int *)mode;	// 0x315bf6d9
// converted property setter: - (void)setDepthLimited:(BOOL)limited;	// 0x315bf69d
// converted property setter: - (void)setStack:(id)stack;	// 0x3158e50d
// converted property getter: - (id)stack;	// 0x315a4601
- (BOOL)topOfStack;	// 0x315bf7a5
- (id)transitionType;	// 0x315bf6c9
- (void)wasBuried;	// 0x315bf729
- (void)wasExhumed;	// 0x315bf6f1
- (void)wasPopped;	// 0x3159abf9
- (void)wasPushed;	// 0x3159a325
@end

