/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRImageControl.h"

@class NSTimer;
@protocol BRImageProxy;

__attribute__((visibility("hidden")))
@interface BRCoverArtImageLayer : BRImageControl {
@private
	id<BRImageProxy> _imageProxy;	// 64 = 0x40
	BOOL _deletterboxImage;	// 68 = 0x44
	BOOL _showsDefaultCoverArt;	// 69 = 0x45
	BOOL _showsBorder;	// 70 = 0x46
	NSTimer *_setCoverArtTimer;	// 72 = 0x48
}
@property(assign) BOOL deletterboxImage;	// G=0x3161d705; S=0x3161d795; converted property
@property(assign) BOOL showsBorder;	// G=0x3161d735; S=0x3161d805; converted property
@property(assign) BOOL showsDefaultCoverArt;	// G=0x3161d725; S=0x3161d715; converted property
- (id)init;	// 0x315b4411
- (void)_coverArtChanged:(id)changed;	// 0x315b7c79
- (void)_setCoverArtImage:(id)image;	// 0x315b476d
- (void)_setCoverArtImageWithDelay:(id)delay;	// 0x3161d745
- (void)_updateCoverArt;	// 0x315b4659
- (void)dealloc;	// 0x315b4d15
// converted property getter: - (BOOL)deletterboxImage;	// 0x3161d705
// converted property setter: - (void)setDeletterboxImage:(BOOL)image;	// 0x3161d795
- (void)setImageProxy:(id)proxy;	// 0x3161d7bd
// converted property setter: - (void)setShowsBorder:(BOOL)border;	// 0x3161d805
// converted property setter: - (void)setShowsDefaultCoverArt:(BOOL)art;	// 0x3161d715
// converted property getter: - (BOOL)showsBorder;	// 0x3161d735
// converted property getter: - (BOOL)showsDefaultCoverArt;	// 0x3161d725
@end

