/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRBaseMenuItemLayerPopulator.h"


@interface BRCollectionMenuItemPopulator : BRBaseMenuItemLayerPopulator {
}
+ (BOOL)canHandleObject:(id)object;	// 0x3161f661
- (id)_folderItemTypes;	// 0x3161ee55
- (id)allowedTypesPredicate;	// 0x3161f1a1
- (id)menuItem;	// 0x3161f329
- (float)menuItemHeightForObject:(id)object delegate:(id)delegate;	// 0x3161f23d
- (unsigned)numItemsInCollection:(id)collection hasOnlySongs:(BOOL *)songs;	// 0x3161eee5
- (id)numItemsString;	// 0x3161f68d
@end

