/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRBoxListControl, NSTimer;

@interface BRContextMenuControl : BRControl {
@private
	BRControl *_endPositionControl;	// 40 = 0x28
	BRControl *_startPositionControl;	// 44 = 0x2c
	BRControl *_dimControl;	// 48 = 0x30
	BRControl *_dimPanel;	// 52 = 0x34
	CGRect _endPositionControlFrame;	// 56 = 0x38
	CGRect _startPositionControlFrame;	// 72 = 0x48
	CGRect _dimControlFrame;	// 88 = 0x58
	BRBoxListControl *_contextBox;	// 104 = 0x68
	int _dimOption;	// 108 = 0x6c
	NSTimer *_autoDismissTimer;	// 112 = 0x70
}
@property(retain) BRControl *dimControl;	// G=0x315dfe41; S=0x315e00e9; converted property
@property(assign) int dimOption;	// G=0x315dfe51; S=0x315e00c9; converted property
@property(retain) BRControl *endPositionControl;	// G=0x315dfe31; S=0x315e0121; converted property
@property(assign) BOOL isVisible;	// G=0x315dffb1; S=0x315dffdd; converted property
@property(retain) id providers;	// G=0x315e0191; S=0x315e01b1; converted property
@property(retain) BRControl *startPositionControl;	// G=0x315dfe21; S=0x315e0159; converted property
- (id)init;	// 0x315e037d
- (void)_addAnimationsForDisplayState:(BOOL)displayState;	// 0x315e0c25
- (void)_autoDismissTimerFired:(id)fired;	// 0x315dff8d
- (CGRect)_dimControlFrame;	// 0x315e0495
- (void)_dissmissAnimationComplete;	// 0x315dff65
- (CGRect)_endPositionControlFrame;	// 0x315e0665
- (CGRect)_startPositionControlFrame;	// 0x315e057d
- (BOOL)brEventAction:(id)action;	// 0x315e0219
- (void)controlWasDeactivated;	// 0x315e02a1
- (void)dealloc;	// 0x315e02ed
// converted property getter: - (id)dimControl;	// 0x315dfe41
// converted property getter: - (int)dimOption;	// 0x315dfe51
// converted property getter: - (id)endPositionControl;	// 0x315dfe31
// converted property getter: - (BOOL)isVisible;	// 0x315dffb1
- (void)layoutSubcontrols;	// 0x315e074d
// converted property getter: - (id)providers;	// 0x315e0191
// converted property setter: - (void)setDimControl:(id)control;	// 0x315e00e9
// converted property setter: - (void)setDimOption:(int)option;	// 0x315e00c9
// converted property setter: - (void)setEndPositionControl:(id)control;	// 0x315e0121
// converted property setter: - (void)setIsVisible:(BOOL)visible;	// 0x315dffdd
- (void)setProvider:(id)provider;	// 0x315e01e5
// converted property setter: - (void)setProviders:(id)providers;	// 0x315e01b1
// converted property setter: - (void)setStartPositionControl:(id)control;	// 0x315e0159
// converted property getter: - (id)startPositionControl;	// 0x315dfe21
@end

