/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControl.h"

@class NSMutableArray;

@interface BRControllerStack : BRControl {
@private
	NSMutableArray *_stack;	// 40 = 0x28
	NSMutableArray *_transactions;	// 44 = 0x2c
	NSMutableArray *_currentStackPath;	// 48 = 0x30
	BOOL _processingTransactions;	// 52 = 0x34
	BOOL _dumpStack;	// 53 = 0x35
}
- (id)init;	// 0x3158d699
- (void)_addTransaction:(id)transaction;	// 0x3158e3ed
- (void)_databaseObjectModified:(id)modified;	// 0x315a03e5
- (void)_performDepthLimitedCullingForController:(id)controller;	// 0x315bfced
- (void)_processPopToClassTransaction:(id)classTransaction;	// 0x315bffd9
- (void)_processPopToLabelTransaction:(id)labelTransaction;	// 0x315bff19
- (void)_processPopToTransaction:(id)transaction;	// 0x315c00a9
- (void)_processPopTransaction:(id)transaction;	// 0x315a5fa1
- (void)_processPushTransaction:(id)transaction;	// 0x3158e42d
- (void)_processRemoveTransaction:(id)transaction;	// 0x315b7e21
- (void)_processReplaceAllTransaction:(id)transaction;	// 0x3159a365
- (void)_processReplaceControllersAboveLabelTransaction:(id)transaction;	// 0x315bfd71
- (void)_processSwapTransaction:(id)transaction;	// 0x315a5281
- (void)_processTransactions;	// 0x315c0c81
- (void)_refreshControllersNotification:(id)notification;	// 0x3159ab89
- (void)_setContent:(id)content direction:(int)direction oldTransition:(id)transition;	// 0x315c0771
- (void)_updateControllerValidity:(id)validity;	// 0x315bfb89
- (void)_updateControllersOnlyLegacy:(BOOL)legacy;	// 0x315bfba1
- (void)_updateStackPathForPoppingController:(id)poppingController;	// 0x3159a52d
- (void)_updateStackPathForPushingController:(id)pushingController;	// 0x3158e51d
- (BOOL)brEventAction:(id)action;	// 0x315a174d
- (id)controllers;	// 0x315c041d
- (id)controllersLabeled:(id)labeled;	// 0x315c0351
- (id)controllersOfClass:(Class)aClass;	// 0x315c0285
- (int)count;	// 0x315c0265
- (void)dealloc;	// 0x315c063d
- (void)layoutSubcontrols;	// 0x315c0bf5
- (id)peekController;	// 0x3159ca59
- (void)popController;	// 0x315a5f4d
- (void)popToController:(id)controller;	// 0x315c05d1
- (void)popToControllerOfClass:(Class)aClass;	// 0x315c0549
- (void)popToControllerWithLabel:(id)label;	// 0x315c04dd
- (void)pushController:(id)controller;	// 0x3158e339
- (void)removeController:(id)controller;	// 0x315b7db5
- (void)replaceAllControllersWithController:(id)controller;	// 0x31592039
- (void)replaceControllersAboveLabel:(id)label withController:(id)controller;	// 0x315c0449
- (id)rootController;	// 0x3159cad9
- (id)stackPathForController:(id)controller;	// 0x315b0261
- (void)swapController:(id)controller;	// 0x315a5185
@end

