/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRBaseMenuItemLayerPopulator.h"


@interface BRDigitalExtrasMenuItemPopulator : BRBaseMenuItemLayerPopulator {
}
+ (BOOL)canHandleObject:(id)object;	// 0x31658c9d
- (id)menuItem;	// 0x31658bb1
@end

