/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRWebControl.h"

@class NSMutableArray;
@protocol BRDigitalExtrasDelegate;

@interface BRDigitalExtrasWebControl : BRWebControl {
@private
	id<BRDigitalExtrasDelegate> _digitalExtrasDelegate;	// 144 = 0x90
}
@property(assign) id digitalExtrasDelegate;	// G=0x31658d21; S=0x31658d11; converted property
+ (void)initialize;	// 0x31658d71
+ (id)webControl;	// 0x31658d35
// converted property getter: - (id)digitalExtrasDelegate;	// 0x31658d21
- (void)loadDigitalExtra:(id)extra;	// 0x31658d31
// converted property setter: - (void)setDigitalExtrasDelegate:(id)delegate;	// 0x31658d11
@end

