/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



__attribute__((visibility("hidden")))
@interface BRDisplayModeRefreshRateSortDescriptor : NSSortDescriptor {
@private
	double _targetRefreshRate;	// 20 = 0x14
}
+ (id)sortDescriptorWithKey:(id)key ascending:(BOOL)ascending targetRefreshRate:(double)rate;	// 0x3164f5b9
- (id)initWithKey:(id)key ascending:(BOOL)ascending targetRefreshRate:(double)rate;	// 0x3164f4e9
- (int)compareObject:(id)object toObject:(id)object2;	// 0x3164f52d
@end

