/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRGridView, BRImage;

__attribute__((visibility("hidden")))
@interface BRDotArrayControl : BRControl {
@private
	long _dotCount;	// 40 = 0x28
	long _activeDot;	// 44 = 0x2c
	BRGridView *_dotGrid;	// 48 = 0x30
	BRImage *_dotOnImage;	// 52 = 0x34
	BRImage *_dotOffImage;	// 56 = 0x38
}
@property(assign) long activeDot;	// G=0x316850a9; S=0x31685155; converted property
@property(assign) long dotCount;	// G=0x31685099; S=0x316851a1; converted property
- (id)init;	// 0x316851d5
- (id)initWithDotCount:(long)dotCount;	// 0x31685259
// converted property getter: - (long)activeDot;	// 0x316850a9
- (void)dealloc;	// 0x316851ed
// converted property getter: - (long)dotCount;	// 0x31685099
- (float)grid:(id)grid heightForItemAtIndex:(long)index;	// 0x316854bd
- (id)grid:(id)grid itemAtIndex:(long)index;	// 0x316850d9
- (void)layoutSubcontrols;	// 0x316853d9
- (long)numberOfColumnsInGrid:(id)grid;	// 0x316850c9
- (long)numberOfItemsInGrid:(id)grid;	// 0x316850b9
// converted property setter: - (void)setActiveDot:(long)dot;	// 0x31685155
// converted property setter: - (void)setDotCount:(long)count;	// 0x316851a1
@end

