/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRFadeMaskLayer : BRControl {
@private
	float _topFadeHeight;	// 40 = 0x28
	float _bottomFadeHeight;	// 44 = 0x2c
	float _leftFadeWidth;	// 48 = 0x30
	float _rightFadeWidth;	// 52 = 0x34
	CGFunctionRef _shadingFunction;	// 56 = 0x38
}
@property(assign) float bottomFadeHeight;	// G=0x315b9c9d; S=0x315b9ad5; converted property
@property(assign) float leftFadeWidth;	// G=0x3161d899; S=0x315a1ca5; converted property
@property(assign) float rightFadeWidth;	// G=0x315a1d0d; S=0x315a1cd9; converted property
@property(assign) float topFadeHeight;	// G=0x315b9c8d; S=0x315b9b09; converted property
- (id)init;	// 0x31595385
// converted property getter: - (float)bottomFadeHeight;	// 0x315b9c9d
- (void)dealloc;	// 0x3159a201
- (void)drawInContext:(CGContextRef)context;	// 0x315a1d35
// converted property getter: - (float)leftFadeWidth;	// 0x3161d899
// converted property getter: - (float)rightFadeWidth;	// 0x315a1d0d
// converted property setter: - (void)setBottomFadeHeight:(float)height;	// 0x315b9ad5
- (void)setEnableMaskAnimation:(BOOL)animation;	// 0x315a1199
// converted property setter: - (void)setLeftFadeWidth:(float)width;	// 0x315a1ca5
// converted property setter: - (void)setRightFadeWidth:(float)width;	// 0x315a1cd9
// converted property setter: - (void)setTopFadeHeight:(float)height;	// 0x315b9b09
// converted property getter: - (float)topFadeHeight;	// 0x315b9c8d
@end

