/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRTransitionControl.h"

@class BRControl;

__attribute__((visibility("hidden")))
@interface BRFadeThroughBlackTransitionControl : BRTransitionControl {
@private
	BRControl *_shroud;	// 48 = 0x30
}
- (void)_addShroud;	// 0x31605a4d
- (void)_removeShroud;	// 0x31604995
- (void)_transitionInCompleted:(id)completed;	// 0x316046b1
- (void)_transitionOutCompleted:(id)completed;	// 0x31604635
- (void)_updateContentForTransitionState;	// 0x31604711
- (void)dealloc;	// 0x31604a61
- (void)layoutSubcontrols;	// 0x316051a9
- (void)setContent:(id)content;	// 0x31604a25
- (void)setTransitionedIn:(BOOL)anIn;	// 0x316049d1
@end

