/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRController.h"

@class NSMutableArray, NSString;
@protocol BRFullScreenPhotoControllerDelegate, BRPhotoProviderForCollection;

@interface BRFullScreenPhotoController : BRController {
@private
	long _startIndex;	// 56 = 0x38
	long _currentIndex;	// 60 = 0x3c
	id<BRPhotoProviderForCollection> _provider;	// 64 = 0x40
	id<BRFullScreenPhotoControllerDelegate> _delegate;	// 68 = 0x44
	BOOL _isNetworkDependent;	// 72 = 0x48
	BOOL _syncEventOccurred;	// 73 = 0x49
	NSMutableArray *_prefetchImageIDs;	// 76 = 0x4c
	NSString *_lastPrefetchAssetID;	// 80 = 0x50
	BOOL _initialLayoutCompleted;	// 84 = 0x54
	int _startTouchXPosition;	// 88 = 0x58
	float _curTouchOffset;	// 92 = 0x5c
	BOOL _imagePrefetchDisabled;	// 96 = 0x60
	long _numPrefetchInProgress;	// 100 = 0x64
}
@property(readonly, assign) long currentIndex;	// G=0x315ccf69; converted property
@property(assign) BOOL imagePrefetchDisabled;	// G=0x315ccfb1; S=0x315ccf99; converted property
@property(assign) BOOL isNetworkDependent;	// G=0x315ccf89; S=0x315ccf79; converted property
@property(readonly, assign, nonatomic) id<BRPhotoProviderForCollection> provider;	// G=0x315ccfc1; @synthesize=_provider
+ (id)fullScreenPhotoControllerForProvider:(id)provider startIndex:(long)index;	// 0x315cd845
- (id)initWithProvider:(id)provider startIndex:(long)index;	// 0x315cd749
- (void)_nextSlide;	// 0x315cd4e9
- (void)_nextSlideWithTransition;	// 0x315cd479
- (void)_playerStateChanged:(id)changed;	// 0x315cd05d
- (void)_prefetchImageWritten:(id)written;	// 0x315ccfd1
- (void)_prefetchNextImage;	// 0x315cd0e5
- (void)_previousSlide;	// 0x315cd4b1
- (void)_previousSlideWithTransition;	// 0x315cd441
- (void)_setImageLayerTargetBounds;	// 0x315cd88d
- (void)_startSlideshow;	// 0x315cd349
- (long)_switchToImageControlForIndex:(long)index usingSwipeTransition:(BOOL)transition;	// 0x315cdd11
- (BOOL)brEventAction:(id)action;	// 0x315cdaa5
- (void)controlWasActivated;	// 0x315cd635
- (void)controlWasDeactivated;	// 0x315cd5e1
// converted property getter: - (long)currentIndex;	// 0x315ccf69
- (void)dealloc;	// 0x315cd6a1
// converted property getter: - (BOOL)imagePrefetchDisabled;	// 0x315ccfb1
// converted property getter: - (BOOL)isNetworkDependent;	// 0x315ccf89
- (BOOL)isValidAfterDataUpdate;	// 0x315cd591
- (void)layoutSubcontrols;	// 0x315cd9c1
// declared property getter: - (id)provider;	// 0x315ccfc1
- (void)reload;	// 0x315cd521
- (void)setControllerDelegate:(id)delegate;	// 0x315cd559
// converted property setter: - (void)setImagePrefetchDisabled:(BOOL)disabled;	// 0x315ccf99
// converted property setter: - (void)setIsNetworkDependent:(BOOL)dependent;	// 0x315ccf79
@end

