/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class NSMutableArray, BRCursorControl;

@interface BRGridView : BRControl {
@private
	int _mode;	// 40 = 0x28
	BRControl *_requester;	// 44 = 0x2c
	NSRange _range;	// 48 = 0x30
	float _lastGapHeight;	// 56 = 0x38
	double _heightToRange;	// 60 = 0x3c
	double _controlHeight;	// 68 = 0x44
	float _columWidth;	// 76 = 0x4c
	float _horizontalGap;	// 80 = 0x50
	float _verticalGap;	// 84 = 0x54
	float _leftMargin;	// 88 = 0x58
	float _rightMargin;	// 92 = 0x5c
	float _bottomMargin;	// 96 = 0x60
	float _bottomMarginFactor;	// 100 = 0x64
	float _topMargin;	// 104 = 0x68
	float _topMarginFactor;	// 108 = 0x6c
	BOOL _wrapsNavigation;	// 112 = 0x70
	id _dataSource;	// 116 = 0x74
	id _delegate;	// 120 = 0x78
	long _defaultFocusIndex;	// 124 = 0x7c
	BRCursorControl *_trackingCursor;	// 128 = 0x80
	BOOL _needsReload;	// 132 = 0x84
	NSMutableArray *_editEventQueue;	// 136 = 0x88
}
@property(retain) id cursor;	// G=0x315e70e5; S=0x315e7db5; converted property
@property(retain) id dataSource;	// G=0x315e7005; S=0x315e8645; converted property
@property(assign) id delegate;	// G=0x315e7025; S=0x315e7015; converted property
@property(assign) float horizontalGap;	// G=0x315e7045; S=0x315e85b5; converted property
@property(assign) float leftMargin;	// G=0x315e7065; S=0x315e84ed; converted property
@property(assign) float rightMargin;	// G=0x315e7075; S=0x315e849d; converted property
@property(assign) long selection;	// G=0x315e861d; S=0x315e8631; converted property
@property(assign) float verticalGap;	// G=0x315e7055; S=0x315e8569; converted property
@property(assign) BOOL wrapsNavigation;	// G=0x315e70ad; S=0x315e709d; converted property
+ (id)_jitterPositionAnimation;	// 0x315e98cd
+ (id)_jitterTransformAnimation;	// 0x315e9635
- (id)init;	// 0x315e86e9
- (void)_animationDidStartInDisplayMode:(id)_animation;	// 0x315e70f5
- (void)_animationDidStartInEditModeMode:(id)_animation;	// 0x315e70f9
- (void)_animationDidStopInDisplayMode:(id)_animation finished:(BOOL)finished;	// 0x315e70fd
- (void)_animationDidStopInEditMode:(id)_animation finished:(BOOL)finished;	// 0x315e76f5
- (id)_controlAtIndex:(long)index controls:(id)controls;	// 0x315e7635
- (long)_controlsInHeight:(double)height startingAt:(long)at actualHeight:(double *)height3;	// 0x315e9e75
- (long)_controlsInHeightBackwards:(double)heightBackwards startingAt:(long)at actualHeight:(double *)height;	// 0x315e9f59
- (id)_controlsInRange:(NSRange)range;	// 0x315ea7ad
- (id)_createControlsInRange:(NSRange)range;	// 0x315e9589
- (void)_focusChanged:(id)changed;	// 0x315e7101
- (CGRect)_frameForControlAtIndex:(long)index controls:(id)controls;	// 0x315ea51d
- (CGRect)_frameForControlAtIndex:(long)index rowFrame:(CGRect)frame controls:(id)controls;	// 0x315e90bd
- (void)_frameRowInRange:(NSRange)range rowFrame:(CGRect)frame controls:(id)controls;	// 0x315ea675
- (BOOL)_handleEventInDisplayMode:(id)displayMode;	// 0x315e7a01
- (BOOL)_handleEventInEditMode:(id)editMode;	// 0x315e77e1
- (float)_heightOfControlAtIndex:(long)index controls:(id)controls;	// 0x315e9379
- (double)_heightOfRowsInRange:(NSRange)range includeVerticalGap:(BOOL)gap controls:(id)controls;	// 0x315e9dbd
- (double)_heightToRange;	// 0x315e9cdd
- (float)_horizontalGapValue;	// 0x315e93e9
- (long)_indexOfFocusedControl;	// 0x315e7691
- (void)_layoutSubcontrols;	// 0x315ea01d
- (float)_positionOfColumn:(long)column inRowWidth:(float)rowWidth cellWidth:(float *)width;	// 0x315e9491
- (void)_restorePersistentSavedSelection;	// 0x315e72b5
- (float)_rowHeightForControlsInRange:(NSRange)range controls:(id)controls;	// 0x315ea6fd
- (void)_sceneBoundsChanged:(id)changed;	// 0x315e716d
- (id)_setControlRange:(NSRange)range withHeightToRange:(double)range2;	// 0x315eadb9
- (BOOL)_setMode:(int)mode;	// 0x315e7c45
- (void)_setSelectedItemJiggling:(BOOL)jiggling;	// 0x315e74e5
- (BOOL)_swapControlAtIndex:(long)index withControlAtIndex:(long)index2;	// 0x315e88ad
- (id)_swapPositionAnimationFromIndex:(long)index toIndex:(long)index2;	// 0x315e7421
- (double)_totalHeight;	// 0x315e9bd9
- (void)_updatePersistentSavedSelection;	// 0x315e7201
- (float)_verticalGapValue;	// 0x315e943d
- (void)animationDidStart:(id)animation;	// 0x315e8265
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x315e822d
- (BOOL)brEventAction:(id)action;	// 0x315e8f95
- (BOOL)controlAcceptsFocusAtIndex:(long)index;	// 0x315e7ded
- (CGRect)controlFocusFrameAtIndex:(long)index;	// 0x315e8bdd
- (id)controlForPoint:(CGPoint)point;	// 0x315e8ee9
- (CGRect)controlFrameAtIndex:(long)index;	// 0x315e8c91
- (void)controlWasActivated;	// 0x315e834d
- (void)controlWasDeactivated;	// 0x315e8311
// converted property getter: - (id)cursor;	// 0x315e70e5
- (long)dataCount;	// 0x315e85f5
// converted property getter: - (id)dataSource;	// 0x315e7005
- (void)dealloc;	// 0x315e8665
// converted property getter: - (id)delegate;	// 0x315e7025
- (void)didFocusItemAtIndex:(long)index;	// 0x315e7f65
- (BOOL)didPlayItemAtIndex:(long)index;	// 0x315e7e2d
- (BOOL)didSelectItemAtIndex:(long)index;	// 0x315e7e7d
- (void)didUnFocusItemAtIndex:(long)index;	// 0x315e7ecd
- (void)focusControlAtIndex:(long)index;	// 0x315eaca1
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x315eaa11
- (void)grid:(id)grid didFocusItemAtIndex:(long)index;	// 0x315e70d5
- (void)grid:(id)grid didSelectItemAtIndex:(long)index;	// 0x315e70e1
- (void)grid:(id)grid didUnFocusItemAtIndex:(long)index;	// 0x315e70dd
- (float)grid:(id)grid heightForItemAtIndex:(long)index;	// 0x315e70c9
- (id)grid:(id)grid itemAtIndex:(long)index;	// 0x315e70c5
- (void)grid:(id)grid willDisplayItemAtIndex:(long)index;	// 0x315e70cd
- (long)grid:(id)grid willFocusItemAtIndex:(long)index;	// 0x315e70d1
- (void)grid:(id)grid willUnFocusItemAtIndex:(long)index;	// 0x315e70d9
- (float)heightForItemAtIndex:(long)index;	// 0x315e804d
- (float)heightOfControlAtIndex:(long)index;	// 0x315e842d
- (float)heightToMaximum:(float)maximum;	// 0x315e9a51
// converted property getter: - (float)horizontalGap;	// 0x315e7045
- (long)indexForItemID:(id)itemID;	// 0x315e809d
- (int)indexOfControlAtPoint:(CGPoint)point;	// 0x315e9175
- (id)initialFocus;	// 0x315eac09
- (id)itemAtIndex:(long)index;	// 0x315e813d
- (id)itemIDAtIndex:(long)index;	// 0x315e80f1
- (void)layoutSubcontrols;	// 0x315e82e9
// converted property getter: - (float)leftMargin;	// 0x315e7065
- (long)numberOfColumns;	// 0x315e8189
- (long)numberOfColumnsInGrid:(id)grid;	// 0x315e70c1
- (long)numberOfItems;	// 0x315e81d1
- (long)numberOfItemsInGrid:(id)grid;	// 0x315e70bd
- (float)positionOfColumn:(long)column;	// 0x315e8e51
- (void)reload;	// 0x315e9b15
- (void)reloadItemAtIndex:(long)index;	// 0x315ea98d
- (void)reloadItemsAtIndexes:(id)indexes;	// 0x315e83c9
// converted property getter: - (float)rightMargin;	// 0x315e7075
- (long)rowCount;	// 0x315e8845
- (void)scrollingCompleted;	// 0x315e8299
- (void)selectItemAtIndex:(long)index;	// 0x315e8219
- (id)selectedObject;	// 0x315e8609
// converted property getter: - (long)selection;	// 0x315e861d
- (void)setBottomMargin:(float)margin;	// 0x315e8ddd
- (void)setColumnWidth:(float)width;	// 0x315e7035
// converted property setter: - (void)setCursor:(id)cursor;	// 0x315e7db5
// converted property setter: - (void)setDataSource:(id)source;	// 0x315e8645
- (void)setDefaultFocusWithPoint:(CGPoint)point;	// 0x315e8ead
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x315e7015
// converted property setter: - (void)setHorizontalGap:(float)gap;	// 0x315e85b5
// converted property setter: - (void)setLeftMargin:(float)margin;	// 0x315e84ed
- (void)setNeedsReload;	// 0x315e8389
// converted property setter: - (void)setRightMargin:(float)margin;	// 0x315e849d
// converted property setter: - (void)setSelection:(long)selection;	// 0x315e8631
- (void)setTopMargin:(float)margin;	// 0x315e8d69
// converted property setter: - (void)setVerticalGap:(float)gap;	// 0x315e8569
- (void)setVerticalMargins:(float)margins;	// 0x315e853d
// converted property setter: - (void)setWrapsNavigation:(BOOL)navigation;	// 0x315e709d
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315e8fd5
// converted property getter: - (float)verticalGap;	// 0x315e7055
- (id)visibleControlAtIndex:(long)index;	// 0x315ea949
- (id)visibleControlsWithRange:(NSRange *)range;	// 0x315e845d
- (NSRange)visibleRange;	// 0x315e7085
- (void)visibleScrollRectChanged;	// 0x315e82fd
- (void)willDisplayItemAtIndex:(long)index;	// 0x315e8001
- (long)willFocusItemAtIndex:(long)index;	// 0x315e7fb1
- (void)willUnFocusItemAtIndex:(long)index;	// 0x315e7f19
// converted property getter: - (BOOL)wrapsNavigation;	// 0x315e70ad
@end

