/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRHDCPMonitor : NSObject {
}
+ (BOOL)protectedContentPlayable;	// 0x316664fd
+ (void)startMonitoring;	// 0x316664f9
@end

