/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BREvent.h"


@interface BRHIDEvent : BREvent {
@private
	unsigned short _page;	// 30 = 0x1e
	unsigned short _usage;	// 32 = 0x20
	unsigned long long _extendedSignature;	// 36 = 0x24
}
@property(readonly, assign) unsigned long long extendedSignature;	// G=0x315d578d; converted property
@property(readonly, assign) unsigned short page;	// G=0x315d576d; converted property
@property(readonly, assign) unsigned short usage;	// G=0x315d577d; converted property
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value;	// 0x315d5939
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value atTime:(double)time;	// 0x315d597d
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature;	// 0x315d59c9
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature atTime:(double)time;	// 0x315d5a15
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value;	// 0x315d58fd
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value atTime:(double)time;	// 0x315d5881
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature;	// 0x315d58b9
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature atTime:(double)time;	// 0x315d5b79
- (id)description;	// 0x315d5a69
// converted property getter: - (unsigned long long)extendedSignature;	// 0x315d578d
- (BOOL)isEqual:(id)equal;	// 0x315d579d
// converted property getter: - (unsigned short)page;	// 0x315d576d
// converted property getter: - (unsigned short)usage;	// 0x315d577d
@end

