/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class BRAsyncTaskContext, NSMutableArray;
@protocol BRProvider;

@interface BRImageLoader : NSObject {
@private
	long _queueSize;	// 4 = 0x4
	NSMutableArray *_imageQueue;	// 8 = 0x8
	NSMutableArray *_candidateImages;	// 12 = 0xc
	NSMutableArray *_pendingImages;	// 16 = 0x10
	id<BRProvider> _provider;	// 20 = 0x14
	BOOL _randomize;	// 24 = 0x18
	long _serialIndex;	// 28 = 0x1c
	long _imageArrayIndex;	// 32 = 0x20
	long _segmentLength;	// 36 = 0x24
	long _segmentCount;	// 40 = 0x28
	int _fillStrategy;	// 44 = 0x2c
	long _failedLoadCount;	// 48 = 0x30
	BRAsyncTaskContext *_taskContext;	// 52 = 0x34
}
@property(assign) int fillStrategy;	// G=0x3163fbc1; S=0x315ac5b9; converted property
@property(assign) long queueSize;	// G=0x3163fbd1; S=0x315ac6fd; converted property
@property(assign) BOOL randomize;	// G=0x3163fbe1; S=0x315ac7f9; converted property
@property(assign) long segmentCount;	// G=0x3163fbb1; S=0x3163fd71; converted property
- (id)init;	// 0x315ac471
- (void)_abandonArtwork:(id)artwork;	// 0x31640211
- (void)_abandonPendingImageProxyForImageWithID:(id)anId;	// 0x31640a65
- (void)_enqueueImage:(id)image;	// 0x31640455
- (BOOL)_isQueuePrimed;	// 0x315aca75
- (id)_pendingImageDictionaryForImageID:(id)imageID;	// 0x3163fdb9
- (void)_prepareImageForQueue:(id)queue withID:(id)anId;	// 0x3163fed5
- (void)_primeQueue;	// 0x315ac909
- (void)_promoteCandidateImageProxy:(id)proxy toPendingImageProxyForImageWithID:(id)anId;	// 0x316402e9
- (void)_providerUpdated:(id)updated;	// 0x3163fbf9
- (id)_pullNextImageProxy;	// 0x3163fc41
- (id)_pullNextImageProxyRandomly;	// 0x316407c5
- (void)_setupForNewProvider;	// 0x3164063d
- (void)_updateArtwork:(id)artwork;	// 0x316408f9
- (void)dealloc;	// 0x315ad489
// converted property getter: - (int)fillStrategy;	// 0x3163fbc1
- (id)finalFormForImage:(id)image;	// 0x3163fbf1
- (void)flushQueue;	// 0x315ac809
- (long)imageCount;	// 0x3163fd1d
- (BOOL)isImageFinalForm:(id)form;	// 0x3163fbf5
- (id)nextImage;	// 0x315ad6d9
- (BOOL)queueReady;	// 0x315acc7d
// converted property getter: - (long)queueSize;	// 0x3163fbd1
// converted property getter: - (BOOL)randomize;	// 0x3163fbe1
// converted property getter: - (long)segmentCount;	// 0x3163fbb1
// converted property setter: - (void)setFillStrategy:(int)strategy;	// 0x315ac5b9
- (void)setImageProxies:(id)proxies;	// 0x3163fd3d
- (void)setProvider:(id)provider;	// 0x31640075
// converted property setter: - (void)setQueueSize:(long)size;	// 0x315ac6fd
// converted property setter: - (void)setRandomize:(BOOL)randomize;	// 0x315ac7f9
// converted property setter: - (void)setSegmentCount:(long)count;	// 0x3163fd71
@end

