/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRImageProxy.h"

@class NSString;

@interface BRInternetRadioImageProxy : NSObject <BRImageProxy> {
@private
	NSString *_category;	// 4 = 0x4
}
- (id)initWithCategory:(id)category;	// 0x316633a5
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x316631f5
- (void)dealloc;	// 0x3166335d
- (id)defaultImageForImageSize:(int)imageSize;	// 0x31663209
- (id)imageForImageSize:(int)imageSize;	// 0x31663241
- (id)imageIDForImageSize:(int)imageSize;	// 0x31663325
- (id)object;	// 0x316631f9
- (BOOL)supportsImageForImageSize:(int)imageSize;	// 0x316631e1
@end

