/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSelectionHandler.h"

@class NSInvocation;

@interface BRInvocationSelectionHandler : NSObject <BRSelectionHandler> {
@private
	NSInvocation *_invocation;	// 4 = 0x4
	BOOL _useInvocationReturnValue;	// 8 = 0x8
}
@property(readonly, retain) NSInvocation *invocation;	// G=0x316235e1; converted property
@property(assign) BOOL useInvocationReturnValue;	// G=0x31623601; S=0x316235f1; converted property
+ (id)handlerWithInvocation:(id)invocation;	// 0x31623759
+ (id)handlerWithTarget:(id)target selector:(SEL)selector;	// 0x316236d5
- (id)initWithInvocation:(id)invocation;	// 0x316237e5
- (void)dealloc;	// 0x3162379d
- (BOOL)handleSelectionForControl:(id)control;	// 0x31623611
// converted property getter: - (id)invocation;	// 0x316235e1
// converted property setter: - (void)setUseInvocationReturnValue:(BOOL)value;	// 0x316235f1
// converted property getter: - (BOOL)useInvocationReturnValue;	// 0x31623601
@end

