/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSMutableArray;

@interface BRKeyValueObservingRegistry : NSObject {
@private
	NSMutableArray *_observationEntries;	// 4 = 0x4
}
- (id)init;	// 0x3168a0cd
- (void)_addObservationEntry:(id)entry options:(unsigned)options;	// 0x3168a1bd
- (id)_observationEntryFromContext:(const void *)context;	// 0x3168a3b9
- (void)_removeObservationEntriesAtIndexes:(id)indexes;	// 0x3168a139
- (void)dealloc;	// 0x3168a079
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void *)context;	// 0x31689da1
- (void)registerObserver:(id)observer ofObject:(id)object forKeyPath:(id)keyPath handler:(id)handler;	// 0x3168a045
- (void)registerObserver:(id)observer ofObject:(id)object forKeyPath:(id)keyPath options:(unsigned)options handler:(id)handler;	// 0x3168a22d
- (void)unregisterAll;	// 0x31689e2d
- (void)unregisterObserver:(id)observer;	// 0x31689fb5
- (void)unregisterObserversOfObject:(id)object;	// 0x31689f49
- (void)unregisterObserversOfObject:(id)object forKeyPath:(id)keyPath;	// 0x31689e91
@end

