/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRKeyboardRomanSquare.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BRKeyboardCandidates : BRKeyboardRomanSquare {
@private
	NSArray *_rawKeyboardDataStrings;	// 40 = 0x28
}
- (id)_keyboardDataFileName;	// 0x315fbc4d
- (id)_mainKeyRowWithKeys:(id)keys index:(int)index;	// 0x315fb6b5
- (float)_mainKeysVerticalSpacing;	// 0x315fb6b1
- (int)_numberOfColumnsForMainKeyRowIndex:(int)mainKeyRowIndex;	// 0x315fb741
- (int)_numberOfMainKeyRows;	// 0x315fb7bd
- (float)_preferredGlyphHeight:(id)height;	// 0x315fb6a5
- (id)_rawKeyboardData;	// 0x315fbc65
- (int)_scrollDirectionForMainKeys;	// 0x315fb6ad
- (id)actionKeyRows;	// 0x315fb69d
- (id)actionKeysContainer;	// 0x315fb6a1
- (id)attributesForTextFieldLabel;	// 0x315fb68d
- (id)bottomRow;	// 0x315fb7e5
- (void)dealloc;	// 0x315fbc05
- (id)mainKeysContainer;	// 0x315fbb21
- (id)name;	// 0x315fb691
- (void)setRawKeyboardDataStrings:(id)strings;	// 0x315fb9f5
- (void)updateMainKeysContainer:(id)container;	// 0x315fb809
@end

