/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRKeyboardRomanSquare.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseSquareHiragana : BRKeyboardRomanSquare {
}
- (CGSize)_actionKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x315fdf51
- (float)_candidatesBackgroundBaseGap:(id)gap resolutionScale:(float)scale;	// 0x315fddf5
- (CGSize)_candidatesBackgroundSize:(id)size resolutionScale:(float)scale;	// 0x315fde11
- (id)_keyRows;	// 0x315fd94d
- (id)_mainKeyRowPlane;	// 0x315fd6e5
- (id)_mainKeyRowWithKeys:(id)keys index:(int)index;	// 0x315fd73d
- (CGSize)_mainKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x315fdfa9
- (float)_mainKeysVerticalSpacing;	// 0x315fd6d9
- (CGSize)_minTextEntryControlSize:(id)size resolutionScale:(float)scale;	// 0x315fde6d
- (int)_numberOfColumnsForMainKeyRowIndex:(int)mainKeyRowIndex;	// 0x315fd6c9
- (int)_numberOfMainKeyRows;	// 0x315fd6c5
- (int)_scrollDirectionForMainKeys;	// 0x315fd6d5
- (long)_startingIndexOfActionKeysInKeyRowData;	// 0x315fd6e1
- (float)_topMostUIElementGap:(id)gap resolutionScale:(float)scale;	// 0x315fde51
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x315fdab5
- (id)actionKeysContainer;	// 0x315fdc89
- (CGRect)candidatesBackgroundFrame:(id)frame resolutionScale:(float)scale;	// 0x315fdd49
- (id)name;	// 0x315fd6b9
- (void)setFocusToDefaultGlyph;	// 0x315fd8f5
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x315fd79d
@end

