/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRKeyboardRomanSquare.h"
#import "BackRow-Structs.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseRomanSquare : BRKeyboardRomanSquare {
}
- (CGSize)_actionKeysContainerSize:(id)size resolutionScale:(float)scale;	// 0x315fd32d
- (CGSize)_minTextEntryControlSize:(id)size resolutionScale:(float)scale;	// 0x315fd3a1
- (long)_startingIndexOfActionKeysInKeyRowData;	// 0x315fcfd9
- (float)_topMostUIElementGap:(id)gap resolutionScale:(float)scale;	// 0x315fd385
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x315fcfdd
- (id)actionKeysContainer;	// 0x315fd26d
- (id)name;	// 0x315fcfc9
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x315fd111
@end

