/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRPanelControl.h"
#import "BackRow-Structs.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanWebKeyContainer : BRPanelControl {
}
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x31657ac9
@end

