/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRKeyboardJapaneseFullRoman.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseFullSymbols : BRKeyboardJapaneseFullRoman {
}
- (id)_keyboardDataFileName;	// 0x315fcfa5
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x315fcedd
- (id)name;	// 0x315fcd71
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)defaultSwitchKeyboardGlyph;	// 0x315fcd81
@end

