/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSMutableDictionary;

@interface BRMappingDictionary : NSObject {
@private
	NSMutableDictionary *_info;	// 4 = 0x4
}
- (id)init;	// 0x315a245d
- (long)count;	// 0x316465c1
- (void)dealloc;	// 0x316465f5
- (id)keyEnumerator;	// 0x315a2cf5
- (id)objectEnumerator;	// 0x316465a1
- (id)objectForKey:(id)key;	// 0x315a25e9
- (void)setObject:(id)object forKey:(id)key;	// 0x315a24b9
- (void)setValue:(id)value forKey:(id)key;	// 0x316465e1
- (void)setValueTransformer:(id)transformer forKey:(id)key;	// 0x315a24d9
- (id)transformedValueForKey:(id)key forObject:(id)object;	// 0x315a2d5d
- (id)valueForKey:(id)key;	// 0x315a2db9
- (id)valueTransformerForKey:(id)key;	// 0x315a2dcd
@end

