/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class NSTimer, BRFadeMaskLayer, BRScrollingTextPlane;
@protocol BRMarqueeScrollingDelegate;

@interface BRMarqueeTextControl : BRControl {
@private
	BRScrollingTextPlane *_plane;	// 40 = 0x28
	BRControl *_leftFade;	// 44 = 0x2c
	BRControl *_rightFade;	// 48 = 0x30
	BRFadeMaskLayer *_mask;	// 52 = 0x34
	NSTimer *_scrollTimer;	// 56 = 0x38
	NSTimer *_fadeMaskTimer;	// 60 = 0x3c
	float _maskRemovalTime;	// 64 = 0x40
	float _scrollPosition;	// 68 = 0x44
	BOOL _autoScrolls;	// 72 = 0x48
	BOOL _crossfadeEnabled;	// 73 = 0x49
	BOOL _crossfading;	// 74 = 0x4a
	BOOL _useAlphaFadeMask;	// 75 = 0x4b
	id<BRMarqueeScrollingDelegate> _scrollingDelegate;	// 76 = 0x4c
}
@property(retain) id attributedString;	// G=0x315ed0ad; S=0x315ed0cd; converted property
@property(assign) BOOL autoScrolls;	// G=0x315ecc15; S=0x315ed039; converted property
@property(assign) BOOL crossfadeEnabled;	// G=0x315ecc3d; S=0x315ecc25; converted property
@property(assign) float scrollPosition;	// G=0x315ecc4d; S=0x315ed005; converted property
@property(assign) id scrollingDelegate;	// G=0x315ecc5d; S=0x315ecc6d; converted property
@property(assign) BOOL useAlphaFadeMask;	// G=0x315ecc8d; S=0x315ecc7d; converted property
- (id)init;	// 0x315ed571
- (BOOL)_autoscrollInProgress;	// 0x315ecc9d
- (void)_beginScroll:(id)scroll;	// 0x315edced
- (void)_clearFadeMaskTimer;	// 0x315ecde1
- (void)_clearScrollTimer;	// 0x315ece25
- (void)_realignCenteredTextToLeftJustified;	// 0x315eceed
- (void)_removeFadeMask:(id)mask;	// 0x315ece69
- (void)_resetScrollTimer;	// 0x315ed671
- (void)_scrollDidStart:(id)_scroll;	// 0x315ecd61
- (void)_scrollDidStop:(id)_scroll;	// 0x315ecccd
- (void)_scrollDidStop:(id)_scroll finished:(BOOL)finished;	// 0x315ecd15
- (void)_updateEdgeMaskingIfScrollingNeeded:(BOOL)needed;	// 0x315ed749
// converted property getter: - (id)attributedString;	// 0x315ed0ad
// converted property getter: - (BOOL)autoScrolls;	// 0x315ecc15
- (void)controlWasActivated;	// 0x315ed359
- (void)controlWasDeactivated;	// 0x315ed395
// converted property getter: - (BOOL)crossfadeEnabled;	// 0x315ecc3d
- (void)dealloc;	// 0x315ed4f1
- (void)layoutSubcontrols;	// 0x315ee149
- (float)maxScrollPosition;	// 0x315edb35
- (BOOL)needsScrollingInBounds:(CGRect)bounds;	// 0x315ed9fd
- (CGSize)pixelBounds;	// 0x315edb11
- (id)preferredActionForKey:(id)key;	// 0x315ed405
- (CGSize)renderedSize;	// 0x315eda95
// converted property getter: - (float)scrollPosition;	// 0x315ecc4d
// converted property getter: - (id)scrollingDelegate;	// 0x315ecc5d
// converted property setter: - (void)setAttributedString:(id)string;	// 0x315ed0cd
// converted property setter: - (void)setAutoScrolls:(BOOL)scrolls;	// 0x315ed039
// converted property setter: - (void)setCrossfadeEnabled:(BOOL)enabled;	// 0x315ecc25
// converted property setter: - (void)setScrollPosition:(float)position;	// 0x315ed005
// converted property setter: - (void)setScrollingDelegate:(id)delegate;	// 0x315ecc6d
- (void)setText:(id)text withAttributes:(id)attributes;	// 0x315ed1f1
// converted property setter: - (void)setUseAlphaFadeMask:(BOOL)mask;	// 0x315ecc7d
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315ed999
// converted property getter: - (BOOL)useAlphaFadeMask;	// 0x315ecc8d
@end

