/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRMediaShelfControl.h"


@interface BRMainMenuShelfControl : BRMediaShelfControl {
}
- (id)init;	// 0x316611c9
- (void)controlWasDeactivated;	// 0x3166118d
@end

