/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImageControl;

@interface BRMainMenuImageControl : BRControl {
@private
	BRImageControl *_content;	// 40 = 0x28
}
- (BOOL)acceptsFocus;	// 0x31663e61
- (void)dealloc;	// 0x31663ef5
- (void)layoutSubcontrols;	// 0x31663f3d
- (void)setImage:(id)image;	// 0x31663e65
@end

