/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImageControl, BRListView, BRTextControl, BRScrollControl;

@interface BRMenuView : BRControl {
@private
	int _alignment;	// 40 = 0x28
	float _verticalSpacer;	// 44 = 0x2c
	BRImageControl *_titleImage;	// 48 = 0x30
	float _titleImageVerticalOffset;	// 52 = 0x34
	BRTextControl *_title;	// 56 = 0x38
	BRTextControl *_description;	// 60 = 0x3c
	BRListView *_list;	// 64 = 0x40
	BRScrollControl *_scroller;	// 68 = 0x44
}
@property(assign) int alignment;	// G=0x31676625; S=0x3167688d; converted property
@property(retain) BRTextControl *description;	// G=0x316766a1; S=0x316766d1; converted property
@property(readonly, retain) BRListView *list;	// G=0x31676645; converted property
@property(assign) CGRect listFrame;	// G=0x31676c3d; S=0x31676655; converted property
@property(retain) BRTextControl *title;	// G=0x316766e9; S=0x31676719; converted property
- (id)init;	// 0x31676945
// converted property getter: - (int)alignment;	// 0x31676625
- (void)dealloc;	// 0x316768b5
// converted property getter: - (id)description;	// 0x316766a1
- (void)layoutSubcontrols;	// 0x31676c61
// converted property getter: - (id)list;	// 0x31676645
// converted property getter: - (CGRect)listFrame;	// 0x31676c3d
// converted property setter: - (void)setAlignment:(int)alignment;	// 0x3167688d
// converted property setter: - (void)setDescription:(id)description;	// 0x316766d1
- (void)setDescription:(id)description withAttributes:(id)attributes;	// 0x31676b09
// converted property setter: - (void)setListFrame:(CGRect)frame;	// 0x31676655
// converted property setter: - (void)setTitle:(id)title;	// 0x31676719
- (void)setTitle:(id)title withAttributes:(id)attributes;	// 0x31676731
- (void)setTitleImage:(id)image withVerticalOffset:(float)verticalOffset;	// 0x316767f1
- (void)setVerticalSpacer:(float)spacer;	// 0x31676635
// converted property getter: - (id)title;	// 0x316766e9
@end

