/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRMetadataDetailControl : BRControl {
}
- (void)addDetails:(id)details withLabel:(id)label;	// 0x315a3669
- (void)layoutSubcontrols;	// 0x315e5215
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315e532d
@end

