/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRVideoCacheManagerDelegate.h"
#import "BRController.h"

@class BRMediaPlayer, BRTransportControl, BRMediaPlayerEventHandler, NSTimer, BRTextControl, BRDescriptionOverlayControl, BRResumeMenuControl;

__attribute__((visibility("hidden")))
@interface BRMediaPlayerController : BRController <BRVideoCacheManagerDelegate> {
@private
	long _state;	// 56 = 0x38
	BRControl *_content;	// 60 = 0x3c
	BRControl *_audioVisualizer;	// 64 = 0x40
	BRMediaPlayer *_player;	// 68 = 0x44
	BRMediaPlayerEventHandler *_eventHandler;	// 72 = 0x48
	BRResumeMenuControl *_resumeMenu;	// 76 = 0x4c
	BRTransportControl *_transport;	// 80 = 0x50
	BRDescriptionOverlayControl *_descriptionOverlay;	// 84 = 0x54
	BRTextControl *_explanatoryTextControl;	// 88 = 0x58
	id _delegate;	// 92 = 0x5c
	id _transitionAnimationDelegate;	// 96 = 0x60
	NSTimer *_suppressBackgroundProcessTimer;	// 100 = 0x64
	NSTimer *_explanatoryTextFadeTimer;	// 104 = 0x68
	NSTimer *_readyToPlayTimer;	// 108 = 0x6c
	NSTimer *_readyToPlayUpdateMinsTimer;	// 112 = 0x70
	float _lastBufferingProgress;	// 116 = 0x74
	unsigned _startChapterIndex;	// 120 = 0x78
	float _startPosition;	// 124 = 0x7c
	BOOL _drmAttempted;	// 128 = 0x80
	BOOL _playbackInitiated;	// 129 = 0x81
	BOOL _alwaysStopOnPop;	// 130 = 0x82
	BOOL _transportDisabled;	// 131 = 0x83
	BOOL _resumeMenuDisabled;	// 132 = 0x84
	BOOL _waitingForTransition;	// 133 = 0x85
	BOOL _visualsHidden;	// 134 = 0x86
	BOOL _inChapterMode;	// 135 = 0x87
	BOOL _digitalExtrasMenuItemDisabled;	// 136 = 0x88
	BOOL _itemReadyToPlay;	// 137 = 0x89
}
@property(assign) BOOL alwaysStopPlaybackWhenPopped;	// G=0x315c57cd; S=0x315c1975; converted property
@property(assign) BOOL digitalExtrasMenuItemDisabled;	// G=0x315c18f5; S=0x315c18e5; converted property
@property(readonly, retain) BRMediaPlayer *player;	// G=0x315c187d; converted property
@property(assign) id playerDelegate;	// G=0x315c188d; S=0x315c58ad; converted property
@property(assign) BOOL resumeMenuDisabled;	// G=0x315c18ad; S=0x315c189d; converted property
@property(assign) unsigned startChapterIndex;	// G=0x315c1915; S=0x315c1905; converted property
@property(assign) float startPosition;	// G=0x315c1965; S=0x315c1925; converted property
@property(assign) BOOL transportControlDisabled;	// G=0x315c18d5; S=0x315c18bd; converted property
@property(assign) BOOL visualsHidden;	// G=0x315c1995; S=0x315c1985; converted property
+ (id)controllerForPlayer:(id)player;	// 0x315c5955
- (id)initWithPlayer:(id)player;	// 0x315c5ae9
- (void)__enterVolumeWarningState;	// 0x315c5635
- (id)_audioVisualizer;	// 0x315c32dd
- (void)_authorizationAttemptComplete:(id)complete;	// 0x315c28a9
- (BOOL)_cycleInfoDisplay:(id)display;	// 0x315c30e1
- (id)_descriptionOverlayForType:(id)type;	// 0x315c3355
- (void)_dismissResumeMenu;	// 0x315c2279
- (BOOL)_enterAudioSubtitleChapterPicker;	// 0x315c320d
- (void)_enterChaptersSubtitlesAndAlternateAudioPickingState;	// 0x315c4075
- (void)_enterDRMSyncState:(BOOL)state;	// 0x315c3da1
- (void)_enterDownloadWaitState;	// 0x315c49b9
- (void)_enterErrorStateWithError:(id)error;	// 0x315c3bf9
- (void)_enterMediaCueingState;	// 0x315c6305
- (void)_enterMediaResolutionState;	// 0x315c4661
- (void)_enterPINEntryState;	// 0x315c4f69
- (void)_enterPlaybackStatePlaying:(BOOL)playing;	// 0x315c3f69
- (void)_enterPreResumeMenuState;	// 0x315c4c51
- (void)_enterResumeMenuState;	// 0x315c420d
- (void)_enterVolumeWarningState;	// 0x315c60a1
- (void)_exitChaptersSubtitlesAndAlternateAudioPickingState;	// 0x315c3fb9
- (void)_explanatoryTextTimerFired:(id)fired;	// 0x315c1a09
- (BOOL)_handleContextMenuEvent:(id)event;	// 0x315c1d71
- (void)_handleContextMenuSelection:(id)selection;	// 0x315c1b91
- (BOOL)_handleDownEvent:(id)event;	// 0x315c1c99
- (BOOL)_handleDownloadStateEvent:(id)event;	// 0x315c1af9
- (void)_handleHideChapterMarkers;	// 0x315c33bd
- (BOOL)_handleMenuButtonEvent:(id)event;	// 0x315c1db9
- (void)_handleShowChapterMarkers;	// 0x315c3419
- (BOOL)_handleUpDownCommandsForInfoDisplay:(id)infoDisplay;	// 0x315c1c01
- (BOOL)_handleUpEvent:(id)event;	// 0x315c1d21
- (void)_initiatePlayback;	// 0x315c3af9
- (double)_keyFrameAdjustedResumeTime:(double)time;	// 0x315c22cd
- (void)_mediaResolutionComplete:(id)complete;	// 0x315c27e5
- (BOOL)_mediaSupportsSubtitles:(id)subtitles;	// 0x315c2ce9
- (id)_photoSet;	// 0x315c2f95
- (void)_playExtraItemSelected:(id)selected;	// 0x315c20c5
- (void)_playerAssetChanged:(id)changed;	// 0x315c2965
- (void)_playerError:(id)error;	// 0x315c2989
- (void)_playerMediaCued:(id)cued;	// 0x315c278d
- (void)_playerPlaybackEnded:(id)ended;	// 0x315c2b11
- (void)_playerStateChanged:(id)changed;	// 0x315c2a05
- (void)_playerVisualsChanged:(id)changed;	// 0x315c29cd
- (void)_preResumeItemSelected:(id)selected;	// 0x315c218d
- (void)_preResumeStartFromBeginningItemSelected:(id)beginningItemSelected;	// 0x315c212d
- (void)_readyToPlayTimerFired:(id)playTimerFired;	// 0x315c48b1
- (void)_readyToPlayUpdateMinsTimerFired:(id)playUpdateMinsTimerFired;	// 0x315c47ed
- (void)_resumeItemSelected:(id)selected;	// 0x315c2241
- (double)_resumeTimeNearKeyframe;	// 0x315c2341
- (BOOL)_shouldRestoreVolume;	// 0x315c2575
- (BOOL)_shouldShowResumeMenu;	// 0x315c2e11
- (BOOL)_shouldShowVolumeWarning;	// 0x315c2519
- (BOOL)_shouldUseMusicContextMenu;	// 0x315c2b5d
- (void)_showLoadingSpinner;	// 0x315c3025
- (void)_startFromBeginningItemSelected:(id)beginningItemSelected;	// 0x315c21c1
- (void)_suppressBackgroundProcesses:(id)processes;	// 0x315c1a39
- (void)_transitionAnimationFinished;	// 0x315c23ad
- (id)_transportControlForType:(id)type;	// 0x315c345d
- (void)_updateExplantoryText;	// 0x315c3535
- (void)_updatePlaybackControls;	// 0x315c37c1
- (void)_volumeWarningDismissed:(id)dismissed;	// 0x315c23fd
// converted property getter: - (BOOL)alwaysStopPlaybackWhenPopped;	// 0x315c57cd
- (BOOL)brEventAction:(id)action;	// 0x315b77a9
- (BOOL)canBeScreenSaver;	// 0x315c19a5
- (void)clearPlayer;	// 0x315c58e5
- (void)controlWasActivated;	// 0x315c5649
- (void)controlWasDeactivated;	// 0x315c55c1
- (void)dealloc;	// 0x315c5999
// converted property getter: - (BOOL)digitalExtrasMenuItemDisabled;	// 0x315c18f5
- (BOOL)handleAssetFailedToLoad:(id)load;	// 0x315c5181
- (BOOL)handleAssetReadyToPlay:(id)play;	// 0x315c5201
- (void)layoutSubcontrols;	// 0x315c5e9d
// converted property getter: - (id)player;	// 0x315c187d
// converted property getter: - (id)playerDelegate;	// 0x315c188d
- (id)providersForContextMenu;	// 0x315c52c9
// converted property getter: - (BOOL)resumeMenuDisabled;	// 0x315c18ad
// converted property setter: - (void)setAlwaysStopPlaybackWhenPopped:(BOOL)popped;	// 0x315c1975
// converted property setter: - (void)setDigitalExtrasMenuItemDisabled:(BOOL)disabled;	// 0x315c18e5
// converted property setter: - (void)setPlayerDelegate:(id)delegate;	// 0x315c58ad
// converted property setter: - (void)setResumeMenuDisabled:(BOOL)disabled;	// 0x315c189d
// converted property setter: - (void)setStartChapterIndex:(unsigned)index;	// 0x315c1905
// converted property setter: - (void)setStartPosition:(float)position;	// 0x315c1925
// converted property setter: - (void)setTransportControlDisabled:(BOOL)disabled;	// 0x315c18bd
// converted property setter: - (void)setVisualsHidden:(BOOL)hidden;	// 0x315c1985
- (BOOL)shouldShowTrackPopup;	// 0x315c5429
- (BOOL)shouldTransitionIn;	// 0x315c5391
// converted property getter: - (unsigned)startChapterIndex;	// 0x315c1915
// converted property getter: - (float)startPosition;	// 0x315c1965
// converted property getter: - (BOOL)transportControlDisabled;	// 0x315c18d5
// converted property getter: - (BOOL)visualsHidden;	// 0x315c1995
- (void)wasPopped;	// 0x315c54d1
@end

