/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSMutableDictionary;

@interface BRMenuSavedState : BRSingleton {
@private
	NSMutableDictionary *_cachedMenuState;	// 4 = 0x4
	BOOL _enabled;	// 8 = 0x8
}
@property(assign) BOOL enabled;	// G=0x315b03d5; S=0x315b0381; converted property
+ (void)clearSavedSelectionForOwnerKey:(id)ownerKey;	// 0x31646735
+ (void)saveSelection:(id)selection atIndex:(id)index forOwnerKey:(id)ownerKey;	// 0x315b9701
+ (id)selectionInfoForOwnerKey:(id)ownerKey;	// 0x315b02d5
+ (void)setSingleton:(id)singleton;	// 0x315b0391
+ (id)singleton;	// 0x315b0305
- (id)init;	// 0x315b0311
- (void)dealloc;	// 0x316466c5
// converted property getter: - (BOOL)enabled;	// 0x315b03d5
- (id)objectForKey:(id)key;	// 0x315b039d
- (void)purge;	// 0x3164663d
- (void)removeObjectForKey:(id)key;	// 0x31646689
// converted property setter: - (void)setEnabled:(BOOL)enabled;	// 0x315b0381
- (void)setObject:(id)object forKey:(id)key;	// 0x315b9791
@end

