/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@protocol BRMediaCollection;

@interface BRMediaCollectionEditor : NSObject {
@private
	id<BRMediaCollection> _collection;	// 4 = 0x4
}
+ (id)editorForCollection:(id)collection;	// 0x315ce2ad
+ (void)setImplementationClass:(Class)aClass;	// 0x315ce281
- (id)initWithMediaCollection:(id)mediaCollection;	// 0x315ce335
- (void)addMediaObjectToCollection:(id)collection;	// 0x315ce291
- (void)clearCollection;	// 0x315ce299
- (id)collection;	// 0x315ce29d
- (id)collectionCopyWithName:(id)name;	// 0x315ce28d
- (void)dealloc;	// 0x315ce2ed
- (void)removeMediaObjectFromCollection:(id)collection;	// 0x315ce295
@end

