/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMediaMenuController.h"
#import "BackRow-Structs.h"
#import "BRMenuListItemProvider.h"

@class NSArray, NSDictionary;

@interface BRMediaShareListController : BRMediaMenuController <BRMenuListItemProvider> {
@private
	Class _mediaControllerClass;	// 136 = 0x88
	BRController *_noMediaErrorController;	// 140 = 0x8c
	BRController *_mountingController;	// 144 = 0x90
	NSDictionary *_selectedHostInfo;	// 148 = 0x94
	BOOL _isMounting;	// 152 = 0x98
	BOOL _isUnmounting;	// 153 = 0x99
	BOOL _hostDisconnected;	// 154 = 0x9a
	NSArray *_hostInfos;	// 156 = 0x9c
}
- (id)init;	// 0x3161cca9
- (void)_addNotifications;	// 0x3161be2d
- (void)_checkMountStatus:(id)status;	// 0x3161c1f5
- (void)_currentMediaHostRemoved:(id)removed;	// 0x3161cda9
- (id)_hostForHostInfoIndex:(long)hostInfoIndex;	// 0x3161bbc5
- (id)_hostInfos;	// 0x3161bc2d
- (BOOL)_isHostValid:(id)valid;	// 0x3161c0cd
- (void)_mediaHostsChanged:(id)changed;	// 0x3161bea9
- (void)_mountHost:(id)host;	// 0x3161c65d
- (void)_networkChanged:(id)changed;	// 0x3161be81
- (void)_removeNotifications;	// 0x3161bde5
- (long)_rowForTitle:(id)title;	// 0x3161ba65
- (id)_selectedHost;	// 0x3161bb95
- (void)_unmountStreamingHostsExcludingHost:(id)host;	// 0x3161c105
- (void)_updateHostInfos;	// 0x3161bb4d
- (id)_waitControllerForHost:(id)host;	// 0x3161bd11
- (id)_wirelessPreviewController;	// 0x3161bac5
- (void)controlWasActivated;	// 0x3161cb49
- (void)controlWasDeactivated;	// 0x3161c9a9
- (void)dealloc;	// 0x3161cc01
- (float)heightForRow:(long)row;	// 0x3161ba31
- (long)itemCount;	// 0x3161c835
- (id)itemForRow:(long)row;	// 0x3161c859
- (void)itemSelected:(long)selected;	// 0x3161cb95
- (id)previewControlForItem:(long)item;	// 0x3161cbed
- (BOOL)rowSelectable:(long)selectable;	// 0x3161ba35
- (void)setMediaControllerClass:(Class)aClass errorController:(id)controller;	// 0x3161c929
- (id)titleForRow:(long)row;	// 0x3161c811
- (void)wasExhumed;	// 0x3161c9e5
- (void)wasPopped;	// 0x3161ba39
- (void)wasPushed;	// 0x3161ca89
@end

