/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRType.h"


@interface BRMediaType : BRType {
@private
	BRMediaType *_derivedFrom;	// 8 = 0x8
}
@property(retain) id parentType;	// G=0x31597d9d; S=0x31593881; converted property
+ (id)TVShow;	// 0x31593c61
+ (id)TVShowPreview;	// 0x31593d35
+ (id)_defaultImageForMediaType:(id)mediaType forImageSize:(int)imageSize;	// 0x316346f5
+ (id)airTunes;	// 0x31594a05
+ (id)audioBook;	// 0x31593f0d
+ (id)booklet;	// 0x31593fe1
+ (id)cdSong;	// 0x315938b9
+ (id)coachedAudio;	// 0x31594389
+ (id)defaultImageForMediaType:(id)mediaType forImageSize:(int)imageSize;	// 0x316331a5
+ (id)demoRentalMovie;	// 0x31594bd9
+ (id)dotMacPhoto;	// 0x316344ed
+ (id)dotMacVideo;	// 0x316340e9
+ (id)dotMacVideoSlideshow;	// 0x31633fe9
+ (id)downloadSpeedTest;	// 0x31633de9
+ (id)dvd;	// 0x31593b8d
+ (id)flikrPhoto;	// 0x316343e9
+ (id)iTunesExtras;	// 0x31633d15
+ (id)iTunesLP;	// 0x31633c41
+ (id)iTunesU;	// 0x31633a99
+ (void)initialize;	// 0x31593405
+ (id)interactiveBooklet;	// 0x315942b5
+ (id)internetPhoto;	// 0x316345f1
+ (id)internetPhotoMediaTypes;	// 0x31633541
+ (id)internetRadioStation;	// 0x31594905
+ (id)liveStreamingTypes;	// 0x316331c5
+ (id)movie;	// 0x315939b9
+ (id)moviePreview;	// 0x31593a8d
+ (id)movieTrailer;	// 0x31594531
+ (id)musicVideo;	// 0x315940b5
+ (id)musicVideoPreview;	// 0x315941b5
+ (id)onTheGoMediaTypes;	// 0x3163341d
+ (id)photo;	// 0x3159445d
+ (id)podcast;	// 0x31593e39
+ (id)podcastSubscription;	// 0x31594b05
+ (id)radioStation;	// 0x31633ee9
+ (id)sedonaMovie;	// 0x316339c5
+ (id)sedonaTVShow;	// 0x316338f1
+ (id)song;	// 0x315936ad
+ (id)songPreview;	// 0x31593781
+ (id)storeMediaTypeStringForMediaType:(id)mediaType;	// 0x3163303d
+ (id)storeMediaTypes;	// 0x31633651
+ (id)storeRentalMovie;	// 0x316342e9
+ (id)storeRentalTVShow;	// 0x316341e9
+ (id)streamingPodcast;	// 0x31594731
+ (id)syncedInternetRadioStation;	// 0x31594805
+ (id)trickPlay;	// 0x31633b6d
+ (id)unchapteredTypes;	// 0x31633269
+ (id)ytVideo;	// 0x31594631
- (void)dealloc;	// 0x316333d5
- (id)description;	// 0x31633001
- (BOOL)isKindOfMediaType:(id)mediaType;	// 0x31632fd5
// converted property getter: - (id)parentType;	// 0x31597d9d
// converted property setter: - (void)setParentType:(id)type;	// 0x31593881
@end

