/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRMediaCollectionGeniusInfo : NSObject {
}
+ (id)geniusInfoForGeniusPlaylist:(id)geniusPlaylist;	// 0x315ce3fd
+ (BOOL)isGeniusDBAvailable;	// 0x315ce3d9
+ (void)setImplementationClass:(Class)aClass;	// 0x315ce389
- (id)initWithGeniusPlaylist:(id)geniusPlaylist;	// 0x315ce3ad
- (BOOL)assetIsCurrentSeed:(id)seed;	// 0x315ce395
- (BOOL)assetIsValidSeed:(id)seed;	// 0x315ce399
- (BOOL)playlistIsDirty;	// 0x315ce3a9
- (BOOL)refreshGeniusPlaylist;	// 0x315ce3a1
- (id)saveGeniusPlaylist;	// 0x315ce3a5
- (BOOL)setGeniusSeed:(id)seed;	// 0x315ce39d
@end

