/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRMediaCollectionGeniusMixInfo : NSObject {
}
@property(retain) id generatedImage;	// G=0x316649ed; S=0x316649f1; converted property
+ (id)geniusMixInfoForGeniusMix:(id)geniusMix;	// 0x31664a21
+ (void)setImplementationClass:(Class)aClass;	// 0x316649d5
- (id)initWithGeniusMix:(id)geniusMix;	// 0x316649f5
- (id)basedOnText;	// 0x316649e1
// converted property getter: - (id)generatedImage;	// 0x316649ed
- (id)images;	// 0x316649e9
- (BOOL)isValid;	// 0x316649e5
// converted property setter: - (void)setGeneratedImage:(id)image;	// 0x316649f1
@end

