/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSString;

@interface BRMediaHostState : NSObject {
@private
	NSString *_description;	// 4 = 0x4
}
@property(readonly, retain) NSString *description;	// G=0x3158eb41; converted property
+ (id)available;	// 0x31590ffd
+ (id)mountFailed;	// 0x31632f01
+ (id)mounted;	// 0x31591279
+ (id)mounting;	// 0x315910d1
+ (id)unavailable;	// 0x3158e819
+ (id)unmounting;	// 0x315911a5
- (id)initWithDescription:(id)description;	// 0x3158e8ed
- (void)dealloc;	// 0x31632c11
// converted property getter: - (id)description;	// 0x3158eb41
- (id)mediaHostEvent:(id)event forMediaHost:(id)mediaHost;	// 0x3159154d
@end

