/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSArray;

@interface BRMenuItemLayerFactory : BRSingleton {
@private
	NSArray *_populators;	// 4 = 0x4
}
+ (void)setSingleton:(id)singleton;	// 0x31593029
+ (id)singleton;	// 0x3159301d
- (id)init;	// 0x3160a819
- (id)_populatorForObject:(id)object;	// 0x3160a8e1
- (void)dealloc;	// 0x3160a7d1
- (id)menuItemForObject:(id)object;	// 0x3160a7b9
- (id)menuItemForObject:(id)object delegate:(id)delegate;	// 0x3160a75d
- (float)menuItemHeightForObject:(id)object;	// 0x3160a7a1
- (float)menuItemHeightForObject:(id)object delegate:(id)delegate;	// 0x3160a72d
- (void)registerPopulator:(Class)populator;	// 0x31593035
- (id)titleForObject:(id)object;	// 0x3160a789
- (id)titleForObject:(id)object delegate:(id)delegate;	// 0x3160a701
@end

