/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BROptionDialog.h"


@interface BRModalOptionDialog : BROptionDialog {
@private
	long _cancelIdx;	// 124 = 0x7c
	BOOL _allowMenuButton;	// 128 = 0x80
}
- (id)init;	// 0x315a6ad5
- (id)initAllowingMenuButton:(BOOL)button;	// 0x315db5dd
- (void)_done:(id)done;	// 0x315a6c1d
- (BOOL)brEventAction:(id)action;	// 0x315a6b91
- (long)runModal;	// 0x315a6aed
- (void)setCancelIndex:(long)index;	// 0x315db5cd
@end

