/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRMultiPartWidgetLayer : BRControl {
@private
	BOOL _suppressAnimations;	// 38 = 0x26
	BRControl *_multiPartControls[12];	// 40 = 0x28
}
+ (void)_setAntialiasingFlagsForLayer:(int)layer control:(id)control;	// 0x3161d8b1
- (id)init;	// 0x3161da81
- (id)_defaultActions;	// 0x31595761
- (void)_updateImage:(id)image forLayer:(int)layer;	// 0x3161dac1
- (float)animationDuration;	// 0x3161d8a9
- (id)animationTimingFunction;	// 0x3161d94d
- (CGSize)edgeSize;	// 0x315a6e09
- (void)layoutSubcontrols;	// 0x3161dbd5
- (void)setBottomDeco:(id)deco;	// 0x315958f9
- (void)setBottomEdge:(id)edge;	// 0x315958e1
- (void)setBottomLeftCorner:(id)corner;	// 0x31595851
- (void)setBottomRightCorner:(id)corner;	// 0x31595749
- (void)setCenter:(id)center;	// 0x315a15ad
- (void)setCenterOverlapFactor:(float)factor;	// 0x315a1561
- (void)setImageMap:(const BRMultiPartImageMap *)map forBundle:(id)bundle;	// 0x315956a1
- (void)setLeftEdge:(id)edge;	// 0x31595899
- (void)setRightEdge:(id)edge;	// 0x315958b1
- (void)setSuppressAnimations:(BOOL)animations;	// 0x3161da49
- (void)setTopDeco:(id)deco;	// 0x31595911
- (void)setTopEdge:(id)edge;	// 0x315958c9
- (void)setTopLeftCorner:(id)corner;	// 0x31595881
- (void)setTopRightCorner:(id)corner;	// 0x31595869
- (void)updateAnimations;	// 0x3161d979
@end

