/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"

@class NSString, NSTimer, NSDictionary, NSMutableDictionary, NSArray, NSNumber;
@protocol BRMediaProvider;

@interface BRMusicStore : BRSingleton {
@private
	int _musicStoreLoadState;	// 4 = 0x4
	NSDictionary *_storeFrontsDictionary;	// 8 = 0x8
	NSNumber *_storeFrontID;	// 12 = 0xc
	NSArray *_rootCollection;	// 16 = 0x10
	id<BRMediaProvider> _provider;	// 20 = 0x14
	BOOL _initializing;	// 24 = 0x18
	NSString *_selectedLanguageCode;	// 28 = 0x1c
	NSString *_storeMainMenuPresentsKey;	// 32 = 0x20
	NSDictionary *_urlBag;	// 36 = 0x24
	NSTimer *_retryTimer;	// 40 = 0x28
	NSString *_platform;	// 44 = 0x2c
	BOOL _initializePlatform;	// 48 = 0x30
	NSMutableDictionary *_languageIDForLanguageCodeCache;	// 52 = 0x34
}
@property(retain) id currentStoreFrontID;	// G=0x31598121; S=0x31639781; converted property
@property(assign) int musicStoreLoadState;	// G=0x316393c5; S=0x316397b9; converted property
@property(readonly, retain) NSArray *rootCollection;	// G=0x31597eb1; converted property
+ (void)setSingleton:(id)singleton;	// 0x3158f5a1
+ (id)singleton;	// 0x3158f499
- (id)init;	// 0x3158f4a5
- (id)URLBagEntryForKey:(id)key;	// 0x31639799
- (void)_bootstrapMusicStore;	// 0x31597f59
- (void)_bootstrapMusicStoreFromURL:(id)url;	// 0x31639a29
- (id)_canonicalNameForMediaType:(id)mediaType;	// 0x3159c79d
- (id)_currentStoreFrontsFilePath;	// 0x3163a431
- (id)_defaultStoreFrontsFilePath;	// 0x3163abd1
- (id)_determineLanguageCodeForStoreFront:(id)storeFront;	// 0x31598345
- (void)_initializeGhostrider:(id)ghostrider;	// 0x3159c27d
- (BOOL)_initializeMusicStore:(id)store;	// 0x3159bedd
- (void)_initializeSedona:(id)sedona;	// 0x316393d9
- (id)_languageIDForLanguageCode:(id)languageCode;	// 0x315984d9
- (BOOL)_loadRootCollection:(id)collection;	// 0x3159c009
- (void)_networkStateChanged:(id)changed;	// 0x3163994d
- (void)_requestStoreFrontList:(id)list;	// 0x3163a52d
- (void)_retryRootCollection:(id)collection;	// 0x3163946d
- (void)_rootCollectionLoaded:(id)loaded;	// 0x3159c541
- (void)_seedMusicStore:(id)store;	// 0x31639491
- (BOOL)_seedMusicStoreWithDocument:(id)document;	// 0x3159bc75
- (void)_seedRequestProcessed:(id)processed;	// 0x3159b7bd
- (void)_setCurrentStoreFrontID:(id)anId language:(id)language platform:(id)platform;	// 0x3163a465
- (void)_setRootCollection:(id)collection;	// 0x3159c6e9
- (void)_storeFrontListRequestProcessed:(id)processed;	// 0x3163a919
- (id)_storeFrontsDictionary;	// 0x3163a6e1
- (void)_storeLoadFailed:(id)failed;	// 0x3163a669
- (void)_updateStoreFrontFromResponse:(id)response;	// 0x3159ba69
- (id)_ytURLDictPath;	// 0x3159c41d
- (id)cacheBusterURLForURL:(id)url;	// 0x316393d5
// converted property getter: - (id)currentStoreFrontID;	// 0x31598121
- (void)dealloc;	// 0x31639805
- (void)decomposeCompositeStoreFrontHeader:(id)header;	// 0x3159bb39
- (void)delayedRootCollectionReset;	// 0x31639b25
- (id)downloadSpeedTestPostResultsURLString;	// 0x31639dad
- (id)downloadSpeedTestURLsArray;	// 0x31639e71
- (id)keyValueStoreGetAllURLString;	// 0x31639ce9
- (id)keyValueStorePutAllURLString;	// 0x31639c25
// converted property getter: - (int)musicStoreLoadState;	// 0x316393c5
- (id)provider;	// 0x3163a0d1
- (void)purgeMusicStore;	// 0x31639731
// converted property getter: - (id)rootCollection;	// 0x31597eb1
- (id)rootCollectionForMediaType:(id)mediaType;	// 0x31597dad
// converted property setter: - (void)setCurrentStoreFrontID:(id)anId;	// 0x31639781
- (void)setCurrentStoreFrontID:(id)anId language:(id)language;	// 0x3163a1f9
// converted property setter: - (void)setMusicStoreLoadState:(int)state;	// 0x316397b9
- (id)storeFronts;	// 0x31598495
- (id)storeHeadersDictionary;	// 0x31597f79
- (id)storeMainMenuPresentsURLString;	// 0x31639ff9
- (id)storeRecommendationsURL;	// 0x315a72e1
- (id)storeRelatedMoviesURLString;	// 0x315a9231
- (id)storeViewMovieURLString;	// 0x31639f35
- (id)userAgent;	// 0x31598715
- (id)ytAuthURLBase;	// 0x315bd1e1
- (id)ytURLBase;	// 0x315bd149
@end

