/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRContextMenuUtility.h"


@interface BRMusicContextMenuUtility : NSObject <BRContextMenuUtility> {
@private
	BOOL _onTheGoEnabled;	// 4 = 0x4
	BOOL _startGeniusEnabled;	// 5 = 0x5
	BOOL _airTunesSettingsEnabled;	// 6 = 0x6
	BOOL _browseArtistEnabled;	// 7 = 0x7
	BOOL _browseAlbumEnabled;	// 8 = 0x8
	BOOL _navigateToArtistForBrowseArtist;	// 9 = 0x9
	BOOL _navigateToAlbumForBrowseAlbum;	// 10 = 0xa
}
@property(assign) BOOL airTunesSettingsEnabled;	// G=0x316467c5; S=0x316467b5; converted property
@property(assign) BOOL browseAlbumEnabled;	// G=0x31646805; S=0x316467f5; converted property
@property(assign) BOOL browseArtistEnabled;	// G=0x316467e5; S=0x316467d5; converted property
@property(assign) BOOL navigateToAlbumForBrowseAlbum;	// G=0x31646845; S=0x31646835; converted property
@property(assign) BOOL navigateToArtistForBrowseArtist;	// G=0x31646825; S=0x31646815; converted property
@property(assign) BOOL onTheGoEnabled;	// G=0x31646785; S=0x31646775; converted property
@property(assign) BOOL startGeniusEnabled;	// G=0x316467a5; S=0x31646795; converted property
+ (void)setImplementationClass:(Class)aClass;	// 0x31646769
+ (id)utility;	// 0x316468c9
- (id)init;	// 0x3164685d
// converted property getter: - (BOOL)airTunesSettingsEnabled;	// 0x316467c5
// converted property getter: - (BOOL)browseAlbumEnabled;	// 0x31646805
// converted property getter: - (BOOL)browseArtistEnabled;	// 0x316467e5
- (id)contextMenuProviderForObject:(id)object target:(id)target selector:(SEL)selector;	// 0x31646855
- (void)handleSelectionForObject:(id)object sender:(id)sender context:(id)context;	// 0x31646859
// converted property getter: - (BOOL)navigateToAlbumForBrowseAlbum;	// 0x31646845
// converted property getter: - (BOOL)navigateToArtistForBrowseArtist;	// 0x31646825
// converted property getter: - (BOOL)onTheGoEnabled;	// 0x31646785
// converted property setter: - (void)setAirTunesSettingsEnabled:(BOOL)enabled;	// 0x316467b5
// converted property setter: - (void)setBrowseAlbumEnabled:(BOOL)enabled;	// 0x316467f5
// converted property setter: - (void)setBrowseArtistEnabled:(BOOL)enabled;	// 0x316467d5
// converted property setter: - (void)setNavigateToAlbumForBrowseAlbum:(BOOL)browseAlbum;	// 0x31646835
// converted property setter: - (void)setNavigateToArtistForBrowseArtist:(BOOL)browseArtist;	// 0x31646815
// converted property setter: - (void)setOnTheGoEnabled:(BOOL)enabled;	// 0x31646775
// converted property setter: - (void)setStartGeniusEnabled:(BOOL)enabled;	// 0x31646795
// converted property getter: - (BOOL)startGeniusEnabled;	// 0x316467a5
@end

