/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface BRMusicStoreUtility : NSObject {
}
+ (void)fetchBookmarkTimeForAsset:(id)asset completionHandler:(id)handler;	// 0x3168b169
+ (void)setImplementationClass:(Class)aClass;	// 0x3168b15d
@end

