/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRAlertController.h"


@interface BRNetworkAlertController : BRAlertController {
}
- (id)initWithType:(int)type titled:(id)titled primaryText:(id)text secondaryText:(id)text4;	// 0x315dabe5
- (void)_networkStatusChanged:(id)changed;	// 0x315db081
- (void)dealloc;	// 0x315dab91
@end

