/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImage, NSString;

__attribute__((visibility("hidden")))
@interface BRPairingPinControl : BRControl {
@private
	BRImage *_boxImage;	// 40 = 0x28
	NSString *_pin;	// 44 = 0x2c
}
@property(retain) id PIN;	// G=0x315f2ca1; S=0x315f2cb1; converted property
- (id)init;	// 0x315f2e71
// converted property getter: - (id)PIN;	// 0x315f2ca1
- (id)_layerForPINDigit:(id)pindigit;	// 0x315f2f1d
- (void)dealloc;	// 0x315f2e15
- (void)layoutSubcontrols;	// 0x315f2fdd
// converted property setter: - (void)setPIN:(id)pin;	// 0x315f2cb1
@end

