/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class NSArray, BRImageControl, BRTextControl, BRPasscodeSelectionWidget;

__attribute__((visibility("hidden")))
@interface BRPasscodeSelectionLayer : BRControl {
@private
	NSArray *_backgroundLayers;	// 40 = 0x28
	NSArray *_digitLayers;	// 44 = 0x2c
	NSArray *_bulletLayers;	// 48 = 0x30
	BRImageControl *_arrowsLayer;	// 52 = 0x34
	BRPasscodeSelectionWidget *_selectionWidget;	// 56 = 0x38
	BRTextControl *_doneLayer;	// 60 = 0x3c
	BOOL _isUserEditable;	// 64 = 0x40
	unsigned _numDigits;	// 68 = 0x44
	BOOL _hideDigits;	// 72 = 0x48
	int _selection;	// 76 = 0x4c
}
@property(retain) id passcode;	// G=0x31624d51; S=0x31624bd5; converted property
- (id)initWithNumDigits:(unsigned)numDigits userEditable:(BOOL)editable hideDigits:(BOOL)digits;	// 0x3162410d
- (void)_adjustDigitVisibility:(id)visibility;	// 0x31623bad
- (CGRect)_arrowsFrameForSelection:(int)selection;	// 0x31625931
- (id)_buildArrowsLayer;	// 0x316253f9
- (id)_buildBackgroundLayers;	// 0x316254a5
- (id)_buildBulletLayers;	// 0x31623d79
- (id)_buildDigitLayers;	// 0x31623ec5
- (id)_buildDoneLayer;	// 0x316255cd
- (CGRect)_cellFrameForSelection:(int)selection;	// 0x316244e1
- (CGRect)_digitFrameForSelection:(int)selection digit:(id)digit;	// 0x31625885
- (void)_hideDigitAtIndex:(int)index;	// 0x31623c05
- (float)_layoutUIWithHeight:(float)height;	// 0x31624655
- (CGRect)_selectionWidgetFrameForSelection:(int)selection;	// 0x316245c5
- (void)_setDigitHighlighted:(BOOL)highlighted atIndex:(int)index;	// 0x31623c85
- (void)_setDigitValue:(id)value atIndex:(int)index;	// 0x31625695
- (void)_setSelection:(int)selection;	// 0x31624355
- (void)dealloc;	// 0x31624069
- (BOOL)decrementSelection;	// 0x31624f39
- (BOOL)digitsHidden;	// 0x31623b9d
- (BOOL)doneButtonSelected;	// 0x31624b8d
- (void)hideDigits:(int)digits;	// 0x316249b9
- (BOOL)incrementSelection;	// 0x316250c1
- (BOOL)moveSelectionLeft;	// 0x31625259
- (BOOL)moveSelectionRight;	// 0x31625321
// converted property getter: - (id)passcode;	// 0x31624d51
- (CGRect)preferredFrameForScreenSize:(CGSize)screenSize;	// 0x31625751
- (void)reset;	// 0x31623fe9
- (void)setFrame:(CGRect)frame;	// 0x31624a99
// converted property setter: - (void)setPasscode:(id)passcode;	// 0x31624bd5
- (BOOL)setSelection:(int)selection;	// 0x31624e6d
- (float)widthOfDigitsForScreenSize:(CGSize)screenSize;	// 0x3162494d
@end

