/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRProvider.h"

@class NSArray;
@protocol BRControlFactory;

@interface BRPhotoProvider : NSObject <BRProvider> {
@private
	NSArray *_collections;	// 4 = 0x4
	id<BRControlFactory> _controlFactory;	// 8 = 0x8
}
@property(retain) id controlFactory;	// G=0x3167b535; S=0x3167b781; converted property
+ (id)providerWithCollections:(id)collections controlFactory:(id)factory;	// 0x3167b885
- (id)initWithCollections:(id)collections controlFactory:(id)factory;	// 0x3167b815
// converted property getter: - (id)controlFactory;	// 0x3167b535
- (id)dataAtIndex:(long)index;	// 0x3167b721
- (long)dataCount;	// 0x3167b761
- (void)dealloc;	// 0x3167b7b9
- (id)hashForDataAtIndex:(long)index;	// 0x3167b6fd
// converted property setter: - (void)setControlFactory:(id)factory;	// 0x3167b781
@end

