/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRPhotoBrowserCorkBoardControl : BRControl {
@private
	BRImage *_image;	// 40 = 0x28
}
- (id)init;	// 0x3165a5e5
- (void)dealloc;	// 0x3165a59d
- (void)layoutSubcontrols;	// 0x3165a6b5
@end

