/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlHeightFactory.h"
#import "BRControlFactory.h"

@protocol BRSelectionHandler;

__attribute__((visibility("hidden")))
@interface BRPhotoBrowserControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	id<BRSelectionHandler> _handler;	// 4 = 0x4
}
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x3161483d
- (void)dealloc;	// 0x31614959
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x316149a1
- (void)setSelectionHandler:(id)handler;	// 0x31614921
@end

