/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRControlHeightFactory.h"
#import "BRControlFactory.h"

@class BRMediaType, NSSet;

__attribute__((visibility("hidden")))
@interface BRPlaylistsControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	BOOL _showMetadata;	// 4 = 0x4
	BRMediaType *_missingType;	// 8 = 0x8
	NSSet *_mediaTypes;	// 12 = 0xc
	BOOL _useMultilineItems;	// 16 = 0x10
	BOOL _showIconForVideo;	// 17 = 0x11
	BOOL _resolveArtworkFromParent;	// 18 = 0x12
}
@property(readonly, retain) NSSet *mediaTypes;	// G=0x31618ba5; converted property
@property(assign) BOOL shouldUseMultilineItems;	// G=0x31618bc5; S=0x31618bb5; converted property
@property(assign) BOOL showIconForVideo;	// G=0x31618be5; S=0x31618bd5; converted property
+ (id)factoryWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata;	// 0x31618e35
+ (id)factoryWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata resolveArtworkFromParentCollections:(BOOL)parentCollections;	// 0x31618de1
- (id)initWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata;	// 0x31618db5
- (id)initWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata resolveArtworkFromParentCollections:(BOOL)parentCollections;	// 0x31618ed5
- (BOOL)_showUnplayedIconForAsset:(id)asset;	// 0x31618bf5
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x31618f69
- (void)dealloc;	// 0x31618e79
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x31618cc9
// converted property getter: - (id)mediaTypes;	// 0x31618ba5
// converted property setter: - (void)setShouldUseMultilineItems:(BOOL)useMultilineItems;	// 0x31618bb5
// converted property setter: - (void)setShowIconForVideo:(BOOL)video;	// 0x31618bd5
// converted property getter: - (BOOL)shouldUseMultilineItems;	// 0x31618bc5
// converted property getter: - (BOOL)showIconForVideo;	// 0x31618be5
@end

