/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMediaMenuController.h"
#import "BackRow-Structs.h"

@class NSSet;

@interface BRPlaylistsMenuController : BRMediaMenuController {
@private
	NSSet *_mediaTypes;	// 136 = 0x88
}
+ (id)_dataStoreWithMediaTypes:(id)mediaTypes sortDescriptors:(id)descriptors;	// 0x31619c25
+ (long)playlistCountForMediaTypes:(id)mediaTypes;	// 0x31619db9
- (id)initWithMediaTypes:(id)mediaTypes;	// 0x31619da1
- (id)initWithMediaTypes:(id)mediaTypes resolveArtworkFromParentCollections:(BOOL)parentCollections;	// 0x31619fd1
- (id)_dataProviderForController:(id)controller;	// 0x31619b75
- (void)_itemSelected:(id)selected;	// 0x316199f9
- (void)_pushControllerForPlaylist:(id)playlist;	// 0x31619699
- (void)_startPlayerWithTrackAtIndex:(long)index tracklist:(id)tracklist shuffle:(BOOL)shuffle list:(id)list;	// 0x31619481
- (void)dealloc;	// 0x31619f89
@end

