/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRPosterReflectionControl : BRControl {
@private
	BRImage *_image;	// 40 = 0x28
	float _cornerRadius;	// 44 = 0x2c
	float _reflectionHeight;	// 48 = 0x30
}
- (id)initWithImage:(id)image reflectionHeight:(float)height cornerRadius:(float)radius;	// 0x3160d869
- (void)dealloc;	// 0x3160d821
- (void)drawInContext:(CGContextRef)context;	// 0x316110dd
@end

