/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImageControl, BRImage, BRTextControl, BRWaitSpinnerControl, BRHorizontalSegmentedWidget, BRAsyncTask, BRAutoScrollingTextControl, NSString, BRPosterReflectionControl, NSTimer;
@protocol BRImageProxy;

@interface BRPosterControl : BRControl {
@private
	int _style;	// 40 = 0x28
	BRImageControl *_defaultImageControl;	// 44 = 0x2c
	BRImage *_defaultImage;	// 48 = 0x30
	BOOL _usingDefaultImage;	// 52 = 0x34
	BRControl *_imageControl;	// 56 = 0x38
	BRImage *_image;	// 60 = 0x3c
	id<BRImageProxy> _imageProxy;	// 64 = 0x40
	BRImage *_tempImage;	// 68 = 0x44
	BRHorizontalSegmentedWidget *_numberBadge;	// 72 = 0x48
	int _numberBadgeValue;	// 76 = 0x4c
	CGColorRef _posterBorderColor;	// 80 = 0x50
	float _posterBorderWidth;	// 84 = 0x54
	BOOL _imageRequested;	// 88 = 0x58
	NSString *_artworkIdentifier;	// 92 = 0x5c
	BRAsyncTask *_imageTask;	// 96 = 0x60
	BOOL _imageLoadSuspended;	// 100 = 0x64
	BRPosterReflectionControl *_reflectionControl;	// 104 = 0x68
	float _reflectionAmount;	// 108 = 0x6c
	float _reflectionBaseline;	// 112 = 0x70
	BRTextControl *_ordinalTextControl;	// 116 = 0x74
	BRAutoScrollingTextControl *_autoScrollingTitleControl;	// 120 = 0x78
	BRTextControl *_subtitleTextControl;	// 124 = 0x7c
	float _titleWidthScale;	// 128 = 0x80
	float _titleVerticalOffset;	// 132 = 0x84
	BOOL _alwaysShowTitles;	// 136 = 0x88
	BOOL _onlyShowSubtitlesWhenFocused;	// 137 = 0x89
	BRWaitSpinnerControl *_spinnerControl;	// 140 = 0x8c
	NSTimer *_localFinalFormTimer;	// 144 = 0x90
	float _cornerRadius;	// 148 = 0x94
	float _cropAspectRatio;	// 152 = 0x98
	BOOL _autoDownsample;	// 156 = 0x9c
	BOOL _observingBounds;	// 157 = 0x9d
	BOOL _cropAndFill;	// 158 = 0x9e
	BOOL _deletterboxImage;	// 159 = 0x9f
	BRImageControl *_badgeImageControl;	// 160 = 0xa0
	BRImage *_badgeImage;	// 164 = 0xa4
	float _badgeScale;	// 168 = 0xa8
	float _badgeOpacity;	// 172 = 0xac
	float _badgeFocusedOpacity;	// 176 = 0xb0
	int _badgePosition;	// 180 = 0xb4
	BOOL _badgeUpdated;	// 184 = 0xb8
	BRImage *_borderImage;	// 188 = 0xbc
	CGRect _borderImageFocusRect;	// 192 = 0xc0
	CGRect _borderImagePhotoImageRect;	// 208 = 0xd0
	BOOL _decoratedImageCacheEnabled;	// 224 = 0xe0
	BOOL _usingDecoratedImage;	// 225 = 0xe1
	BOOL _imageEdgeAntialiasingEnabled;	// 226 = 0xe2
}
@property(assign) BOOL alwaysShowTitles;	// G=0x3160d69d; S=0x3160eafd; converted property
@property(readonly, retain) BRImage *badgeImage;	// G=0x3160d5f5; converted property
@property(assign) float badgeOpacity;	// G=0x3160d625; S=0x3160f005; converted property
@property(readonly, assign) int badgePosition;	// G=0x3160d605; converted property
@property(assign) float badgeScale;	// G=0x3160d615; S=0x3160f07d; converted property
@property(assign) float cornerRadius;	// G=0x3160d5c5; S=0x3160f1f9; converted property
@property(assign) BOOL cropAndFill;	// G=0x3160d5d5; S=0x3160f1bd; converted property
@property(assign) float cropAspectRatio;	// G=0x3160d5e5; S=0x3160f175; converted property
@property(retain) BRImage *defaultImage;	// G=0x3160d4ed; S=0x3160f665; converted property
@property(assign) BOOL deletterboxImage;	// G=0x3160d6ed; S=0x3160d6dd; converted property
@property(assign) float focusedBadgeOpacity;	// G=0x3160d635; S=0x3160ef8d; converted property
@property(retain) BRImage *image;	// G=0x3160d6cd; S=0x3160e87d; converted property
@property(retain) id imageProxy;	// G=0x3160d52d; S=0x3160f599; converted property
@property(assign) int numberBadgeValue;	// G=0x3160d645; S=0x3160ecf9; converted property
@property(assign) BOOL onlyShowSubtitlesWhenFocused;	// G=0x3160d6bd; S=0x3160d6ad; converted property
@property(assign) int ordinal;	// G=0x3160f331; S=0x3160f36d; converted property
@property(assign) CGColorRef posterBorderColor;	// G=0x3160d4fd; S=0x3160fd5d; converted property
@property(assign) float posterBorderWidth;	// G=0x3160d50d; S=0x3160f631; converted property
@property(assign) int posterStyle;	// G=0x3160d51d; S=0x316128d9; converted property
@property(assign) float reflectionAmount;	// G=0x3160d591; S=0x3160f4ed; converted property
@property(assign) float reflectionBaseline;	// G=0x3160d5a1; S=0x3160f4b9; converted property
@property(assign) BOOL spinnerEnabled;	// G=0x3160d5b1; S=0x3160f21d; converted property
@property(retain) id subtitle;	// G=0x3160e91d; S=0x3160e9dd; converted property
@property(retain) id title;	// G=0x3160eb99; S=0x3160ece1; converted property
@property(assign) float titleVerticalOffset;	// G=0x3160d68d; S=0x3160eb25; converted property
@property(assign) float titleWidthScale;	// G=0x3160d665; S=0x3160eb59; converted property
+ (void)initialize;	// 0x3160f8e9
+ (Class)layerClass;	// 0x3160f949
+ (id)polaroidPosterWithImageProxy:(id)imageProxy title:(id)title;	// 0x3160f969
+ (id)posterButtonWithImage:(id)image title:(id)title;	// 0x3160fa95
+ (id)tilePosterWithImageProxy:(id)imageProxy title:(id)title subtitle:(id)subtitle;	// 0x3160f9b9
+ (id)twoLinePosterButtonWithImage:(id)image title:(id)title subtitle:(id)subtitle;	// 0x3160fa31
- (id)init;	// 0x3160f865
- (id)_addFadeAnimationToLayer:(id)layer forKey:(id)key;	// 0x3160dfb5
- (id)_artworkIdentifier;	// 0x3160d77d
- (void)_cropImage:(id)image;	// 0x3160e509
- (id)_currentImage;	// 0x3160d75d
- (CGRect)_currentImageRect;	// 0x316107f1
- (void)_decorateImage:(id)image;	// 0x31610ea5
- (id)_decoratedImageIdentifier:(id)identifier size:(CGSize)size;	// 0x3160dce1
- (void)_delayedFinalFormSetting:(id)setting;	// 0x3160d8e1
- (void)_deletterboxImage:(id)image;	// 0x3160e609
- (id)_fetchImage;	// 0x3160db5d
- (void)_focusWasChanged;	// 0x3160dee5
- (id)_getDecoratedImage:(id)image imageID:(id)anId toSize:(CGSize)size writeToDisk:(BOOL)disk;	// 0x31612409
- (id)_getImageFromImageManagerNamed:(id)imageManagerNamed withSize:(CGSize)size;	// 0x3160d919
- (BOOL)_imageRequiresCrop;	// 0x3160d71d
- (int)_imageSize;	// 0x3160d78d
- (void)_imageTaskComplete:(id)complete;	// 0x3160e46d
- (void)_imageUpdated:(id)updated;	// 0x316104e1
- (CGRect)_mainImageRectFromMainImageUnitRect;	// 0x31611341
- (CGRect)_maxImageRect;	// 0x31610879
- (id)_numberBadgeAttributes;	// 0x31610f5d
- (id)_ordinalAttributes;	// 0x316109a1
- (id)_resizeImage:(id)image;	// 0x31610329
- (void)_restartImageResizing;	// 0x3160dd41
- (void)_scaleImage:(id)image;	// 0x31610fe9
- (void)_setArtworkIdentifier:(id)identifier;	// 0x3160de01
- (void)_setAttributedTitle:(id)title withCrossfade:(BOOL)crossfade;	// 0x3160e089
- (void)_setFinalFormImage:(id)image;	// 0x3160dcc9
- (void)_setFinalFormImage:(id)image needsLayout:(BOOL)layout;	// 0x3160dbe9
- (void)_setTempImage:(id)image;	// 0x3160ddb1
- (void)_startDeletterboxTaskForImage:(id)image;	// 0x3160d9f5
- (void)_startImageProcessingTaskForImage:(id)image;	// 0x3160ff35
- (id)_subtitleAttributes;	// 0x316106e5
- (id)_titleAttributes;	// 0x31610c85
- (void)_updateArtwork;	// 0x3161041d
- (void)_updateDefaultArtwork;	// 0x3160e651
- (void)_updateDeferredArtwork;	// 0x3160fd99
- (void)_updateTextLayerOpacity;	// 0x3160e1b1
- (BOOL)_usesDeferredArtworkLoading;	// 0x3160d7a5
// converted property getter: - (BOOL)alwaysShowTitles;	// 0x3160d69d
- (id)badge;	// 0x3160d70d
// converted property getter: - (id)badgeImage;	// 0x3160d5f5
// converted property getter: - (float)badgeOpacity;	// 0x3160d625
// converted property getter: - (int)badgePosition;	// 0x3160d605
// converted property getter: - (float)badgeScale;	// 0x3160d615
- (void)controlWasActivated;	// 0x3160f799
- (void)controlWasDeactivated;	// 0x3160f6dd
- (void)controlWasFocused;	// 0x3160e841
- (void)controlWasUnfocused;	// 0x3160e805
// converted property getter: - (float)cornerRadius;	// 0x3160d5c5
// converted property getter: - (BOOL)cropAndFill;	// 0x3160d5d5
// converted property getter: - (float)cropAspectRatio;	// 0x3160d5e5
- (void)dealloc;	// 0x3160fb3d
// converted property getter: - (id)defaultImage;	// 0x3160d4ed
// converted property getter: - (BOOL)deletterboxImage;	// 0x3160d6ed
- (id)description;	// 0x3160f7f5
- (void)drawInContext:(CGContextRef)context;	// 0x316106d9
- (CGRect)focusCursorFrame;	// 0x316121f1
// converted property getter: - (float)focusedBadgeOpacity;	// 0x3160d635
- (void)hideTextLayers;	// 0x3160e7ad
// converted property getter: - (id)image;	// 0x3160d6cd
// converted property getter: - (id)imageProxy;	// 0x3160d52d
- (void)layoutSubcontrols;	// 0x316113dd
// converted property getter: - (int)numberBadgeValue;	// 0x3160d645
// converted property getter: - (BOOL)onlyShowSubtitlesWhenFocused;	// 0x3160d6bd
// converted property getter: - (int)ordinal;	// 0x3160f331
// converted property getter: - (CGColorRef)posterBorderColor;	// 0x3160d4fd
// converted property getter: - (float)posterBorderWidth;	// 0x3160d50d
// converted property getter: - (int)posterStyle;	// 0x3160d51d
- (float)preferredCursorRadius;	// 0x3160d6fd
// converted property getter: - (float)reflectionAmount;	// 0x3160d591
// converted property getter: - (float)reflectionBaseline;	// 0x3160d5a1
- (void)scrollingCompleted;	// 0x3160e771
// converted property setter: - (void)setAlwaysShowTitles:(BOOL)titles;	// 0x3160eafd
- (void)setBadgeImage:(id)image atPosition:(int)position;	// 0x3160f0b1
// converted property setter: - (void)setBadgeOpacity:(float)opacity;	// 0x3160f005
// converted property setter: - (void)setBadgeScale:(float)scale;	// 0x3160f07d
// converted property setter: - (void)setCornerRadius:(float)radius;	// 0x3160f1f9
// converted property setter: - (void)setCropAndFill:(BOOL)fill;	// 0x3160f1bd
// converted property setter: - (void)setCropAspectRatio:(float)ratio;	// 0x3160f175
// converted property setter: - (void)setDefaultImage:(id)image;	// 0x3160f665
// converted property setter: - (void)setDeletterboxImage:(BOOL)image;	// 0x3160d6dd
- (BOOL)setEnableDecoratedImageCache:(BOOL)cache;	// 0x3160d53d
// converted property setter: - (void)setFocusedBadgeOpacity:(float)opacity;	// 0x3160ef8d
// converted property setter: - (void)setImage:(id)image;	// 0x3160e87d
- (void)setImageEdgeAntialiasingEnabled:(BOOL)enabled;	// 0x3160f539
// converted property setter: - (void)setImageProxy:(id)proxy;	// 0x3160f599
- (void)setNonAttributedSubtitle:(id)subtitle;	// 0x3160e93d
- (void)setNonAttributedTitle:(id)title;	// 0x3160ec29
- (void)setNonAttributedTitleWithCrossfade:(id)crossfade;	// 0x3160ebb9
// converted property setter: - (void)setNumberBadgeValue:(int)value;	// 0x3160ecf9
// converted property setter: - (void)setOnlyShowSubtitlesWhenFocused:(BOOL)focused;	// 0x3160d6ad
// converted property setter: - (void)setOrdinal:(int)ordinal;	// 0x3160f36d
// converted property setter: - (void)setPosterBorderColor:(CGColorRef)color;	// 0x3160fd5d
// converted property setter: - (void)setPosterBorderWidth:(float)width;	// 0x3160f631
// converted property setter: - (void)setPosterStyle:(int)style;	// 0x316128d9
// converted property setter: - (void)setReflectionAmount:(float)amount;	// 0x3160f4ed
// converted property setter: - (void)setReflectionBaseline:(float)baseline;	// 0x3160f4b9
// converted property setter: - (void)setSpinnerEnabled:(BOOL)enabled;	// 0x3160f21d
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x3160e9dd
// converted property setter: - (void)setTitle:(id)title;	// 0x3160ece1
// converted property setter: - (void)setTitleVerticalOffset:(float)offset;	// 0x3160eb25
// converted property setter: - (void)setTitleWidthScale:(float)scale;	// 0x3160eb59
- (void)setTitleWithCrossfade:(id)crossfade;	// 0x3160ecc9
// converted property getter: - (BOOL)spinnerEnabled;	// 0x3160d5b1
// converted property getter: - (id)subtitle;	// 0x3160e91d
// converted property getter: - (id)title;	// 0x3160eb99
- (id)titleControl;	// 0x3160d655
// converted property getter: - (float)titleVerticalOffset;	// 0x3160d68d
// converted property getter: - (float)titleWidthScale;	// 0x3160d665
@end

