/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRButtonControl.h"


@interface BRPreviewBrowserControl : BRButtonControl {
}
+ (id)previewBrowser;	// 0x315f30d9
- (BOOL)brEventAction:(id)action;	// 0x315f315d
@end

