/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSString;

@interface BRPreferences : NSObject {
@private
	NSString *_domain;	// 4 = 0x4
}
@property(readonly, retain) NSString *domain;	// G=0x31648729; converted property
+ (id)sharedFrontRowPreferences;	// 0x31648c85
- (id)initWithDomain:(id)domain;	// 0x31648c35
- (BOOL)boolForKey:(id)key;	// 0x316489c5
- (BOOL)boolForKey:(id)key withValueForMissingPrefs:(BOOL)missingPrefs;	// 0x31648979
- (BOOL)canSetPreferencesForKey:(id)key;	// 0x316488b9
- (void)dealloc;	// 0x31648bed
- (id)descriptionForKey:(id)key;	// 0x316488f9
// converted property getter: - (id)domain;	// 0x31648729
- (double)doubleForKey:(id)key;	// 0x31648a11
- (float)floatForKey:(id)key;	// 0x31648a99
- (float)floatForKey:(id)key withValueForMissingPrefs:(float)missingPrefs;	// 0x31648a51
- (int)integerForKey:(id)key;	// 0x31648b29
- (int)integerForKey:(id)key withValueForMissingPrefs:(int)missingPrefs;	// 0x31648ae1
- (id)objectForKey:(id)key;	// 0x31648b71
- (BOOL)setBool:(BOOL)aBool forKey:(id)key;	// 0x31648785
- (BOOL)setDouble:(double)aDouble forKey:(id)key;	// 0x316487d1
- (BOOL)setFloat:(float)aFloat forKey:(id)key;	// 0x31648821
- (BOOL)setInteger:(int)integer forKey:(id)key;	// 0x3164886d
- (BOOL)setObject:(id)object forKey:(id)key;	// 0x31648739
- (id)stringForKey:(id)key;	// 0x31648939
- (void)syncNow;	// 0x31648bb1
@end

