/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@class NSArray;

@interface BRProviderGroup : NSObject {
@private
	NSArray *_providers;	// 4 = 0x4
}
@property(readonly, retain) NSArray *providers;	// G=0x316227b5; converted property
+ (id)groupWithProviders:(id)providers;	// 0x31622c21
- (id)initWithProviders:(id)providers;	// 0x31622c65
- (id)createControlAtGroupIndex:(long)groupIndex currentControl:(id)control requestedBy:(id)by;	// 0x3162294d
- (id)createControlsInGroupRange:(NSRange)groupRange requestedBy:(id)by;	// 0x316228b9
- (long)dataCount;	// 0x31622b8d
- (id)dataForGroupIndex:(long)groupIndex;	// 0x31622b61
- (void)dealloc;	// 0x315a7491
- (long)groupIndexForHash:(id)hash;	// 0x316229a5
- (id)hashForDataAtGroupIndex:(long)groupIndex;	// 0x31622b35
- (id)providerForDataAtGroupIndex:(long)groupIndex providerIndex:(long *)index;	// 0x31622aad
// converted property getter: - (id)providers;	// 0x316227b5
@end

