/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRListControl, BRImageControl, BRResumeMenuControlLayoutManager;

@interface BRResumeMenuControl : BRControl {
@private
	BRListControl *_resumeMenu;	// 40 = 0x28
	BRImageControl *_blurControl;	// 44 = 0x2c
	BRResumeMenuControlLayoutManager *_layoutManager;	// 48 = 0x30
	float _blurOversizeFactor;	// 52 = 0x34
}
- (id)init;	// 0x315b97f5
- (BOOL)brEventAction:(id)action;	// 0x315f366d
- (void)dealloc;	// 0x315b9cad
- (void)layoutSubcontrols;	// 0x315f3701
- (id)list;	// 0x315b9a01
- (id)preferredActionForKey:(id)key;	// 0x315f34ad
- (void)setBlurOversizeFactor:(float)factor;	// 0x315b99dd
- (void)setImage:(id)image;	// 0x315f3599
@end

