/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRMediaHost.h"


__attribute__((visibility("hidden")))
@interface BRRemoteMediaHost : BRMediaHost {
@private
	BOOL _hostFound;	// 44 = 0x2c
	BOOL _hostValid;	// 45 = 0x2d
}
@property(assign) BOOL hostFound;	// G=0x31631409; S=0x31631419; converted property
@property(assign) BOOL hostValid;	// G=0x31631429; S=0x31631439; converted property
// converted property getter: - (BOOL)hostFound;	// 0x31631409
- (id)hostID;	// 0x3163185d
// converted property getter: - (BOOL)hostValid;	// 0x31631429
// converted property setter: - (void)setHostFound:(BOOL)found;	// 0x31631419
// converted property setter: - (void)setHostValid:(BOOL)valid;	// 0x31631439
@end

