/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRInputMethod.h"


__attribute__((visibility("hidden")))
@interface BRRomanInputMethod : BRInputMethod {
}
- (void)_createKeyboardsForTextEntryStyle:(int)textEntryStyle;	// 0x315ff5cd
- (id)isoLanguageCode;	// 0x315ff5bd
- (id)name;	// 0x315ff5b1
- (BOOL)usesCandidateDisplayForKeyboard:(id)keyboard;	// 0x315ff5c9
@end

