/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRXMLMediaAsset.h"


@interface BRRSSMediaAsset : BRXMLMediaAsset {
@private
	BOOL _needsVolumeFading;	// 12 = 0xc
}
@property(assign) BOOL needsVolumeFading;	// G=0x315d09c5; S=0x315d09d5; converted property
+ (id)mediaAssetFromMediaProvider:(id)mediaProvider;	// 0x315d0a3d
- (id)coverArt;	// 0x315d0ab5
- (id)description;	// 0x315d09e5
- (long)duration;	// 0x315d0a75
- (BOOL)hasVideoContent;	// 0x315d0a09
// converted property getter: - (BOOL)needsVolumeFading;	// 0x315d09c5
// converted property setter: - (void)setNeedsVolumeFading:(BOOL)fading;	// 0x315d09d5
@end

