/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRProvider.h"
#import "BackRow-Structs.h"

@class BRTypesetter, NSAttributedString;
@protocol BRControlFactory;

__attribute__((visibility("hidden")))
@interface BRScrollingTextTextProvider : NSObject <BRProvider> {
@private
	BRTypesetter *_typesetter;	// 4 = 0x4
	NSAttributedString *_string;	// 8 = 0x8
	id<BRControlFactory> _factory;	// 12 = 0xc
	CGSize _boxSize;	// 16 = 0x10
}
@property(retain) id attributedString;	// G=0x315f52a9; S=0x315f53fd; converted property
+ (id)providerWithAttributedString:(id)attributedString;	// 0x315f5515
- (id)init;	// 0x315f54b9
- (void)_updateTypesetter;	// 0x315f52cd
// converted property getter: - (id)attributedString;	// 0x315f52a9
- (id)controlFactory;	// 0x315f52b9
- (id)dataAtIndex:(long)index;	// 0x315f5371
- (long)dataCount;	// 0x315f5391
- (void)dealloc;	// 0x315f544d
- (id)hashForDataAtIndex:(long)index;	// 0x315f52c9
// converted property setter: - (void)setAttributedString:(id)string;	// 0x315f53fd
- (void)setTextBoxSize:(CGSize)size;	// 0x315f53b1
@end

