/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRVerticalScrollBarControl, BRListControl, NSAttributedString;

@interface BRScrollingTextBoxControl : BRControl {
@private
	BRListControl *_list;	// 40 = 0x28
	NSAttributedString *_text;	// 44 = 0x2c
	BRVerticalScrollBarControl *_scrollBar;	// 48 = 0x30
	float _textHeightFactor;	// 52 = 0x34
	long _upperFocusLimit;	// 56 = 0x38
	long _lowerFocusLimit;	// 60 = 0x3c
}
@property(retain) NSAttributedString *text;	// G=0x315f3809; S=0x315f3cdd; converted property
@property(assign) float textHeightFactor;	// G=0x315f3829; S=0x315f3819; converted property
- (id)init;	// 0x315f3de1
- (void)_calculateFocusLimitsWithTextBoxSize:(CGSize)textBoxSize;	// 0x315f3991
- (void)_forceSelectionToFocusLimit;	// 0x315f3b25
- (void)_listSelectionChanged:(id)changed;	// 0x315f3b91
- (void)_providerCountChanged:(id)changed;	// 0x315f3961
- (BOOL)brEventAction:(id)action;	// 0x315f3c1d
- (void)dealloc;	// 0x315f3d4d
- (void)layoutSubcontrols;	// 0x315f40f9
// converted property setter: - (void)setText:(id)text;	// 0x315f3cdd
// converted property setter: - (void)setTextHeightFactor:(float)factor;	// 0x315f3819
// converted property getter: - (id)text;	// 0x315f3809
// converted property getter: - (float)textHeightFactor;	// 0x315f3829
@end

