/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRScrollingTextBoxControl, BRHeaderControl, NSAttributedString, NSString, BRPanelControl;

@interface BRScrollingTextControl : BRControl {
@private
	BRHeaderControl *_header;	// 40 = 0x28
	BRScrollingTextBoxControl *_textBox;	// 44 = 0x2c
	BRPanelControl *_buttonGrid;	// 48 = 0x30
	NSAttributedString *_attributedString;	// 52 = 0x34
	long _selectedIndex;	// 56 = 0x38
	NSString *_dialogIdentifier;	// 60 = 0x3c
}
@property(retain) NSAttributedString *attributedString;	// G=0x315f4361; S=0x315f4729; converted property
+ (id)controlWithTitle:(id)title documentPath:(id)path firstButton:(id)button secondButton:(id)button4 thirdButton:(id)button5 defaultFocus:(int)focus;	// 0x315f4811
+ (id)controlWithTitle:(id)title text:(id)text firstButton:(id)button secondButton:(id)button4 thirdButton:(id)button5 defaultFocus:(int)focus;	// 0x315f48f5
+ (int)postControlAsDialogWithTitle:(id)title text:(id)text;	// 0x315f49d9
+ (int)postControlAsDialogWithTitle:(id)title text:(id)text firstButton:(id)button secondButton:(id)button4 thirdButton:(id)button5 defaultFocus:(int)focus;	// 0x315f4c41
- (id)init;	// 0x315f4a2d
- (id)_dialogIdentifier;	// 0x315f4381
- (id)_paragraphTextAttributes;	// 0x315f50a1
- (long)_selectedIndex;	// 0x315f4371
- (void)_setDialogIdentifier:(id)identifier;	// 0x315f4401
- (void)_setSelectedIndexWithControl:(id)control;	// 0x315f4439
- (void)addButtonWithTitle:(id)title isDefaultFocus:(BOOL)focus;	// 0x315f456d
// converted property getter: - (id)attributedString;	// 0x315f4361
- (BOOL)brEventAction:(id)action;	// 0x315f44d9
- (void)dealloc;	// 0x315f4791
- (void)layoutSubcontrols;	// 0x315f4de9
// converted property setter: - (void)setAttributedString:(id)string;	// 0x315f4729
- (void)setDocumentPath:(id)path;	// 0x315f4711
- (void)setDocumentPath:(id)path encoding:(unsigned)encoding;	// 0x315f4635
- (void)setSelectionHandler:(id)handler;	// 0x315f4479
- (void)setText:(id)text;	// 0x315f4bc9
- (void)setTitle:(id)title;	// 0x315f475d
@end

