/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRFadeMaskLayer, ScrollAnimationDelegate;

@interface BRScrollControl : BRControl {
@private
	BRControl *_content;	// 40 = 0x28
	BRControl *_topFade;	// 44 = 0x2c
	BRControl *_bottomFade;	// 48 = 0x30
	BRControl *_leftFade;	// 52 = 0x34
	BRControl *_rightFade;	// 56 = 0x38
	BRFadeMaskLayer *_mask;	// 60 = 0x3c
	ScrollAnimationDelegate *_animationDelegate;	// 64 = 0x40
	int _scrollDirection;	// 68 = 0x44
	int _mode;	// 72 = 0x48
	int _defaultAnimationMode;	// 76 = 0x4c
	int _fastAnimationMode;	// 80 = 0x50
	BOOL _switchAnimationModes;	// 84 = 0x54
	float _edgeFadePercent;	// 88 = 0x58
	float _extraBottomSpace;	// 92 = 0x5c
	float _extraTopSpace;	// 96 = 0x60
	float _extraLeftSpace;	// 100 = 0x64
	float _extraRightSpace;	// 104 = 0x68
	BOOL _scrollPointSet;	// 108 = 0x6c
	BOOL _constrainAllContentToEdges;	// 109 = 0x6d
	BOOL _useRealMasks;	// 110 = 0x6e
	BOOL _followsFocus;	// 111 = 0x6f
	BOOL _repeatActive;	// 112 = 0x70
}
@property(assign) int animationMode;	// G=0x316710f9; S=0x31595cd1; converted property
@property(assign) BOOL constrainAllContentToEdges;	// G=0x316710e9; S=0x316710d1; converted property
@property(retain) BRControl *content;	// G=0x31671091; S=0x31671841; converted property
@property(assign) float edgeFadePercentage;	// G=0x316710c1; S=0x316715dd; converted property
@property(assign) BOOL followsFocus;	// G=0x316710a1; S=0x31595e75; converted property
@property(assign) int scrollDirection;	// G=0x31671121; S=0x31671109; converted property
@property(assign) BOOL useRealMasks;	// G=0x316710b1; S=0x315b99b5; converted property
- (id)init;	// 0x31595bc5
- (BOOL)_animatingPositionChange;	// 0x3167127d
- (void)_attemptToRemoveFadeMask;	// 0x315b9bc5
- (id)_bottomFadeFilters;	// 0x31596d9d
- (float)_calculateXPositionForPlane:(CGPoint)plane halfScrollerWidth:(float)width halfPlaneWidth:(float)width3;	// 0x31671a69
- (float)_calculateYPositionForPlane:(CGPoint)plane halfScrollerHeight:(float)height halfPlaneHeight:(float)height3;	// 0x316719f5
- (void)_enlargeScrollPlaneHeight:(CGPoint)height oldPosition:(CGPoint)position;	// 0x31671bf1
- (void)_enlargeScrollPlaneWidth:(CGPoint)width oldPosition:(CGPoint)position;	// 0x31671b41
- (id)_fadeMaskForBounds:(CGSize)bounds;	// 0x315b9a11
- (void)_focusChanged:(id)changed;	// 0x3167113d
- (id)_leftFadeFilters;	// 0x31672f89
- (void)_minimizeVisiblePlaneArea;	// 0x31671221
- (id)_parentScrollControl;	// 0x31671139
- (id)_rightFadeFilters;	// 0x31672941
- (void)_scrollPoint:(CGPoint)point fromControl:(id)control;	// 0x316719b5
- (void)_scrollRect:(CGRect)rect fromControl:(id)control;	// 0x31671941
- (BOOL)_setPlanePosition:(CGPoint)position;	// 0x31672c51
- (id)_topFadeFilters;	// 0x31596ec5
- (void)_updateEdgeFading;	// 0x31596d45
- (void)_updateFocusNotifications;	// 0x31671181
- (void)_updateHorizontalEdgeFading;	// 0x31671ca1
- (void)_updateScrollPositionForFocus;	// 0x31672601
- (void)_updateVerticalEdgeFading;	// 0x316720d1
- (CGRect)_visibleRectOfControl:(id)control;	// 0x31672775
// converted property getter: - (int)animationMode;	// 0x316710f9
- (BOOL)autoScrolling;	// 0x316716b9
- (BOOL)brEventAction:(id)action;	// 0x31671725
// converted property getter: - (BOOL)constrainAllContentToEdges;	// 0x316710e9
// converted property getter: - (id)content;	// 0x31671091
- (void)controlWasActivated;	// 0x31671561
- (void)controlWasDeactivated;	// 0x31671525
- (void)dealloc;	// 0x315a6305
// converted property getter: - (float)edgeFadePercentage;	// 0x316710c1
// converted property getter: - (BOOL)followsFocus;	// 0x316710a1
- (void)layoutSubcontrols;	// 0x31672a3d
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void *)context;	// 0x316714ed
// converted property getter: - (int)scrollDirection;	// 0x31671121
- (void)scrollToControl:(id)control;	// 0x3167252d
- (void)scrollToPoint:(CGPoint)point;	// 0x3167168d
- (void)scrollToRect:(CGRect)rect;	// 0x3167163d
- (BOOL)scrolling;	// 0x31671701
- (void)scrollingCompleted;	// 0x316714ad
// converted property setter: - (void)setAnimationMode:(int)mode;	// 0x31595cd1
// converted property setter: - (void)setConstrainAllContentToEdges:(BOOL)edges;	// 0x316710d1
// converted property setter: - (void)setContent:(id)content;	// 0x31671841
- (void)setDefaultAnimationMode:(int)mode fastScrollingAnimationMode:(int)mode2;	// 0x3167159d
// converted property setter: - (void)setEdgeFadePercentage:(float)percentage;	// 0x316715dd
// converted property setter: - (void)setFollowsFocus:(BOOL)focus;	// 0x31595e75
// converted property setter: - (void)setScrollDirection:(int)direction;	// 0x31671109
// converted property setter: - (void)setUseRealMasks:(BOOL)masks;	// 0x315b99b5
// converted property getter: - (BOOL)useRealMasks;	// 0x316710b1
@end

