/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRSingleton.h"


@interface BRSettingsFacade : BRSingleton {
}
@property(assign) BOOL UISoundsEnabled;	// G=0x3164a531; S=0x3164a4b1; converted property
@property(assign) int audioFormat;	// G=0x3158c33d; S=0x3164a061; converted property
@property(assign) BOOL crashReportingEnabled;	// G=0x3164a941; S=0x3164a8c5; converted property
@property(retain) id defaultAudioLanguage;	// G=0x3164a355; S=0x3164a2fd; converted property
@property(retain) id defaultSubtitleLanguage;	// G=0x3164a3e5; S=0x3164a38d; converted property
@property(assign) int favoritesSortMode;	// G=0x31649e99; S=0x31649e5d; converted property
@property(retain) id keyboardLanguageKeys;	// G=0x316494ad; S=0x31649475; converted property
@property(retain) id lastUsedKeyboardLanguage;	// G=0x316493d9; S=0x316493a1; converted property
@property(retain) id marimbaSlideshowDefaultMusicPlaylistID;	// G=0x31649519; S=0x316494e1; converted property
@property(retain) id marimbaSlideshowDefaultMusicServerID;	// G=0x31649585; S=0x3164954d; converted property
@property(retain) id marimbaSlideshowStyle;	// G=0x316496b5; S=0x316496f5; converted property
@property(assign) int musicRepeatMode;	// G=0x315ba459; S=0x3164a221; converted property
@property(assign) BOOL musicVolumeControlEnabled;	// G=0x3164a1e5; S=0x3164a15d; converted property
@property(assign) BOOL playlistsEverywhereEnabled;	// G=0x31649fe9; S=0x31649fad; converted property
@property(assign) BOOL preferHDVideo;	// G=0x31649f35; S=0x31649ed5; converted property
@property(assign) BOOL screenSaverAllowedOverMusic;	// G=0x315bb939; S=0x31649f71; converted property
@property(assign) BOOL slideshowPanAndZoom;	// G=0x31649b89; S=0x31649b4d; converted property
@property(assign) BOOL slideshowPlayMusic;	// G=0x31649b11; S=0x31649ad5; converted property
@property(assign) BOOL slideshowRepeat;	// G=0x31649cf1; S=0x31649cb5; converted property
@property(assign) int slideshowSecondsPerSlide;	// G=0x31649d91; S=0x31649d55; converted property
@property(retain) id slideshowSelectedPlaylistName;	// G=0x316498d5; S=0x3164989d; converted property
@property(retain) id slideshowSelectedTransitionName;	// G=0x31649841; S=0x31649805; converted property
@property(assign) BOOL slideshowShuffleMusic;	// G=0x31649c01; S=0x31649bc5; converted property
@property(assign) BOOL slideshowShufflePhotos;	// G=0x31649c79; S=0x31649c3d; converted property
@property(retain) id slideshowTransitionDirection;	// G=0x31649789; S=0x3164974d; converted property
@property(assign) int videoClosedCaptionMode;	// G=0x315a92f5; S=0x3164a445; converted property
+ (void)setSingleton:(id)singleton;	// 0x3158c1c9
+ (id)singleton;	// 0x3158c0f9
// converted property getter: - (BOOL)UISoundsEnabled;	// 0x3164a531
- (id)_availableDefaultAVLanguages;	// 0x31648cfd
- (long)_preferredTrackIDForMedia:(id)media forType:(id)type;	// 0x3164904d
- (void)_removeSavedPreferredTrackIDsForType:(id)type;	// 0x31648dd5
- (void)_savePreferredTrackID:(long)anId forMedia:(id)media forType:(id)type;	// 0x31648e41
- (void)_setSlideshowSelectedPlaylistName:(id)name forHost:(id)host;	// 0x316491b5
- (id)_slideshowSelectedPlaylistNameForHost:(id)host;	// 0x316490e5
// converted property getter: - (int)audioFormat;	// 0x3158c33d
- (id)availableDefaultAudioLanguages;	// 0x3164a41d
- (id)availableDefaultSubtitleLanguages;	// 0x3164a431
- (BOOL)bootedFromRecoveryPartition;	// 0x31648cf5
// converted property getter: - (BOOL)crashReportingEnabled;	// 0x3164a941
- (BOOL)crashReportingPreferenceSet;	// 0x3164a025
// converted property getter: - (id)defaultAudioLanguage;	// 0x3164a355
// converted property getter: - (id)defaultSubtitleLanguage;	// 0x3164a3e5
// converted property getter: - (int)favoritesSortMode;	// 0x31649e99
- (void)flushDiskChanges;	// 0x3158dcbd
- (id)hwDeviceName;	// 0x316492f1
- (BOOL)keyboardLanguageEnabled:(id)enabled;	// 0x31649441
// converted property getter: - (id)keyboardLanguageKeys;	// 0x316494ad
// converted property getter: - (id)lastUsedKeyboardLanguage;	// 0x316493d9
// converted property getter: - (id)marimbaSlideshowDefaultMusicPlaylistID;	// 0x31649519
// converted property getter: - (id)marimbaSlideshowDefaultMusicServerID;	// 0x31649585
// converted property getter: - (id)marimbaSlideshowStyle;	// 0x316496b5
// converted property getter: - (int)musicRepeatMode;	// 0x315ba459
- (float)musicVolume;	// 0x3164a121
// converted property getter: - (BOOL)musicVolumeControlEnabled;	// 0x3164a1e5
- (id)parentalControlsPasscode;	// 0x31649e25
- (int)parentalControlsYTMode;	// 0x31649ded
// converted property getter: - (BOOL)playlistsEverywhereEnabled;	// 0x31649fe9
// converted property getter: - (BOOL)preferHDVideo;	// 0x31649f35
- (long)preferredAlternateAudioTrackIDForMedia:(id)media;	// 0x3164a291
- (long)preferredSubtitleTrackIDForMedia:(id)media;	// 0x3164a2dd
- (void)resetAllSettings;	// 0x3164a59d
- (BOOL)saveConfiguration:(id)configuration;	// 0x31648cf9
- (void)saveMusicVolume:(float)volume;	// 0x3164a0b9
- (void)savePreferredAlternateAudioTrackID:(long)anId forMedia:(id)media;	// 0x3164a265
- (void)savePreferredSubtitleTrackID:(long)anId forMedia:(id)media;	// 0x3164a2b1
// converted property getter: - (BOOL)screenSaverAllowedOverMusic;	// 0x315bb939
// converted property setter: - (void)setAudioFormat:(int)format;	// 0x3164a061
// converted property setter: - (void)setCrashReportingEnabled:(BOOL)enabled;	// 0x3164a8c5
// converted property setter: - (void)setDefaultAudioLanguage:(id)language;	// 0x3164a2fd
// converted property setter: - (void)setDefaultSubtitleLanguage:(id)language;	// 0x3164a38d
// converted property setter: - (void)setFavoritesSortMode:(int)mode;	// 0x31649e5d
- (void)setHWDeviceName:(id)name;	// 0x3164a9a5
- (void)setKeyboardLanguageEnabled:(id)enabled enabled:(BOOL)enabled2;	// 0x3164940d
// converted property setter: - (void)setKeyboardLanguageKeys:(id)keys;	// 0x31649475
// converted property setter: - (void)setLastUsedKeyboardLanguage:(id)language;	// 0x316493a1
// converted property setter: - (void)setMarimbaSlideshowDefaultMusicPlaylistID:(id)anId;	// 0x316494e1
// converted property setter: - (void)setMarimbaSlideshowDefaultMusicServerID:(id)anId;	// 0x3164954d
// converted property setter: - (void)setMarimbaSlideshowStyle:(id)style;	// 0x316496f5
// converted property setter: - (void)setMusicRepeatMode:(int)mode;	// 0x3164a221
// converted property setter: - (void)setMusicVolumeControlEnabled:(BOOL)enabled;	// 0x3164a15d
// converted property setter: - (void)setPlaylistsEverywhereEnabled:(BOOL)enabled;	// 0x31649fad
// converted property setter: - (void)setPreferHDVideo:(BOOL)video;	// 0x31649ed5
// converted property setter: - (void)setScreenSaverAllowedOverMusic:(BOOL)music;	// 0x31649f71
// converted property setter: - (void)setSlideshowPanAndZoom:(BOOL)zoom;	// 0x31649b4d
// converted property setter: - (void)setSlideshowPlayMusic:(BOOL)music;	// 0x31649ad5
// converted property setter: - (void)setSlideshowRepeat:(BOOL)repeat;	// 0x31649cb5
// converted property setter: - (void)setSlideshowSecondsPerSlide:(int)slide;	// 0x31649d55
// converted property setter: - (void)setSlideshowSelectedPlaylistName:(id)name;	// 0x3164989d
// converted property setter: - (void)setSlideshowSelectedTransitionName:(id)name;	// 0x31649805
// converted property setter: - (void)setSlideshowShuffleMusic:(BOOL)music;	// 0x31649bc5
// converted property setter: - (void)setSlideshowShufflePhotos:(BOOL)photos;	// 0x31649c3d
// converted property setter: - (void)setSlideshowTransitionDirection:(id)direction;	// 0x3164974d
// converted property setter: - (void)setUISoundsEnabled:(BOOL)enabled;	// 0x3164a4b1
// converted property setter: - (void)setVideoClosedCaptionMode:(int)mode;	// 0x3164a445
// converted property getter: - (BOOL)slideshowPanAndZoom;	// 0x31649b89
// converted property getter: - (BOOL)slideshowPlayMusic;	// 0x31649b11
- (id)slideshowPlaybackOptions;	// 0x3164972d
- (id)slideshowPlaylists;	// 0x31649909
// converted property getter: - (BOOL)slideshowRepeat;	// 0x31649cf1
// converted property getter: - (int)slideshowSecondsPerSlide;	// 0x31649d91
// converted property getter: - (id)slideshowSelectedPlaylistName;	// 0x316498d5
// converted property getter: - (id)slideshowSelectedTransitionName;	// 0x31649841
// converted property getter: - (BOOL)slideshowShuffleMusic;	// 0x31649c01
// converted property getter: - (BOOL)slideshowShufflePhotos;	// 0x31649c79
// converted property getter: - (id)slideshowTransitionDirection;	// 0x31649789
- (id)slideshowTransitionNames;	// 0x31648cd5
- (BOOL)slideshowTransitionsDisabled;	// 0x31648cd9
- (BOOL)slideshowTransitionsRandom;	// 0x31648cdd
- (id)syncHostName;	// 0x31649369
- (void)updateHostID:(id)anId to:(id)to;	// 0x3164a809
- (id)versionEFI;	// 0x31648ce9
- (id)versionGF;	// 0x31648cf1
- (id)versionIR;	// 0x31648ced
- (id)versionOS;	// 0x31648ce1
- (id)versionOSBuild;	// 0x31648ce5
- (id)versionSoftware;	// 0x3158f455
- (id)versionSoftwareBuild;	// 0x3158c339
// converted property getter: - (int)videoClosedCaptionMode;	// 0x315a92f5
@end

