/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRImageControl;

__attribute__((visibility("hidden")))
@interface BRShimmerControl : BRControl {
@private
	BRControl *_base;	// 40 = 0x28
	BRImageControl *_shimmer;	// 44 = 0x2c
	float _offset;	// 48 = 0x30
}
@property(assign) float offset;	// G=0x316585b9; S=0x316586c5; converted property
+ (id)shimmerWithOffset:(float)offset;	// 0x31658729
- (id)init;	// 0x31658711
- (id)initWithOffset:(float)offset;	// 0x31658781
- (id)_calculateKeyTimes;	// 0x316585c9
- (id)_calculatePositionValues;	// 0x316588dd
- (void)dealloc;	// 0x31658669
- (void)layoutSubcontrols;	// 0x316589a5
// converted property getter: - (float)offset;	// 0x316585b9
// converted property setter: - (void)setOffset:(float)offset;	// 0x316586c5
@end

