/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class NSString;

@interface BRSimpleMenuItem : NSObject {
@private
	NSString *_title;	// 4 = 0x4
	NSString *_rightJustifiedText;	// 8 = 0x8
	int _titlePosition;	// 12 = 0xc
	int _menuItemType;	// 16 = 0x10
}
@property(readonly, assign) int menuItemType;	// G=0x315d0c6d; converted property
@property(readonly, retain) NSString *rightJustifiedText;	// G=0x315d0c4d; converted property
@property(readonly, retain) NSString *title;	// G=0x315d0c3d; converted property
@property(readonly, assign) int titlePosition;	// G=0x315d0c5d; converted property
+ (id)simpleMenuItemWithTitle:(id)title rightJustifiedText:(id)text titlePosition:(int)position menuItemType:(int)type;	// 0x315d0ca1
+ (id)simpleMenuItemWithTitle:(id)title titlePosition:(int)position menuItemType:(int)type;	// 0x315d0cf1
- (id)initWithTitle:(id)title rightJustifiedText:(id)text titlePosition:(int)position menuItemType:(int)type;	// 0x315d0d9d
- (id)initWithTitle:(id)title titlePosition:(int)position menuItemType:(int)type;	// 0x315d0c7d
- (void)dealloc;	// 0x315d0d41
// converted property getter: - (int)menuItemType;	// 0x315d0c6d
// converted property getter: - (id)rightJustifiedText;	// 0x315d0c4d
// converted property getter: - (id)title;	// 0x315d0c3d
// converted property getter: - (int)titlePosition;	// 0x315d0c5d
@end

