/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRBaseMenuItemLayerPopulator.h"


@interface BRSongMenuItemPopulator : BRBaseMenuItemLayerPopulator {
}
+ (BOOL)canHandleObject:(id)object;	// 0x3161fa15
- (id)menuItem;	// 0x3161f795
- (float)menuItemHeightForObject:(id)object delegate:(id)delegate;	// 0x3161f731
@end

