/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRSpecialKeyRow : BRControl {
}
- (void)layoutSubcontrols;	// 0x31689049
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x3168927d
@end

