/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRPhotoMediaAsset.h"
#import "BRATVMediaItem.h"


@interface BRStreamingPhotoAsset : BRPhotoMediaAsset <BRATVMediaItem> {
@private
	ATVMediaItemRef _mediaItem;	// 36 = 0x24
	ATVDataClientRef _dataClient;	// 40 = 0x28
	BOOL _useForScreenSaver;	// 44 = 0x2c
}
@property(assign) BOOL useForScreenSaver;	// G=0x31685761; S=0x31685751; converted property
+ (id)assetWithATVMediaItem:(ATVMediaItemRef)atvmediaItem dataClient:(ATVDataClientRef)client;	// 0x31685b21
- (id)initWithATVMediaItem:(ATVMediaItemRef)atvmediaItem dataClient:(ATVDataClientRef)client;	// 0x31685a81
- (CGRect)_paddedFaceRectFromFaceRect:(CGRect)faceRect;	// 0x31685781
- (id)dateTaken;	// 0x31685a4d
- (void)dealloc;	// 0x31685b59
- (CGRect)faceRectForFaceCollectionID:(id)faceCollectionID;	// 0x31685ba9
- (id)faces;	// 0x316859cd
- (id)imageProxy;	// 0x31685a01
- (BOOL)isLocal;	// 0x3168574d
- (ATVMediaItemRef)mediaItemRef;	// 0x31685771
// converted property setter: - (void)setUseForScreenSaver:(BOOL)screenSaver;	// 0x31685751
- (id)subImageProxyWithRect:(CGRect)rect;	// 0x31685969
// converted property getter: - (BOOL)useForScreenSaver;	// 0x31685761
@end

