/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRPanelControl.h"
#import "BackRow-Structs.h"

@class NSDictionary, NSArray;

@interface BRTabControl : BRPanelControl {
@private
	int _selectedTabIndex;	// 68 = 0x44
	float _scaledTextPadding;	// 72 = 0x48
	float _scaledPreferredHeight;	// 76 = 0x4c
	int _tabBeingDeselected;	// 80 = 0x50
	id _tabControlDelegate;	// 84 = 0x54
	NSArray *_greyImages;	// 88 = 0x58
	NSArray *_blackImages;	// 92 = 0x5c
	NSArray *_blueImages;	// 96 = 0x60
	NSDictionary *_tabItemLabelAttributes;	// 100 = 0x64
}
@property(assign) id tabControlDelegate;	// G=0x315f5ea9; S=0x315f5eb9; converted property
+ (id)fullSizeTabControl;	// 0x315f73e5
+ (id)menuTabControl;	// 0x315f71dd
- (id)init;	// 0x315f7651
- (id)_centerTabImagesFromImages:(id)images;	// 0x315f6479
- (void)_focusChanged:(id)changed;	// 0x315f5ed9
- (id)_imagesForTabItem:(id)tabItem;	// 0x315f609d
- (id)_leftTabImagesFromImages:(id)images;	// 0x315f64f5
- (void)_loadTabImages;	// 0x315f6691
- (id)_rightTabImagesFromImages:(id)images;	// 0x315f63a5
- (void)_updateFocusNotifications;	// 0x315f5f05
- (void)_updateTabItemNames:(int)names;	// 0x315f5f91
- (void)addTabItem:(id)item;	// 0x315f70c5
- (void)addTabItems:(id)items;	// 0x315f6e99
- (void)controlWasFocused;	// 0x315f69a1
- (void)controlWasUnfocused;	// 0x315f68f9
- (void)dealloc;	// 0x315f7135
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x315f6a49
- (void)insertTabItem:(id)item atIndex:(int)index;	// 0x315f749d
- (void)removeAllTabItems;	// 0x315f6e81
- (void)removeTabItem:(id)item;	// 0x315f6db1
- (void)selectNextTabItem;	// 0x315f6ab9
- (void)selectPreviousTabItem;	// 0x315f6b29
- (void)selectTabItem:(id)item;	// 0x315f6bd1
- (void)selectTabItemAtIndex:(int)index;	// 0x315f6b75
- (id)selectedTabItem;	// 0x315f6d5d
- (int)selectedTabItemIndex;	// 0x315f5ec9
- (void)setScaledPreferredHeight:(float)height;	// 0x315f5e99
- (void)setScaledTextPadding:(float)padding;	// 0x315f5e89
// converted property setter: - (void)setTabControlDelegate:(id)delegate;	// 0x315f5eb9
- (void)setTabItemLabelAttributes:(id)attributes;	// 0x315f70fd
- (void)setTabItemNonSelectedImages:(id)images;	// 0x315f65a1
- (void)setTabItemSelectedInFocusImages:(id)focusImages;	// 0x315f6641
- (void)setTabItemSelectedNonFocusedImages:(id)images;	// 0x315f65f1
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315f7295
// converted property getter: - (id)tabControlDelegate;	// 0x315f5ea9
- (int)tabItemCount;	// 0x315f6d8d
@end

