/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRScrollControl, BRTabControl, NSMutableString, BRTextControl, BRInputMethod, BRKeyboard, BRCursorControl, NSArray, BRDeviceKeyboardMessage, BRTextFieldControl, BRRoundRectOutlineLayer, BRTextFieldBackgroundLayer, NSAttributedString;

@interface BRTextEntryControl : BRControl {
@private
	int _textEntryStyle;	// 40 = 0x28
	BRInputMethod *_inputMethod;	// 44 = 0x2c
	BRKeyboard *_activeKeyboard;	// 48 = 0x30
	BRControl *_roundRectBackground;	// 52 = 0x34
	BRRoundRectOutlineLayer *_roundRectOutline;	// 56 = 0x38
	BRControl *_candidatesBackground;	// 60 = 0x3c
	BRScrollControl *_candidatesKeysContainer;	// 64 = 0x40
	BRScrollControl *_keyboardContainer;	// 68 = 0x44
	BRControl *_actionKeysContainer;	// 72 = 0x48
	BRTextFieldBackgroundLayer *_textFieldBackground;	// 76 = 0x4c
	BRTextControl *_textFieldLabel;	// 80 = 0x50
	NSAttributedString *_textFieldLabelString;	// 84 = 0x54
	BRTextFieldControl *_textField;	// 88 = 0x58
	BRTabControl *_tabControl;	// 92 = 0x5c
	BRCursorControl *_cursor;	// 96 = 0x60
	NSArray *_customizedTextFieldControls;	// 100 = 0x64
	BRDeviceKeyboardMessage *_deviceKeyboardMessage;	// 104 = 0x68
	BRKeyboard *_popupKeyboard;	// 108 = 0x6c
	CGColorRef _popupBackgroundColor;	// 112 = 0x70
	CGColorRef _popupBorderColor;	// 116 = 0x74
	int _popupShadowStyle;	// 120 = 0x78
	BOOL _constrainCursorToPopupKeyboard;	// 124 = 0x7c
	BRScrollControl *_popupKeyboardControl;	// 128 = 0x80
	BRControl *_previouslyFocusedRow;	// 132 = 0x84
	int _previouslySelectedCharacterKeyIndex;	// 136 = 0x88
	NSMutableString *_userEnteredText;	// 140 = 0x8c
	BOOL _showUserEnteredText;	// 144 = 0x90
	BOOL _textFieldIsInternal;	// 145 = 0x91
	BOOL _shouldWrapHorizontally;	// 146 = 0x92
	BOOL _shouldWrapVertically;	// 147 = 0x93
	BOOL _clientHasSpecifiedHorizontalWrapping;	// 148 = 0x94
	BOOL _clientHasSpecifiedVerticalWrapping;	// 149 = 0x95
}
@property(assign) BOOL canWrapHorizontally;	// G=0x31601589; S=0x31601545; converted property
@property(assign) BOOL canWrapVertically;	// G=0x31601521; S=0x316014dd; converted property
@property(retain) BRTabControl *tabControl;	// G=0x315ff919; S=0x3160142d; converted property
@property(assign) int textEntryStyle;	// G=0x315ff8f9; S=0x315afbb5; converted property
@property(retain) BRTextFieldControl *textField;	// G=0x315ff909; S=0x316015f9; converted property
@property(assign) id textFieldDelegate;	// G=0x316013d5; S=0x315b00cd; converted property
- (id)init;	// 0x315af1b9
- (id)initWithTextEntryStyle:(int)textEntryStyle;	// 0x315af18d
- (id)initWithTextEntryStyle:(int)textEntryStyle textField:(id)field;	// 0x31601f05
- (void)_addActionKeysRowForKeyboard:(id)keyboard;	// 0x31601b81
- (void)_addCustomizedTextFieldControls;	// 0x316017b5
- (void)_addMainKeyboardContainerForKeyboard:(id)keyboard;	// 0x31601d19
- (void)_addOrRemoveCandidatesContainer:(id)container;	// 0x31602451
- (id)_bestKeyboardLanguage:(int)language;	// 0x315ffedd
- (void)_customizeTextEntryControls;	// 0x31601851
- (void)_finalizeControlWasFocused;	// 0x31600085
- (void)_generateKeyEventWithCharacters:(id)characters;	// 0x31602ac1
- (void)_handleCharacterSelectionEvent:(id)event;	// 0x31600bd9
- (void)_handleCustomActionKeyEvent:(id)event;	// 0x31600c39
- (void)_handlePopupKeyboardEvent;	// 0x31602b8d
- (void)_inputActionAppendCandidate:(id)candidate;	// 0x3160098d
- (void)_inputActionAppendText:(id)text;	// 0x316009e9
- (void)_inputActionClearText:(id)text;	// 0x316008d5
- (void)_inputActionDeleteText:(id)text;	// 0x316029b5
- (void)_inputActionEscape:(id)escape;	// 0x31600285
- (void)_inputActionSwitchInputMethod:(id)method;	// 0x316002e5
- (void)_inputActionSwitchKeyboard:(id)keyboard;	// 0x316004b5
- (void)_invokeInputActionWithDictionary:(id)dictionary;	// 0x316028d1
- (BOOL)_keyboardFocusIsAtEdge:(int)edge;	// 0x31600175
- (id)_keyboardMappingData;	// 0x316034ed
- (void)_removeActionKeysRow;	// 0x31601b29
- (void)_removeCustomizedTextFieldControls;	// 0x31601755
- (void)_removePopupKeyboard;	// 0x31600ac9
- (void)_setActiveKeyboard:(id)keyboard;	// 0x31601ed9
- (void)_wrapAroundEdge:(int)edge;	// 0x31600c81
- (void)addSelectionHandlerForControl:(id)control forKeyboard:(id)keyboard;	// 0x315ffdc9
- (BOOL)brEventAction:(id)action;	// 0x315b0749
// converted property getter: - (BOOL)canWrapHorizontally;	// 0x31601589
// converted property getter: - (BOOL)canWrapVertically;	// 0x31601521
- (void)controlWasFocused;	// 0x3160011d
- (void)controlWasUnfocused;	// 0x31600049
- (void)dealloc;	// 0x315b3971
- (void)deviceKeyboardClose;	// 0x315ffd4d
- (void)deviceKeyboardMessageHandler:(id)handler;	// 0x315ff949
- (void)deviceKeyboardUpdate:(BOOL)update;	// 0x315ffbfd
- (void)layoutSubcontrols;	// 0x31601fbd
- (void)reset;	// 0x316012c9
- (void)setBackgroundColor:(CGColorRef)color;	// 0x315ffebd
// converted property setter: - (void)setCanWrapHorizontally:(BOOL)horizontally;	// 0x31601545
// converted property setter: - (void)setCanWrapVertically:(BOOL)vertically;	// 0x316014dd
- (void)setConstrainCursorToPopupKeyboard:(BOOL)popupKeyboard;	// 0x315ff939
- (void)setDeviceKeyboardTitle:(id)title subText:(id)text;	// 0x316015ad
- (void)setFocusToGlyphNamed:(id)glyphNamed;	// 0x31601135
- (void)setInitialText:(id)text;	// 0x31601369
- (void)setOutlineColor:(CGColorRef)color;	// 0x315ffe9d
- (void)setPopupBackgroundColor:(CGColorRef)color;	// 0x316034bd
- (void)setPopupOutlineColor:(CGColorRef)color;	// 0x3160348d
- (void)setPopupShadowStyle:(int)style;	// 0x315ff929
- (void)setShowUserEnteredText:(BOOL)text;	// 0x316013f5
// converted property setter: - (void)setTabControl:(id)control;	// 0x3160142d
// converted property setter: - (void)setTextEntryStyle:(int)style;	// 0x315afbb5
// converted property setter: - (void)setTextField:(id)field;	// 0x316015f9
// converted property setter: - (void)setTextFieldDelegate:(id)delegate;	// 0x315b00cd
- (void)setTextFieldLabel:(id)label;	// 0x315b00ed
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x3160241d
- (void)startSpinning;	// 0x315b09ed
- (void)stopSpinning;	// 0x315b0a35
// converted property getter: - (id)tabControl;	// 0x315ff919
// converted property getter: - (int)textEntryStyle;	// 0x315ff8f9
// converted property getter: - (id)textField;	// 0x315ff909
// converted property getter: - (id)textFieldDelegate;	// 0x316013d5
@end

