/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BRController.h"

@class NSTimer, BRWaitPromptControl;

@interface BRTextWithSpinnerController : BRController {
@private
	NSTimer *_revealTimer;	// 56 = 0x38
	double _revealInterval;	// 60 = 0x3c
	BRWaitPromptControl *_prompt;	// 68 = 0x44
	BOOL _isNetworkDependent;	// 72 = 0x48
}
@property(readonly, assign) BOOL isNetworkDependent;	// G=0x315aae15; converted property
- (id)initWithTitle:(id)title text:(id)text;	// 0x315aada9
- (id)initWithTitle:(id)title text:(id)text isNetworkDependent:(BOOL)dependent;	// 0x315aadd5
- (id)initWithTitle:(id)title text:(id)text isNetworkDependent:(BOOL)dependent revealAfter:(double)after;	// 0x315cc629
- (id)initWithTitle:(id)title text:(id)text revealAfter:(double)after;	// 0x315cc5ad
- (void)_checkActivationState:(id)state;	// 0x315cc4d9
- (void)controlWasActivated;	// 0x315ab209
- (void)controlWasDeactivated;	// 0x315cc5d9
- (void)dealloc;	// 0x315ab761
// converted property getter: - (BOOL)isNetworkDependent;	// 0x315aae15
- (void)setIcon:(id)icon horizontalOffset:(float)offset kerningFactor:(float)factor;	// 0x315cc4d5
@end

