/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRMenuController.h"

@class BRTextControl, BRTextEntryControl;

@interface BRTextEntryController : BRMenuController {
@private
	BRTextEntryControl *_editor;	// 100 = 0x64
	BRTextControl *_footnoteText;	// 104 = 0x68
}
@property(readonly, retain) BRTextEntryControl *editor;	// G=0x31612ef1; converted property
- (id)init;	// 0x31613069
- (id)initWithTextEntryStyle:(int)textEntryStyle;	// 0x3161316d
- (void)dealloc;	// 0x31613125
// converted property getter: - (id)editor;	// 0x31612ef1
- (BOOL)isValidAfterDataUpdate;	// 0x31612f01
- (void)layoutSubcontrols;	// 0x31613245
- (void)reset;	// 0x31612f85
- (void)setFocusToGlyphNamed:(id)glyphNamed;	// 0x31612fc9
- (void)setFootnoteText:(id)text withAttributes:(id)attributes;	// 0x31612f05
- (void)setInitialTextEntryText:(id)text;	// 0x31612fe9
- (void)setPrimaryInfoText:(id)text withAttributes:(id)attributes;	// 0x31613081
- (void)setShowUserEnteredText:(BOOL)text;	// 0x31612fa5
- (void)setTextEntryStyle:(int)style;	// 0x31613049
- (void)setTextEntryTextFieldLabel:(id)label;	// 0x31613029
- (void)setTextFieldDelegate:(id)delegate;	// 0x31613009
@end

