/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRHorizontalSegmentedWidget.h"


__attribute__((visibility("hidden")))
@interface BRTextFieldBackgroundLayer : BRHorizontalSegmentedWidget {
}
- (id)init;	// 0x315af859
@end

