/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"
#import "BRTextField.h"

@class NSMutableString, NSDictionary, BRMarqueeTextControl;

@interface BRTextFieldControl : BRControl <BRTextField> {
@private
	id _delegate;	// 40 = 0x28
	id _characterDelegate;	// 44 = 0x2c
	BRMarqueeTextControl *_displayString;	// 48 = 0x30
	NSMutableString *_clearString;	// 52 = 0x34
	NSDictionary *_savedAttributes;	// 56 = 0x38
	BOOL _useSecureText;	// 60 = 0x3c
	BOOL _showCursor;	// 61 = 0x3d
}
@property(assign) id characterDelegate;	// G=0x31658dd9; S=0x31658de9; converted property
@property(assign) id delegate;	// G=0x31658db9; S=0x31658dc9; converted property
@property(assign) BOOL showCursor;	// G=0x31658df9; S=0x31659189; converted property
@property(retain) id textAttributes;	// G=0x31658e19; S=0x316590dd; converted property
@property(assign) BOOL useSecureText;	// G=0x31658e09; S=0x31659155; converted property
- (id)init;	// 0x31659229
- (id)_secureTextFromClearText;	// 0x31658e55
- (BOOL)brEventAction:(id)action;	// 0x31658e29
- (BOOL)brKeyEvent:(id)event;	// 0x31659379
// converted property getter: - (id)characterDelegate;	// 0x31658dd9
- (void)dealloc;	// 0x316591bd
// converted property getter: - (id)delegate;	// 0x31658db9
- (float)maxScrollPosition;	// 0x31658f8d
- (BOOL)needsScrollingInBounds:(CGRect)bounds;	// 0x31658fad
// converted property setter: - (void)setCharacterDelegate:(id)delegate;	// 0x31658de9
- (void)setClearString:(id)string;	// 0x31658ff9
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x31658dc9
- (void)setDisplayString:(id)string;	// 0x31659049
- (void)setScrollPosition:(float)position;	// 0x31658f6d
// converted property setter: - (void)setShowCursor:(BOOL)cursor;	// 0x31659189
- (void)setString:(id)string;	// 0x31658ee9
// converted property setter: - (void)setTextAttributes:(id)attributes;	// 0x316590dd
// converted property setter: - (void)setUseSecureText:(BOOL)text;	// 0x31659155
// converted property getter: - (BOOL)showCursor;	// 0x31658df9
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x3165933d
- (id)stringValue;	// 0x31658f3d
// converted property getter: - (id)textAttributes;	// 0x31658e19
// converted property getter: - (BOOL)useSecureText;	// 0x31658e09
@end

