/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRTextEntryController.h"
#import "BRTextFieldDelegate.h"

@class NSString;

@interface BRTextEntryDialog : BRTextEntryController <BRTextFieldDelegate> {
@private
	NSString *_dialogID;	// 108 = 0x6c
	BOOL _canceled;	// 112 = 0x70
}
@property(readonly, retain) NSString *dialogID;	// G=0x316136a1; converted property
- (BOOL)brEventAction:(id)action;	// 0x316135c9
- (void)dealloc;	// 0x31613659
// converted property getter: - (id)dialogID;	// 0x316136a1
- (id)runModal;	// 0x31613529
- (void)textDidChange:(id)text;	// 0x316134f1
- (void)textDidEndEditing:(id)text;	// 0x316134f5
@end

