/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"
#import "BRAXTitleChangeProtocol.h"

@class NSAttributedString;

@interface BRTextControl : BRControl <BRAXTitleChangeProtocol> {
@private
	NSAttributedString *_string;	// 40 = 0x28
}
@property(retain) id attributedString;	// G=0x31596ba5; S=0x31596bb5; converted property
- (id)init;	// 0x315953f9
- (void)_shrinkTextToFitInBounds:(CGSize)bounds;	// 0x31607f39
- (void)_shrinkTextToTwoLines:(CGSize)twoLines;	// 0x31607d29
// converted property getter: - (id)attributedString;	// 0x31596ba5
- (id)axTitleText;	// 0x315f7c55
- (void)dealloc;	// 0x3159a591
- (void)drawInContext:(CGContextRef)context;	// 0x3159d185
- (CGSize)renderedSize;	// 0x3159efcd
- (CGSize)renderedSizeWithMaxSize:(CGSize)maxSize;	// 0x3159d021
// converted property setter: - (void)setAttributedString:(id)string;	// 0x31596bb5
- (void)setMaxSize:(CGSize)size;	// 0x315a500d
- (void)setText:(id)text withAttributes:(id)attributes;	// 0x315a2649
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x315f7c79
@end

