/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@protocol BRTransientPlaybackRange
@property(assign) unsigned startTimeInMS;	// converted property
@property(assign) unsigned stopTimeInMS;	// converted property
// converted property setter: - (void)setStartTimeInMS:(unsigned)ms;
// converted property setter: - (void)setStopTimeInMS:(unsigned)ms;
- (unsigned)startChapter;
// converted property getter: - (unsigned)startTimeInMS;
- (unsigned)stopChapter;
// converted property getter: - (unsigned)stopTimeInMS;
@end

