/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"

@class BRWaitSpinnerControl, BRTextControl;

@interface BRWaitPromptControl : BRControl {
@private
	BRWaitSpinnerControl *_spinner;	// 40 = 0x28
	BRTextControl *_prompt;	// 44 = 0x2c
}
@property(retain) BRTextControl *prompt;	// G=0x315ab339; S=0x315a58dd; converted property
@property(retain) id promptText;	// G=0x316063dd; S=0x3160640d; converted property
+ (id)themeAttributes;	// 0x315b0ffd
- (id)init;	// 0x315a541d
- (void)dealloc;	// 0x315a6429
- (void)layoutSubcontrols;	// 0x31606495
// converted property getter: - (id)prompt;	// 0x315ab339
// converted property getter: - (id)promptText;	// 0x316063dd
// converted property setter: - (void)setPrompt:(id)prompt;	// 0x315a58dd
// converted property setter: - (void)setPromptText:(id)text;	// 0x3160640d
@end

