/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import "BRControl.h"


__attribute__((visibility("hidden")))
@interface BRWebPointerControl : BRControl {
}
- (id)init;	// 0x3165bc15
- (id)preferredActionForKey:(id)key;	// 0x3165bbbd
@end

