/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"

@interface CALayer (ControlCheaters)
- (id)_owningControl;	// 0x315d30bd
@end

@interface CALayer (DirtyLayout)
- (void)setNeedsLayoutOnAllSublayers;	// 0x315d48d5
@end

@interface CALayer (BRScalingLayoutManager)
@property(assign) CGRect scaledFrame;	// G=0x3161ec15; S=0x3161ec5d; converted property
// converted property getter: - (CGRect)scaledFrame;	// 0x3161ec15
// converted property setter: - (void)setScaledFrame:(CGRect)frame;	// 0x3161ec5d
@end

@interface CALayer (BRCALayerAdditions)
- (void)addBasicAnimationForProperty:(id)property fromValue:(id)value toValue:(id)value3 duration:(double)duration timingFunction:(id)function delegate:(id)delegate;	// 0x3163d041
- (id)firstLayerNamed:(id)named;	// 0x3163d111
@end

