/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */



@interface DOMHTMLInputElement (TextEntryAssistants)
@property(retain) id nodeStringValue;	// G=0x3165b6f5; S=0x3165b6e1; converted property
- (int)formPeriperalType;	// 0x3165b6a1
- (BOOL)isSecure;	// 0x3165b745
- (BOOL)isTextControl;	// 0x3165b771
- (BOOL)nodeCanBecomeFirstResponder;	// 0x3165b709
// converted property getter: - (id)nodeStringValue;	// 0x3165b6f5
// converted property setter: - (void)setNodeStringValue:(id)value;	// 0x3165b6e1
@end

