/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */


@class BRScrollControl;

__attribute__((visibility("hidden")))
@interface ScrollAnimationDelegate : NSObject {
@private
	BRScrollControl *_scroll;	// 4 = 0x4
	long _animationBalance;	// 8 = 0x8
}
- (id)initWithScroll:(id)scroll;	// 0x31595c95
- (void)animationDidStart:(id)animation;	// 0x315ae11d
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x315ae1b5
- (void)clearScroll;	// 0x31671081
- (BOOL)scrolling;	// 0x31671069
@end

